### ISSUE TITLE
Unclear how to update code following version increment

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1006]
@aymanhab Please see [PrescribedForce::updateFromXMLNode()](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/PrescribedForce.cpp#L81). Your comment indicates that the test "needs to change when we have a new version number" but it isn't clear how it should be changed.

**Comment by aymanhab** [comment]
Thanks @tkuchida Indeed the test should change to (versionNumber < 30506) so that conversion is invoked exactly once and only when needed. I can open PR for this one but there're likely more places that need to make this check. 

On recurring version increment to newVersionNumber, developers should introduce code that manipulates old xml layout to new layout in a block and guard the block with a check that conversion is needed (usually version < newVersionNumber).
