### ISSUE TITLE
Change return type from void to self& to allow cascading method calls

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1013]
Here's an example from the DecorativeGeometry class in Simbody (from [here](https://github.com/simbody/simbody/blob/master/SimTKcommon/Geometry/include/SimTKcommon/internal/DecorativeGeometry.h#L211)):

``` cpp
DecorativeGeometry& setColor(const Vec3& rgb);
```

which allows code like this (from [here](https://github.com/simbody/simbody/blob/master/Simbody/tests/adhoc/GeometryPlayground.cpp#L128)):

``` cpp
Decorations dec; dec.setColor(color).setLineThickness(2);
```

This feature might be nice for methods like `Model::addBody()` and `Model::addJoint()`, turning this

``` cpp
myModel.addBody(pelvis);
myModel.addBody(thigh);
myModel.addJoint(hip);
```

into this

``` cpp
myModel.addBody(pelvis).addBody(thigh).addJoint(hip);
```

**Comment by aymanhab** [comment]
@tkuchida While I like cascading calls to set independent attributes, I'd worry about the cascading behavior when doing structural changes (that can potentially throw exceptions or be problematic), for example do we need to add the bodies first then the joint that connects them? What happens if not done in proper order?. Do we need calls to connect/init/traverse/.... in between? Also it's likely the code to create the bodies and joints will dwarf the line that adds them to the model so the gain may not be worth it trading clarity for code-size, but that's my personal opinion, good to know what others think :thought_balloon:

**Comment by chrisdembia** [comment]
I don't even like Simbody's use of cascading class. I do think it would be interesting to have an `add()` method that returned the thing you added:

```
Body& b = model.add<Body>("body_name", mass, massCenter, inertia);
```

**Comment by tkuchida** [comment]
Good point @aymanhab about limiting to operations that are commutative.
