### ISSUE TITLE
Visualizer doesn't apply ModelDisplayHints "show_frames" property

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1023]
ModelDisplayHints has a property for showing/hiding frames but setting this property has no effect.

**Comment by aymanhab** [comment]
@tkuchida Is there a branch you're working off that I can use to test? Thanks.

**Comment by tkuchida** [comment]
> Is there a branch you're working off that I can use to test?

Not yet. Can these features be exercised in testVisualization?

**Comment by aymanhab** [comment]
@tkuchida testVisualization uses a model with static geometry, I can modify it to run a few times with a variety of DisplayHints but to actually see what's drawn on screen is a different issue!

**Comment by tkuchida** [comment]
Whether it's in testVisualization or elsewhere, I think there should be a dedicated test/example for exercising the visualizer (e.g., to ensure transformations are applied correctly in all `generateDecorations()` methods).

**Comment by aymanhab** [comment]
Agreed, I'm considering the options.

**Comment by aymanhab** [comment]
@tkuchida I made a branch and made fixes on it to make sure DisplayHints are respected. I'll also add a test case. DisplayHints however can't be applied retrospectively on objects that are already displayed since the State is never cached, so there's no way to regenerate the scene, i.e. it affects only future drawings or you set the flags in the your program before you launch the visualizer. 
@chrisdembia or @jimmyDunne or @carmichaelong Do you know if that ever worked (that toggles on the API visualizer menus affected the already displayed scene?) If not it'd be a new functionality that we can do later if we have time. Thanks.

**Comment by chrisdembia** [comment]
> Do you know if that ever worked (that toggles on the API visualizer menus affected the already displayed scene?)

I don't know; sorry.
