### ISSUE TITLE
Unable to create ConsoleReporter for SpatialVecs

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1097]
Presumably missing a specialization for SpatialVecs. Likely affects TableReporter as well.

**Comment by jenhicks** [comment]
@klshrinidhi Is this fixed?

**Comment by klshrinidhi** [comment]
Not sure. I will get back.

**Comment by jenhicks** [comment]
If it's not already done, then we could hold until post 4.0. Let me know what you find out.

**Comment by klshrinidhi** [comment]
It looks like (as @tkuchida mentioned) `ConsoleReporter` currently does not have (special) code to handle anything other than `double`.  If the type `T` in `ConsoleReporter<T>` supports `operator<<()`, it will work in theory. The resulting output on the terminal/console may not be properly formatted. Since types like `UnitVec3`, `SpatialVec`, `Quaternion`, `Vec<N>` currently do not have support for `operator<<()`, they should refuse to compile.

On the other `TableReporter` should support all types that `TimeSeriesTable` supports because it does not do anything with the incoming values. It just stores them in the `TimeSeriesTable`.

**Comment by jenhicks** [comment]
Ok based on discussion with @aymanhab and @aseth1 I am going to postpone this until next release, but we can prioritize if needed.
