### ISSUE TITLE
[visualizer] Visualizer crashes if the model contains disabled muscles

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1111]

**Comment by tkuchida** [comment]
Presumably, `GeometryPath::generateDecorations()` should return immediately if the muscle is disabled.

**Comment by aseth1** [comment]
I would like us to work out a mechanism so that any Component can be "disabled". In particular, "disabled" would mean it is not part of the Component tree so *none* of the Component interface methods are invoked on the disabled Component. You would have to "enable" the Component and call `finalizeFromProperties()` to have it in included again. See also  #845.

I think this would be better than surgically handling what "disable" does on different Components.

@tkuchida @chrisdembia @aymanhab what do you think?

**Comment by chrisdembia** [comment]
I like that idea a lot. This is more possible now that the "subcomponents" data structure is not the properties itself, but something filled up from the properties. So it should be fairly easy to handle. 

Should still probably fix this bug in the meantime.

**Comment by tkuchida** [comment]
> "disabled" would mean it is not part of the Component tree so *none* of the Component interface methods are invoked on the disabled Component.

I like that idea. It sounds like that would allow you to disable a Component that isn't working and it would be entirely ignored (i.e., behavior would be identical if it weren't added to the Model at all), which could be useful for debugging.

> Should still probably fix this bug in the meantime.

This bug likely affects lots of Components, so it might be best to just tackle the problem at the Component level in one fell swoop.

**Comment by aymanhab** [comment]
I completely agree as well. Deciding what that means for various components is a bit harder, but that's a topic for discussion.

**Comment by aymanhab** [comment]
@aseth1 This will be important to solve in 4.0 The main issue is that the GeometryPath doesn't know that the Muscle is disabled. Any thoughts?

**Comment by aseth1** [comment]
Possible solutions:

1. Implement DevProp #1382 so that any Component can be temporarily excluded without crashing.
2. Figure out which calls to `GeometryPath` *blow-up* and band-aid the problem by checking the *appliesForce* flag first. With the rename to `appliesForce`, there should be no expectations that the Muscle should not draw itself - it simply should not apply forces - and we could still have the muscle draw itself.

**Comment by aymanhab** [comment]
Thanks @aseth1 I think we greed already that DevProp is outside the scope of 4.0 as it introduces new concepts. For solution 2, the crash happens while trying to get the CacheEntry  "current_path". Incidently the CacheEntry does exist but retrieving the value throws an exception. This can be made more consistent I think.

**Comment by aseth1** [comment]
>  Incidently the CacheEntry does exist but retrieving the value throws an exception. This can be made more consistent I think.

Yes @aymanhab there was a bug and it is being addressed in #1444.
