### ISSUE TITLE
improve standards files in testVisualization

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1190]
As of now w euse a surrogate (text file) to test that visualization primitives have not changed due to code changes as a surrogate to actual visualization which can't be practically tested cross platform without user intervention. This issue is a place holder to come up with alternatives or implement improvements.

**Comment by aymanhab** [comment]
As of now each primitive writes out all its attributes/members regardless of what's used and how. without trying to map into human readable quantities because for example, most colors do not map up to names (only a handful) draw options are enums (converting to string to compare is an additional source of errors due to spaces, case conversion etc.)

**Comment by aseth1** [comment]
@aymanhab Adding the image is nice for reassuring the developer that nothing has materially changed, but when the test still fails, what do you do? I have a test failure now due to the fact that the order has changed, which should not fail the test- or should it?

**Comment by aymanhab** [comment]
@aseth1 Actually as it is the test will fail since the file has the primitives in "processing" order which is similar to how state names/vectors were used in the past. Indeed this is not very robust but that's why the standards file is kept short so you can diff, and update the standard if the order is different but the contents are same but I'm open to suggestions for improvements.

**Comment by aseth1** [comment]
One idea is to do away with the standard files altogether. The essence of the test is that the correct silo of decorative geometry is created by the Model (as top level with contributions from all its subs). Serializing that Silo forces the test to be text diff exercise which is far to stringent. Instead, why not create the standard silo programmitcally and the compare the two silos. We can then get around order issues. It may require implementing `==`  on DecorativeGeometry but I think that would be more robust.

I really don't like having to update the standard. What happens if we miss something? It is easy to overlook a detail like color, opacity value or even a component of the transform.

**Comment by aymanhab** [comment]
That could be an improvement @aseth1 but I think the crux of the matter is not whether the objects are built programmatically or from a file vs. whether order matters (if that was a list of objects in memory and the comparison went in order then the test would fail, though the fix would be easier. The primitive DecorativeGeometry and subclasses live on the Simbody side so changing them is a big deal but something to consider. 

I don't think anybody else is changing the traversal order or how components are wired so for now feel free to change the std file and I'll review to make sure nothing slips.
