### ISSUE TITLE
Mapping templatized C++ classes to Scripting is unclear or undocumented

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1251]
We use quite a few classes in our API that are templatized. Examples in C++ mostly utilize the template syntax. Scripting users, particularly in Matlab are not given a mapping between these classes and Java or Python classes. The naming is also left to the developers writing the interface files for SWIG. It would be great help if the mapping is documented somewhere. Issue came during discussion of #1206

**Comment by aseth1** [comment]
@tkuchida proposed:

> If possible, I think it would be best to present Matlab users with methods of the form STOFileAdapter:cow: or STOFileAdapter_:cow:, where :cow: is always the type (double, Vec3, etc.). Otherwise, the user needs to remember :cow: = (type == double) ? null : type.

I think adding `Double` for the type used 99% of the time can be less convenient/confusing for the common/typical use cases. I am also in favor of consistency. So if it is unanimous to have all wrapped template classes named as `<class_name><type_name_with_leading_uppercase>` then so be it. 

But, do you really want `TransformDouble`, `MatrixDouble`, ... I also find it confusing for sets, `SetFunction`, `SetForce` etc... sound like the objects are being set (not a a Set of Forces) and although consistent with the convention seems more confusing to me.

**Comment by aymanhab** [comment]
I think there are two cases that may need to be treated differently but all need to be documented. 
SimTK's Vector_<double> typedef into Vector needs to be preserved for users to read/follow the SimTK code/examples as well as for convenience but when the template argument can be anything (e.g. Double, Vec3, Vec6 etc. then I'd prefer to append Double/Vector etc.). Just important to have "a" convention and a mechanism to communicate to users and future developers.

**Comment by tkuchida** [comment]
> I think adding `Double` for the type used 99% of the time can be less convenient/confusing for the common/typical use cases. […] do you really want `TransformDouble`, `MatrixDouble`, ... I also find it confusing for sets, `SetFunction`, `SetForce` etc... sound like the objects are being set (not a a Set of Forces) and although consistent with the convention seems more confusing to me.

I will explain the rationale for my suggestion in detail.

1. Ideally the type would be resolved automatically, which would align with Matlab's implicit typing; however, this is not possible with SWIG alone AFAIK. Perhaps this is something we could do if we release utility .m files along with the 4.0 release.

2. According to your statistics, users will need to use a non-double version 1% of the time. The first thing I would try is the vanilla method (e.g., `Transform`). If the error message is informative, then I agree that dropping the `Double` would be fine.

3. My expectation is that the error messages are not currently informative, or that some are and some are not. Establishing a convention where the type is baked into the method name would give the user a hint about what method to use even in the absence of helpful error messages or doxygen/Confluence documentation.

**Comment by aseth1** [comment]
@tkuchida I like the idea of 1 but I don't know how feasible it will be to create and test utility scripts to handle conversion for each type. We could try.

2. I merely used 99% to indicate overwhelming use of- not that it is statistically accurate. In the case of `Transform`, `Matrix` and others I am quite certain there is no usage of non double types because non double types are not wrapped. So as @aymanhab suggests it may be useful to look at C++ usage and see where a typedef is being used to mask the template (e.g. Vector = Vector_<SimTK::Real>). I agree that getting informative messages if/when you use the wrong type is key. So if you try to stuff a Vec3 into an element a Vector, you would ideally get a message about the element type not being compatible with the Vector_<double> type. 

3. I agree. I am favor of consistency. I just wanted to raise some cases where it may not make sense (`Transform`, `Matrix`, `SpatialVec` and others) where there is an implicit assumption even in C++ that these are doubles and AFAIK do not have any other types wrapped.  The other case is for `Set<T>` where `SetForce`  may not be as clear as `SetOfForces` which violates the aforementioned naming convention but is easier to understand what it is. 

Please do not interpret my raising of  these cases as reasons against a convention - I am in favor of it. Perhaps there is a naming rule like `Container<T>` C++ is wrapped as `ContainerOfTs` or something else which also works for Sets.

**Comment by chrisdembia** [comment]
I think we can close this issue: see [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Common+Scripting+Commands#CommonScriptingCommands-HandlingC++Templates(e.g.Array<double>))
