### ISSUE TITLE
ComponentPath::getComponentName() crashes when getNumPathLevels() == 0

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1307]
The following code causes a crash:

```cpp
ComponentPath path("");
path.getComponentName();
```

What should the expected behavior be? I can think of two options:

1. Return an empty string; `""`.
2. Throw an exception, saying the ComponentPath is empty.

**Comment by carmichaelong** [comment]
Of the three uses of `getComponentName()` in the Component class, one function checks if there is an empty name (`findComponent()`) and two functions do not (`findAndConnect()` and `traversePathToComponent()`).

I think this currently points at doing option 1, since it seems like Component currently handles the empty name, but I don't know what the complete vision is for the Component class.

**Comment by aseth1** [comment]
Closed by #1336
