### ISSUE TITLE
Disabled flag for ContactForce is ignored

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1358]
While trying to test behavior of ContactGeometry when the corresponding Contact Force is disabled (in XML), the flag appeared to be ignored and a SimTK force was created regardless (though there's a possibility that the flag is taken into consideration downstream). Not sure what's the "desired" behavior of disabled Contact Forces. No tests verify behavior when Force is disabled AFAIK. If there's one that I missed, feel free to close.

**Comment by aseth1** [comment]
Disabling of a Force or a Constraint in Simbody does not exclude it from the System. It must be part of the ForceSubsystem to add its disable flag  (as a discrete State variable) and *disabling* simply updates its value. Downstream the contribution of the Force/Constraint is not computed or added to the System dynamics if disabled. It does not mean we can prevent the Force (or Constraint) from computing other things like distances that it uses at the Dynamics stage.

I don't think this is a bug. I am proposing a universal option to exclude Components (#1382) so that it is easy for users to test the effect of the presence/absence of a Component with greater confidence (without editing XML directly). I am not sure disabling as defined by Simbody was intended for *exclusion* use case.

**Comment by jenhicks** [comment]
Issue is due to (understandable) misinterpretation of the flag. Will rename flags. Also need to update behavior so components that aren't applying forces are still visualized.
