### ISSUE TITLE
Add documentation/sample code to help MATLAB users handle enums

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1456]
Some possible destinations for such documentation/sample code:
- [Common Scripting Commands](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Common+Scripting+Commands) page on Confluence
- Class description for `Frame`

### Example:
**C++**
```cpp
auto& rot = myFrame.getTransformInGround(state);
rot.convertThreeAxesRotationToThreeAngles(BodyRotationSequence,
                                          XAxis,
                                          YAxis,
                                          ZAxis);
```

**MATLAB**
```
rot = myFrame.getTransformInGround(state);
rot.convertThreeAxesRotationToThreeAngles(BodyOrSpaceType.BodyRotationSequence,
                                          CoordinateAxis(0),
                                          CoordinateAxis(1),
                                          CoordinateAxis(2));
```

**Comment by chrisdembia** [comment]
Both places!

**Comment by tkuchida** [comment]
@jimmyDunne Please add to this list if/when you encounter methods with a similar issue. :coffee:

**Comment by aymanhab** [comment]
This has to be addressed on a case by case basis since it's hard to come up with a generic rule. Now that Doxygen documentation is included in java source files we may point users to the SWIG produced Java files with embedded enums. E.g. 
https://github.com/opensim-org/opensim-gui/blob/c229bbb2f2a848d34b7a6f24b7fc6bf26f0a123d/Gui/opensim/modeling/src/org/opensim/modeling/Rotation.java#L281

Thoughts?

**Comment by tkuchida** [comment]
> Now that Doxygen documentation is included in java source files we may point users to the SWIG produced Java files with embedded enums.

Good idea, @aymanhab! Even just knowing where to dig (or Ctrl+F) might be helpful. #BlastFromThePast
