### ISSUE TITLE
Manager::stepTo()

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1462]
Especially for MATLAB, it would be great if the Manager had a method `stepTo()`, to allow the following:

```
man = Manager(model);
for i = 1:100
    t = i * 0.01;
    manager.stepTo(state, t);
end
```

@malborno @carmichaelong 

Raised during @malborno's hackathon project.

**Comment by jenhicks** [comment]
@carmichaelong Will investigate if this is an easy feature to add for 4.0. Otherwise, include in the next release.

**Comment by chrisdembia** [comment]
In today's dev meeting, @carmichaelong suggested the following logic within stepTo():

```
if state.getTime() < initial_time 
    integrate from initial_time to final_time
else
    integrate from state.getTime() to stepToTime.
```

I prefer the following:

```
/// Integrate from initial_time to final_time.
integrate();
/// Integrate from the state's current time to the provided time.
/// This ignores the Manager's initial_time and final_time fields.
stepTo(double time);
```

With such an interface, it is clear what the integration times will be. Also, we maintain consistency with Simbody's stepTo().

**Comment by aseth1** [comment]
I question the value of having initial and final time data members for the `Manager`, which is the cause of potential inconsistency.  What is the value or benefit of having the initial and final times as data members of the `Manager` since it is easy to set the time on the state and have  `integrate()` take a final time. Would it not be simpler, and less error prone to do something like this:

```cpp
// set the initial time of the state
state.setTime(initial_time);
// integrate from the current state (and its time) to a future state at final_time
manager.integrate(state, final_time);
```
The tools already store/serialize the integration times.  This would would not be a backward compatible for API users but it would have virtually no impact on Tool and GUI users. If we ever want to change the Manager interface, we should do it now.

**Comment by chrisdembia** [comment]
The manager in almost every piece of C++ user code, so I also agree that if we are to change this, we should do it for 4.0. However, my opinion is to leave in the initial_time/final_time data members. 

Another option is to deprecate the data members in 4.0.

**Comment by aseth1** [comment]
>Another option is to deprecate the data members in 4.0.

Yes, then also deprecate `integrate(state)` to use `integrate(state, final_time)`.

**Comment by carmichaelong** [comment]
@aseth1 It seems to me that in your preferred case, `integrate(state, final_time)` will essentially be equivalent to using `TimeStepper::stepTo()`?

**Comment by aseth1** [comment]
@carmichaelong yes, we would not need a separate `stepTo` in that case. That is one of the reasons I prefer it.
