### ISSUE TITLE
Issue in stiffness calculation in Millard Muscle Model

### ISSUE THREAD

**Issue by mshabani** [opensim-org/opensim-core#1515]
I am using OpenSim 3.3
In Millard2012EquilibriumMuscle.cpp line 1077 and 1078:

dFmAT_dlceAT = calc_DFiberForceAT_DFiberLengthAT(**dFm_dlce**,
                mli.sinPennationAngle, mli.cosPennationAngle, mli.fiberLength);

Method calc_DFiberForceAT_DFiberLengthAT receives fiber stiffness **dFm_dlce** as first input while it expects **dFmAT_d_lce** as its first input. Method's signature is: 

double Millard2012EquilibriumMuscle::
calc_DFiberForceAT_DFiberLengthAT(double dFmAT_d_lce,
                                  double sinPhi,
                                  double cosPhi,
                                  double lce) const

This issue results in wrong muscle stiffness calculation. 
To double check, I calculated muscle stiffness numerically and compared it to the stiffness calculated using this class. They don't match.

**Comment by tkuchida** [comment]
Thanks for reporting the bug, @mshabani! The same issue was raised in #1357 and was fixed in PR #1402 (which has been merged into master). Assuming you're building from source, you might want to make the same fix locally for now, and upgrade to 4.0 when you're feeling brave :wink: or when the beta is released.

@aseth1: should we backport PR #1402 to v3.3?

**Comment by mshabani** [comment]
Thank you so much for the fix. I will fix it locally for now.
Thanks,
Mohammad

**Comment by tkuchida** [comment]
Opened issue to track in opensim32 repo; closing.
