### ISSUE TITLE
Name of Connector::connected_to_name property

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#161]
I think the language surrounding connections still needs some cleaning up. I think this should just be "connectee". I still vote for a word other than connectee, but whatever that noun is should be the name of this property, I think. I feel that `connected_to_name` reads verbosely in the XML.

During the hackathon, we brainstormed some alternative names, like plug, socket (using a circuit analogy) I know some of them weren't good, but I think we should still discuss this.

I'm used to the "ee" syntax with Employer, Employee, in which both objects are of the same type. Connector and the connectee are not of the same type; Connector is a middle man.

**Comment by chrisdembia** [comment]
In #558 @sherm1 said

> I see I didn't like connector/connectee in #161 but I think I got used to it from Ajay using the term in discussions so I was surprised that it wan't used across the API. If it is used anywhere I'd like to see it used everywhere. "connectee" does have the advantages of (a) being a made-up word with no a priori meaning, (b) clearly being a noun, and (c) conciseness.



I am fine with `connectee` so long as we create a beautiful and clear diagram explaining all the new terms (connector, connectee, input, output), with a "plug" showing what a `connectee` is, etc., and we put this diagram where it will be found easily by component developers and users. I'm thinking in the description of the Component class, or preferably in our "Component developer guide", and perhaps in the user's guide as well.

**Comment by aseth1** [comment]
I've been reluctant to document when the names are in flux - the names are in flux because the terms are not liked - part of not liking them is that there is no clear documentation ... I will add to the [definitions.md](https://gist.github.com/aseth1/0d3e16028d985d6ed95d)  to start to address the latter problem at least. 

Consistency with the code would also be helpful. Changing `connected_to_name` to `connectee_name`, for example, would help.  @sherm1 you suggested that and sounds like @chrisdembia agrees. @jenhicks @aymanhab  OK with that?

**Comment by chrisdembia** [comment]
I'm closing this now since #572 is about to be merged.
