### ISSUE TITLE
addMarker() has an incorrect behavior (Matlab)

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#1659]
When adding markers using `model.addMarker()` I get weird behaviour that results in errors. 

(Below) I make a basic model and add a marker (in Matlab)
```
>> 
%% import java libraries
import org.opensim.modeling.*
model = Model();
model.setUseVisualizer(true);
r1  = Body('rod1', 1, Vec3(0), Inertia(0));

% first marker 
m = Marker(); 
m.setParentFrame(r1);
m.set_location(Vec3(0.1,0.5,0));  
m.setName('marker_1');

model.addMarker(m);
```

If I look at the initial marker added, I get the correct answer for the name (and other variables I wont show here)

```
model.getMarkerSet().get(0).getName() 
>> ans = marker_1

```
 
If I instantiate another marker, add it to the model, and then check the names, they are now incorrect (ordered and absolute). 

```
m2 = Marker(); 
m2.setParentFrame(r1); 
m2.set_location(Vec3(0.25,0.2,0.2)); 
m.setName('marker_2');

model.addMarker(m2);

model.getMarkerSet().get(0).getName()

>> ans = marker_2
 
model.getMarkerSet().get(1).getName()

>> ans = marker_

```

The more markers I add, the more random it gets. 

I can get better behavior if I use `model.getMarkerSet().adoptAndAppend()` , but I assume we will want this working correctly. 

Let me know if I can provide more info.

**Comment by aymanhab** [comment]
Did u mean m2.setName () ?



On Apr 13, 2017 5:53 PM, "jimmyDunne" <notifications@github.com> wrote:

When adding markers using model.addMarker() I get weird behaviour that
results in errors.

(Below) I make a basic model and add a marker (in Matlab)

>>
%% import java libraries
import org.opensim.modeling.*
model = Model();
model.setUseVisualizer(true);
r1  = Body('rod1', 1, Vec3(0), Inertia(0));

% first marker
m = Marker();
m.setParentFrame(r1);
m.set_location(Vec3(0.1,0.5,0));
m.setName('marker_1');

model.addMarker(m);

If I look at the initial marker added, I get the correct answer for the
name (and other variables I wont show here)

model.getMarkerSet().get(0).getName()
>> ans = marker_1


If I instantiate another marker, add it to the model, and then check the
names, they are now incorrect (ordered and absolute).

m2 = Marker();
m2.setParentFrame(r1);
m2.set_location(Vec3(0.25,0.2,0.2));
m.setName('marker_2');

model.addMarker(m2);

model.getMarkerSet().get(0).getName()

>> ans = marker_2

model.getMarkerSet().get(1).getName()

>> ans = marker_


The more markers I add, the more random it gets.

I can get better behavior if I use model.getMarkerSet().adoptAndAppend() ,
but I assume we will want this working correctly.

Let me know if I can provide more info.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opensim-org/opensim-core/issues/1659>, or mute the
thread

**Comment by jimmyDunne** [comment]
ahh, I see. That was an error on my part. 

I was messing up some of the setName() property which, now fixed, seems to have solved the problem. 

I guess all the markers need unique names..
