### ISSUE TITLE
Document removal of reverse flag on confluence

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1709]
Joint constructors no longer have _reverse_ flag (appears on [this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Common+Scripting+Commands), [this page](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Part+II:+Building+a+Passive+Dynamic+Walker+Model), and likely others)

**Comment by tkuchida** [comment]
Searched "OpenSim Documentation" space for "reverse"; updated the following pages:
- [\_\_40\_\_{WIP} Common Scripting Commands](http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__%7BWIP%7D+Common+Scripting+Commands)
- [\_\_40\_\_Common Scripting Commands](http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Common+Scripting+Commands)
- [\_\_40\_\_Property Editor](http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Property+Editor)

The issue description (up top) refers to the "Common Scripting Commands" page and the "From the Ground Up: Building a Passive Dynamic Walker Model" page. The former was updated, but the latter was not because it seems that no analogous "\_\_40\_\_" page exists. @jenhicks: Are we updating the examples separately?
