### ISSUE TITLE
Update instructions for configureOpenSim.m on confluence

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#1710]
http://simtk-confluence.stanford.edu:8080/display/OpenSim/Scripting+with+Matlab

**Comment by chrisdembia** [comment]
I can do this.

**Comment by chrisdembia** [comment]
The "Scripting with Matlab" confluence page provides links to the Matlab scripts in the GitHub repository. This is very handy. Right now, the commit hashes in the links are for an older version of OpenSim (presumably 3.3). When we release 4.0, we should make sure these links go to the 4.0 version of these files on GitHub. Or perhaps we should just always link to the version in the master branch? It might be difficult to remember to update these links with each release. @jimmyDunne your input would be valuable.

**Comment by chrisdembia** [comment]
I've updated the "configureOpenSim.m" section: http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Scripting+with+Matlab.

I decided to remove the "manual" instructions, since they are will be out of date for 4.0 and should not be necessary. I replaced the manual instructions with a description of what the configuring process entails.

**Comment by chrisdembia** [comment]
The "Setting up your Matlab Scripting Environment" section of the "__40__Scripting with Matlab" page is ready for review.

**Comment by jimmyDunne** [comment]
Scripting users aren't going to realize that `methods org.opensim.modeling.Model` is for viewing the methods without importing the libraries. Also, (only) saying `methodsview Model` also doesn't intuitively suggest to a user that you can do this on any class (scripting users often don't know what class means since they haven't done object orientated programming). I would suggest using two or three examples for each and add some `% Comments`

I realize that the script you wrote is working well, but I disagree with removing the manual instructions. There may still be instances when the script fails that we will be unaware of until public Beta; it seems premature to assume that this will work under all conditions.

**Comment by chrisdembia** [comment]
Thanks @jimmyDunne. I'll update the "Loading OpenSim Libraries" section and I'll create new manual instructions for setting up the environment (since the process has changed).

As for the links in the "Available Matlab Scripts" section, I think we should eventually have a branch on GitHub called "v4" that we update with each minor/patch release, and the links could be to this branch. That way, they stay up to date automatically (until v5) and we avoid having the documentation point to in-development versions of the scripts.

**Comment by chrisdembia** [comment]
@aymanhab @jimmyDunne the Confluence instructions currently say the following:

> By default, if Java exceptions occur, Matlab will exit and save debug information to a log file in the current workspace. If this happens please send us the stack trace or crash report to fix. You don't need to setDebugLevel as of version 3.1. For previous versions you can call
OpenSimObject.setDebugLevel(3);

I'd like to remove this section, because I think the OpenSim exceptions no longer cause MATLAB to crash, in general. What do you think?

**Comment by chrisdembia** [comment]
@jimmyDunne I have tried to address your comments (http://simtk-confluence.stanford.edu:8080/display/OpenSim/__40__Scripting+with+Matlab):

- Added more examples and comments to the "Loading OpenSim Libraries" section.
- Added new "manual setup" instructions.

**Comment by aymanhab** [comment]
I agree, exceptions are handled better and don't cause a crash of Matlab, this only happens if dereferencing null pointers. Feel free to remove.

**Comment by chrisdembia** [comment]
Thanks @aymanhab; I have gone ahead and removed the section. If others disagree, we can easily add it back.

**Comment by jimmyDunne** [comment]
Will need to update once #2174 is merged.
