### ISSUE TITLE
In updating XML of VisibleObject DisplayGeometry, orientation from transform not preserved

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#1759]
I do not believe that the updateFromXMLNode code for updating VisibleObject DisplayGeometry properly carries over the DisplayGeometry's orientation portion of the transform. 

I discovered this bug by inspecting [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/PhysicalFrame.cpp#L352), which I think should say use `"orientation"` instead of `"rotation"`.

Locally, I did a quick test to verify that the orientation is not carried over (I edited a pre-4.0 model to have a non-zero orientation, and it did not appear in the updated XML file).

**Comment by aymanhab** [comment]
Thanks for reporting @chrisdembia My recollection is that this was tested with existing models that needed conversion and that none actually had non trivial transform for visibleObject since it was never exposed in the GUI while the transforms attached to DisplayGeometry were available and were thoroughly tested. I'm curious how you ran into this (to understand the scope). If the xml tag is incorrect/invalid then we should definitely fix it. Thank you.

**Comment by chrisdembia** [comment]
I did not find any models that specified non-zero orientations for the DisplayGeometry's transform (but I did not look at at all that many models). I had to edit a pre-existing model to observe the bug.

I discovered this while working on #1751, since I am editing the `PhysicalFrame::createFrameForXform()` function.

**Comment by aymanhab** [comment]
Thanks @chrisdembia that explains. Feel free to submit PR for the fix/label-change.

**Comment by chrisdembia** [comment]
THere is a fix to this bug in #1751. If it's going to take too long to merge #1751, I could split the fix to this issue into a separate PR.

**Comment by aseth1** [comment]
Closed by #1751

**Comment by chrisdembia** [comment]
Thanks for closing.
