### ISSUE TITLE
Numeric properties load with many extraneous digits

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1804]
For example, the mass_center property of femur_r in gait1018_wArms.osim is "0 -0.17 0" in the .osim file but "0 -0.17000000000000001 0" appears in the GUI (opensim4.0Beta0627_win64.zip). Particularly undesirable for an introductory tutorial.

**Comment by tkuchida** [comment]
Another example (from Confluence):
![](http://simtk-confluence.stanford.edu:8080/download/attachments/3376207/function-3.PNG?version=1&modificationDate=1349822297234&api=v2)

**Comment by tkuchida** [comment]
See discussion in [opensim-gui issue 259](https://github.com/opensim-org/opensim-gui/issues/259).

**Comment by jenhicks** [comment]
Is this an opensim-core issue @aymanhab

**Comment by aymanhab** [comment]
Yes, AFAIK. the toString method called by the GUI ends up calling printUnformatted which prints excess digits. We could override on API side to use some formatting (e.g. %g).

**Comment by aseth1** [comment]
We could do a better job handling formatting properties out to string.
`Property::toString()` calls  `Property::writeSimplePropertyToStream(outstream)` which currently invokes `SimTK::writeUnformatted(outstream, values)` which appears to write values to stream in full precision separated by spaces (if vector value).  There is no `SimTK::writeFormatted()` in general, and it appears to only add brackets and comma separate elements in the case of Arrays but does not appear control the number of sig figs, AFAICT.

Talking with @carmichaelong a potential solution is to have a global setting (user preference) to display sig figs of properties (e.g. default 8). The same preference could be used to write properties to XML or we could have separate *PropertyDisplayPrecision* and *PropertyWritePrecision* (something like that) or just leave file writing at full precision.

In any case we would need to override `Property::toString()` on new properties to format output. We see mixed behaviors in 3.3 because new properties use unformatted and deprecated properties do something along the lines of:
```cpp
string PropertyDblArray::toString() const
{
    string str = "(";
    char dbl[256];
    for(int i=0; i < _array.getSize(); i++){
        sprintf(dbl, "%g", _array[i]);
        str += (i>0?" ":"") + string(dbl);
    }
    str += ")";
    return str;
}
```
 We could make properties format like the deprecated, which is what @aymanhab seems to be advocating.

**Comment by chrisdembia** [comment]
I like the idea that the XML files serialize the exact numbers in full precision, for reproducibility. The GUI use some type of truncating when displaying numbers.

**Comment by aymanhab** [comment]
This issue is becoming more annoying, especially that it was introduced in 4.0 (probably due to conversion to the new property system across the board) would be important to fix for 4.0

**Comment by chrisdembia** [comment]
I think @carmichaelong is considering a fix.

**Comment by carmichaelong** [comment]
I have a first shot at a fix ready for a PR, but there's some problem with git on my computer right now that I have to solve first.
