### ISSUE TITLE
Methods invoked from Tools that exercise editing should document behavior

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#1815]
While tools haven't primarily changed for 4.0, the semantics/behavior of the methods (that are still available) have changed. Because we consider some of these methods as "Editing" now, an explicit call to initSystem is required. This caused problems that were hard to find earlier for ScaleTool (issue with replaceMarkerSet) and later with AnalyzeTool (updateModelForces). We should either document this in methods, or use different named methods in 4.0 and keep semantics of old methods the same to avoid seeming instability of 4.0. Unfortunately not calling initSystem doesn't always lead to immediate/clear error messages, and these are few examples.

**Comment by jimmyDunne** [comment]
When system is invalid, message to finalizeFromProperties() or initSystem()

**Comment by aseth1** [comment]
@aymanhab The fact that we could edit models after creating a System without recourse, in my view,  was a weakness/bug in previous versions of OpenSim and not a feature lost. The previous "semantics" were highly prone to bugs and hard to trace errors with changes to objects that would have not effect on the system.  These are not new problems, just that they are now detectable because of the stricter editing and system building process. I don't think we should document every  model editing method in the API to remind users they must `finalizeFromProperties()` after they make a change to the model.

I agree that we should provide swift and informative messages when errors are detected. Can you list the context/ method calls that led to the problems you ran into? I can then make sure that informative errors are thrown in these cases. Thanks!
