### ISSUE TITLE
Improve checks for naming Components

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1876]
- For as long as OpenSim uses its own methods for parsing path strings, Component names containing characters like `/`, `.`, and `:` are prohibited.
- A Body cannot be named "Ground". (addressed in #2285).
- Components must have unique absolute path names.

These checks could be added to `{Component|Model}::finalizeFromProperties()` and provide helpful user-facing messages.

Related: #337, #1866.

**Comment by aseth1** [comment]
I might separate the issue into:
1.  catch invalid form of a `ComponentPath` (e.g. flagging illegal characters) 
2.  inform the user of ambiguity due to multiple components with the same path (upon deserialization)
3.  prevent `Ground` component from being renamed
4.  flag "Ground" (and its variants) as an illegal `Body` name

**Comment by tkuchida** [comment]
Perhaps we should include in :four: a check for illegal characters in the `name` property string.
