### ISSUE TITLE
runtime_error exception throws red-circle "unexpected exception" in GUI

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1877]
The `runtime_error` thrown by Simbody's MultibodyGraphMaker is not wrapped and leads to a red-circle exception in the GUI when attempting to load a model that contains bodies/joints with non-unique absolute path names. See #1768 and #1866.

<pre>
java.lang.RuntimeException: addBody(): Duplicate body name '/subject01/tibia'
	at org.opensim.modeling.opensimSimulationJNI.Model_initSystem(Native Method)
	at org.opensim.modeling.Model.initSystem(Model.java:840)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:144)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:139)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:100)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>

Possible solutions include (1) wrapping the `runtime_error` exception; (2) catching and re-throwing with the additional message requested in #1768; and (3) implementing a general component validation mechanism (see #1876).

**Comment by aseth1** [comment]
I don't see a component level *validator* as being a feasible option for catching non-unique paths. Only the top-level (root) component can do that. We can use `ComponentPath` type property instead of string to store component paths and beef it up so it validates the form of the path, but it cannot verify that it is a unique path.

 Catching the `runtime_error` and presenting a meaningful message seems like a good solution here.

**Comment by tkuchida** [comment]
> I don't see a component level *validator* as being a feasible option for catching non-unique paths. Only the top-level (root) component can do that.

That conflicts with my understanding of the Component API design. Since (i) Components own other Components and (ii) Model is a type of Component, it would seem that the problem can be avoided if each Component ensures its own children are uniquely named.

**Comment by aseth1** [comment]
Checking uniqueness of individual paths is only effective at the top level. Sure, you can have a component check every-time subcomponents are added, but that seems potentially wasteful since we must check again with a complete tree.

`Component::addComponent()` does a check that the added component is uniquely present in the tree by delegating up to its root to do the check, so there is some precedent for always checking. However, comparing references is a lot faster than strings. This check ensures that when building a model programmatically its components are unique. 

The issue we might be with deserilzation of models with non-unique names at the same level and type. This should be illegal. OpenSim 3.3 and earlier may not have complained with multiple bodies of the same name, but that doesn't mean it was being handled correctly. I don't think there is a *correct* option here . It likely only involved the first `Body` (or thing) and neglected the second instance altogether. So throwing an exception to alert the user to the ambiguity at connection time seems perfectly reasonable to me.

I'll look at the problematic model(s) to confirm.

**Comment by tkuchida** [comment]
> Checking uniqueness of individual paths is only effective at the top level. Sure, you can have a component check every-time subcomponents are added, but that seems potentially wasteful since we must check again with a complete tree.

I don't understand why it would be wasteful or why you would need to check again with a complete tree. Each Component (including Model) should ensure that its immediate children are uniquely named. I believe this is a necessary and sufficient condition for all nodes in the tree to have a unique absolute path.

**Comment by aseth1** [comment]
You are absolutely right and we can add that to `Component::finalizeFromProperties()` easily enough.

**Comment by jenhicks** [comment]
For old models that have components (any type) with duplicate names add _1, _2, etc.

**Comment by tkuchida** [comment]
> For old models that have components (any type) with duplicate names add _1, _2, etc.

I suggest applying this same logic even if the original name is of zero length.

**Comment by aseth1** [comment]
Closed by #1887 where Component names are validated.
