### ISSUE TITLE
Use less prominent color for deactivated muscles

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#1926]
David proposed the following color scheme for muscles:
![proposedmusclecolors](https://user-images.githubusercontent.com/4203505/30457860-10f922c0-9977-11e7-954d-b6a57209a5d0.png)

Here's an example that was generated with an early version of the GUI:

![example](https://user-images.githubusercontent.com/4203505/30457846-068d06e4-9977-11e7-9cef-e781f81d08fb.png)

Any objections @jenhicks @aseth1 @aymanhab @chrisdembia?

**Comment by chrisdembia** [comment]
Interesting. I don't personally feel that there's a problem to solve with the existing colors, but this proposal seems mostly fine to me. Is the light blue still less prominent than the red on a black background? I could imagine that the blue stands out more than the red on black.

**Comment by tkuchida** [comment]
> I don't personally feel that there's a problem to solve with the existing colors

I believe the "problem" is that blue stands out as much as red on a white background in the new GUI. I can ask David to provide a more rigorous argument to support his choice of colors.

> Is the light blue still less prominent than the red on a black background?

I don't know how to quantify prominence, but I think the idea was to make deactivated muscles closer to the color of the bones (and the background when the background is white).

> I could imagine that the blue stands out more than the red on black.

I guess the question is this: On what background color should deactivated muscles be minimally prominent? Do you want me to generate prototypes on a variety of background colors?

**Comment by tkuchida** [comment]
Another option could be to set the color of deactivated muscles based on the visualizer's current background color.

**Comment by aymanhab** [comment]
I tend to agree with @tkuchida and David that the color scheme they used is visually more appealing and communicates what's active which is more important to emphasize than what's not. I also agree that there's not a single color/scheme that works for all background/lighting combinations. The problem at the "core" :green_apple:  is that color is computed by the API rather than switched on the fly by the visualizer (based on lighting, background, user-preference etc.) :sob: . Some practical solutions that may or may not be doable in 4.0:
1. Treat color provided by core as a hint, and provide a variety of color schemes in DisplayHints to override/ignore and let users choose for themselves how to override this hint.
2. Change the values computed by the API to return those suggested above (but these will be hardcoded and will not change with background or lighting) and are inconsistent with earlier versions.

The inherent problem that I see is that computing colors/shades/textures etc. is a fundamental responsibility of the GUI/ visualization. The API should provide the "data" to visualize but not dictate how to visualize (e.g. GUI could decide to use transparency to indicate activation rather than colors). Whatever solution we come up with should follow this paradigm or move us in this direction IMHO.

**Comment by chrisdembia** [comment]
A new color scheme could also be a nice way to set 4.0 apart from 3.3, to make the visualizer feel more new.

**Comment by jenhicks** [comment]
I think the scheme above is nice, although a little bit too pastel for my taste. It could be fine to hard code a new scheme for 4.0 as long as it looks ok on gray, black, and white backgrounds.

**Comment by aseth1** [comment]
> although a little bit too pastel for my taste.

You are not alone.

**Comment by clnsmith** [comment]
I like the gray to red scheme more than blue to red, but either one is OK to me. 

It would be nice to be able to change the normalization value (0-1.0) for visualizing submaximal activities like walking. I sometimes multiply the activations 2x or 3x in order to get nice contrast between active and inactive muscles. See hamstring activity at heel strike in the images below. 

In the 4.0 gui that chris let me demo I can set the color of path geometries, which is great for visualizing the ligaments. It also would be nice to be able to control the display radius of their lines as well so I could make the muscles thick and the ligament line segments thin.

![heelstrike_normal](https://user-images.githubusercontent.com/1234687/31917322-6b4c05c6-b81c-11e7-948a-e0314ab1c8b5.jpg)
![heelstrike_3x](https://user-images.githubusercontent.com/1234687/31917353-a6c55558-b81c-11e7-8da3-8f60da5f8250.jpg)
