### ISSUE TITLE
Wrapping SignalGenerator for use in the MATLAB API

### ISSUE THREAD

**Issue by AdrianLai88** [opensim-org/opensim-core#1985]
I wrapped the SignalGenerator() function so that I could use it in the MATLAB API, however, I'm unable to use all the functions available to me in the source code. For example, I can't add as a component possibly because I can't specific a name. Also, I can't connect the input to the model. I've added some sample code from my main script as the lines I'm having problems with using the MATLAB API. 

Any help would be appreciated. 

Thanks!

Adrian 

```
		// Create a signal generator and set a default Constant value (fast fibre excitation)
		SignalGenerator* sig = new SignalGenerator();
		sig->setName("signal");
		sig->set_function(Constant(0.1));
		// Add signal generator as a component
		osimModel.addComponent(sig);
		// Add the component to the input to the fibre type muscle
		fibretype->connectInput_excitation_fast(sig->getOutput("signal"));
```

**Comment by chrisdembia** [comment]
How did you wrap SignalGenerator?

**Comment by AdrianLai88** [comment]
I'm not sure if I'm doing it properly but in all instances in the Bindings folder, I added the SignalGenerator wherever I located other Functions (e.g. OpenSimHeaders_common.h) and then re-ran Cmake and rebuilt the code.

**Comment by chrisdembia** [comment]
> For example, I can't add as a component possibly because I can't specific a name. 

I'm not sure what you mean by "I can't specify a name." Can you show MATLAB code and point to exactly what's not working?

You can look in the `*.java` files generated by SWIG (in the install folder) and see if you can find a `SignalGenerator.java` file. Also, you can see if SWIG generates any warnings related to SignalGenerator (first comment out the lines in the `*.i` SWIG interface files that cause warnings to be ignored).

**Comment by AdrianLai88** [comment]
```
		SignalGenerator* sig = new SignalGenerator();
		sig->setName("signal");
```

MATLAB equivalent 

```
sig = SignalGenerator();
sig.setName('signal');
```

> You can look in the *.java files generated by SWIG (in the install folder) and see if you can find a SignalGenerator.java file. Also, you can see if SWIG generates any warnings related to SignalGenerator (first comment out the lines in the *.i SWIG interface files that cause warnings to be ignored).

I found the SignalGenerator.java file but I can't find the lines to comment out in the *.i SWIG interface files. Is it in the common.i file where I've included the SignalGenerator function?

**Comment by chrisdembia** [comment]
It looks like you were able to wrap the SignalGenerator class. What is the exact error message you get in MATLAB? Are you sure MATLAB is hooked up to the opensim install containing the wrapped SignalGenerator?

**Comment by AdrianLai88** [comment]
I'm trying to replicate this C++ code 

```
// Create a signal generator and set a default Constant value (fast fibre excitation)
SignalGenerator* sig = new SignalGenerator();
sig->setName("signal");
sig->set_function(Constant(0.1));
// Add signal generator as a component
osimModel.addComponent(sig);
// Add the component to the input to the fibre type muscle
fibretype->connectInput_excitation_fast(sig->getOutput("signal"));
```
MATLAB equivalent that doesn't work 
```
% Create signal generator for the second control input
sig = SignalGenerator();
sig.setName('signal');
sig.set_function(Constant(0.1));
osimModel.addComponent(sig); % can't add a component to the model
 % Add the component to the input to the fibre type muscle
fibretype.connectInput_excitation_fast(sig.getOutput('signal'));
```
Errors in MATLAB
No appropriate method, property, or field setName for class org.opensim.modeling.SignalGenerator.
No method 'addComponent' with matching signature found for class 'org.opensim.modeling.Model'.
No appropriate method, property, or field getOutput for class org.opensim.modeling.SignalGenerator.

> Are you sure MATLAB is hooked up to the opensim install containing the wrapped SignalGenerator?

I can run sig = SignalGenerator() in MATLAB

**Comment by aymanhab** [comment]
This suggests inheritance is wrong on the java side likely because of
unexpected ordering of classes so Swig and have doesn't recognize
SignalGenerator as Component.


On Oct 23, 2017 9:22 PM, "Adrian Lai" <notifications@github.com> wrote:

I'm trying to replicate this C++ code

// Create a signal generator and set a default Constant value (fast
fibre excitation)
SignalGenerator* sig = new SignalGenerator();
sig->setName("signal");
sig->set_function(Constant(0.1));
// Add signal generator as a component
osimModel.addComponent(sig);
// Add the component to the input to the fibre type muscle
fibretype->connectInput_excitation_fast(sig->getOutput("signal"));

MATLAB equivalent that doesn't work

% Create signal generator for the second control input
sig = SignalGenerator();
sig.setName('signal');
sig.set_function(Constant(0.1));
osimModel.addComponent(sig); % can't add a component to the model
 % Add the component to the input to the fibre type muscle
fibretype.connectInput_excitation_fast(sig.getOutput('signal'));

Errors in MATLAB
No appropriate method, property, or field setName for class
org.opensim.modeling.SignalGenerator.
No method 'addComponent' with matching signature found for class
'org.opensim.modeling.Model'.
No appropriate method, property, or field getOutput for class
org.opensim.modeling.SignalGenerator.

Are you sure MATLAB is hooked up to the opensim install containing the
wrapped SignalGenerator?

I can run sig = SignalGenerator() in MATLAB

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opensim-org/opensim-core/issues/1985#issuecomment-338869221>,
or mute the thread

**Comment by chrisdembia** [comment]
Ah yes Ayman is correct. Make sure the line you added to `common.i` is after the line `%include <OpenSim/Common/Component.h>`.

**Comment by AdrianLai88** [comment]
Thanks Ayman and Chris! I can now add the SignalGenerator as a Component and connect the input to my muscle model class.
