### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by romainmartinez** [opensim-org/opensim-core#2137]
Hi,

Would it be possible to update the python package on [pip](https://pypi.python.org/pypi/opensim) with the python 3.6 bindings and opensim 4.0?

Something similar to the [conda](https://anaconda.org/kidzik/opensim) package, but with pip as it is the recommended package manager.

Thank you,

*-- Romain Martinez.*

**Comment by chrisdembia** [comment]
This would be nice to have but would take some time to do. We would welcome contributions!

**Comment by chrisdembia** [comment]
At the Advanced User Workshop in March 2018, Tokio had issues getting the 4.0 python bindings to work on Windows. The issue was resolved by using python binaries from python.org instead of Anaconda Python, probably because AppVeyor uses python.org.

Some steps we can take:

1. Update Python Confluence page to saying that Windows users must use binaries from python.org if they want to use the python bindings that come with the OpenSim GUI.
2. Create an official conda package and encourage users to get the opensim bindings via conda instead of pip.

@romainmartinez, why do you say that pip is the recommended package manager? It seems to me that conda is now very popular.

cc @aymanhab @nickbianco @kidzik

**Comment by romainmartinez** [comment]
Pipenv is the "_officially_" recommended Python packaging tool from [Python.org](https://packaging.python.org/tutorials/managing-dependencies/#managing-dependencies). What could be good with pip is that everyone can use it (even conda users).

**But**, this seems to be the case for distributing pure python code. On the other hand, when it comes to C ++ and Python code, conda seems much more practical.

After a few weeks of testing, I decided to use conda to distribute my packages because it's much easier to manage cmake, swig and cross-platform distribution.

Sorry for the inconvenience, I let you close the issue.

**Comment by chrisdembia** [comment]
Hey @romainmartinez; thanks for that. Because we interact with C++, we need to control which python installation was used to build the bindings. Building the `opensim` python package with Mac's built-in python results in a package that is not compatible with Anaconda's python, for example.

**Comment by chrisdembia** [comment]
We might need help creating or testing the conda package.
