### ISSUE TITLE
Model::formStateStorage() should be writing zeros for muscle activations if original Storage has no activations

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2152]
See original discussion at https://github.com/opensim-org/opensim-gui/issues/279.

When CMC results are animated in the GUI, the muscles change color as a function of their activation. If RRA kinematics are then animated, the muscles are not blue as expected but instead retain the last color they had in the CMC animation. Perhaps `Model::formStateStorage()` isn't writing zeros for activations in the new Storage (and, thus, the GUI isn't receiving zeros to turn the muscles blue)?

**Comment by aseth1** [comment]
`Model::formStateStorage()` uses the default state value for unspecified states. The default for muscle activation is either zero or the minimum activation specified by the muscle (activation dynamics) model. 

One guess is that the GUI is updating/corrupting the model default state during CMC. `Model::formStateStorage()` doesn't build a fresh state  (which requires `initializeState()`) but instead uses the Model's internal `getWorkingState()`. `OpenSimContext::restoreStateFromCachedModel()` is setting a private internal (naked) pointer to the Model's workingState and then changes the Model's internal state under the covers.  I think this is a mistake on the GUI that is incorrectly invoking  `OpenSimContext::restoreStateFromCachedModel()` after running CMC.

**Comment by aseth1** [comment]
It is not an incorrect call to `OpenSimContext::restoreStateFromCachedModel()` that is the culprit but the `MotionDisplayer` itself that is overwriting the underlying working state of the `Model`.  See [GUI issue #279](https://github.com/opensim-org/opensim-gui/issues/279) for details.

**Comment by aseth1** [comment]
@aymanhab please verify and then close this issue. Thanks!

**Comment by aymanhab** [comment]
Thanks for the investigation @aseth1 
The GUI has always used the workingState of the model, since it lives in OpenSimContext, it's managed by the GUI, nobody else can use it anyway. Meanwhile, keeping multiple states alive and synchronized is not a maintainable solution (the name workingState is aligned with this usage).  If you believe the GUI/motionDisplayer should make another call to reset the state that it manages to default values before calling the method above then please advise (e.g. should we call initializeState?)  Thanks

**Comment by aseth1** [comment]
1.  it is wrong for the `MotionDisplayer` to use a `const` method on the  `OpenSimContext` to edit the underlying state. 
2. if the intention is for the `OpenSimContext` to have its own private `State` to allow clients to edit then it should have its own `State` member and not a pointer to the working `State` that belongs to the `Model`. 
3. readable access to the working state which the `const` infers would be fine

I am not a fan of having the `_workingState` data member in the `Model`. Tim insisted on the change because he wanted to edit the default state himself (which may have been a cause of his simulations differing upon multiple runs). I prefer removing it or making it an uneditable `_defaultState`. This is a different issue altogether.
