### ISSUE TITLE
Include a couple example scripts for GUI editing

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2248]
- [x] Adding a body with a joint (generic joint type)
- [x] Adding a muscle (by default creates two path points)

**Comment by carmichaelong** [comment]
@aseth1 can you point me to where the scripts are located?

**Comment by aseth1** [comment]
@carmichaelong you can find all the model editing utilities in [modelBuildingUtilities.py](https://github.com/opensim-org/opensim-gui/blob/master/Gui/opensim/Scripts/modelBuildingUtilities.py).

**Comment by scrum2a** [comment]
For Joints, can pass in the joint type itself.

**Comment by aymanhab** [comment]
Keep in mind that we can not change type of objects (e.g. joints) after creation by property editing, so it may make sense to 
- add a body with no connections/sockets to model
- create the joint of appropriate type that connects to the added body
- add the joint to the model
- only then call initSystem on the new/modified model.
You need to make sure the code used after adding the body doesn't assume component-tree traversal since this will be in limbo state until initSystem is called, I think.

**Comment by aseth1** [comment]
> You need to make sure the code used after adding the body doesn't assume component-tree traversal since this will be in limbo state until initSystem is called, I think.

No, component traversal works immediately after adding the component to the model.

**Comment by aymanhab** [comment]
Since the PR has been merged, this should go to verified I think @chrisdembia

**Comment by chrisdembia** [comment]
Okay I moved this issue to Verified.
