### ISSUE TITLE
Nan in force file causes ID results to be entirely NaN

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2256]
Having any nan's in a force file (.mot) will cause the results of ID to be entirely NaN. Replacing all nans with zeros will allow for ID to compute joint moments. 

In 3.3, ID will only run until the first nan is encountered, then it will stop. In 4.0, ID (seemingly) runs for the entirety of the trial but the resulting joint torques are all nan. 

The offending force file was generated from C3D using C3DFileAdaper(). In theory, there shouldn't be any nans n the C3D, so there are potentially two issues to address here;

(i) Why is the C3DFileAdapter() writing nans to file? Are they real nans or is there something weird going on during reading and conversion.?
(ii) If the nans are real (stored as such in the binary file), then either the C3DFileAdapter needs to write them as zeros or the tools that deal with forces need to handle nans.  

I have attached a zip file to replicate the issue and test the fix. 
[NanExample.zip](https://github.com/opensim-org/opensim-core/files/2281347/NanExample.zip)

**Comment by jimmyDunne** [comment]
On further inspection, the nans are only occurring when the force location is expressed as a COP. When the force is from the origin, there are no nans.  So BTK/OpenSim is introducing the nans.

**Comment by jimmyDunne** [comment]
Seen by a User [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=10148&p=27994). I tested the user's data— a single NaN in each column caused this issue.

**Comment by jenhicks** [comment]
May be an issue due to splining ... not sure where.

**Comment by aseth1** [comment]
There are two issues.
1. `NaN`s in a frame of data should not cause the tool to fail especially if the vast majority of frames does not have `NaN`s. This is likely related to splining. I don't believe this is a new issue.

2. `C3DFileAdapter` can transform raw data to cop and free-moment representation. When this is done in MATLAB we usually threshold vertical force.  If vertical force is too small, we cannot compute COP. In this case `ground_force_2_vy = 1.49493017474042E-16` and `ground_moment_1_mz = `1.49493017474042E-17` which essentially leads to 0/0 = NaN. A quick fix is to threshold to a small number (SimTK::Eps or SimTK::SqrtEps) to avoid generating NaNs, but the answers could still be junk.
--

**Comment by jimmyDunne** [comment]
The immediate fix is to give a warning when this is happening.
 @james will update the documentation for preparing your data and add methods to the osimC3D.m

Future development could use a new class called DataTableUtilities() that would have methods to process tables. 

@chrisdembia @nickbianco are you intending on including something like this on Moco?

**Comment by chrisdembia** [comment]
Yes, we created something called TableProcessor. It's in the master branch of Moco.

**Comment by jimmyDunne** [comment]
The quick fix is to the threshold at a small value (1N) so we don't get a divide by zero. We will test and see if the values are acceptable.

**Comment by aseth1** [comment]
@jimmyDunne can you post or send me the C3D file that produced NaNs? Thanks!

**Comment by jimmyDunne** [comment]
Attached is a zip of c3d that, when converted to .mot using C3DFileAdapter().readFile(name,1), gives a nan on one frame of COP. Let me know if this isn't a great example and I can find another one. 

[example_nan.c3d.zip](https://github.com/opensim-org/opensim-core/files/3303773/example_nan.c3d.zip)

**Comment by aseth1** [comment]
@jimmyDunne what are CoP coordinate values set to when the vertical force is below threshold? AFAICT the attached file only produces a NaN when the vertical GRF crosses zero and that is only because the force is biased to some -15N when there is no load.  

Adding an eps doesn't fix the problem if we can get vertical forces below zero. Instead it just shifts the problem. The correct solution, IMHO, is NaNs for the COP coordinate values when the vertical force is 0 (or below threshold).  It basically means the foot is not in contact with the ground and the CoP is undefined.

When applying forces to a model, we should first check that the force is above threshold, and if so, then apply it at the CoP. Otherwise we are relying on zero forces to cancel out the fact that we have bogus CoP locations.

**Comment by jimmyDunne** [comment]
In discussion, we feel that this is a pre-processing step that needs to be decided by the user. The fix is to have thorough documentation in the 'Preparing your Data' section that describes the problem and points users to solutions. 

@aseth1, can you add more comments and I can draft.

**Comment by aseth1** [comment]
One proposal is this:

1. Always read experiment force data as forces and moments as measured by the plate (e.g. about its origin). No NaNs because there is no COP calculation.
2. Write a COPProcessor that takes force-plate table (1.) and converts moments to CoP and free moment. This can produce NaNs. To avoid NaNs the processor takes 2 additional arguments: i) vertical force threshold (below which forces are zeroed) and ii) the COP value when force is below threshold.
3. We can encourage to feed their force data (from 1.) directly into Tools and use 2. only to visualize in the GUI. This could be done semi-automatically (with an option) when loading experimental forces in the GUI.

This avoids corrupting force data to avoid NaNs but leads to incorrect application of external forces/momemnts during simulations.

**Comment by aymanhab** [comment]
@jimmyDunne Can you comment on where this stands? and if it should stay under the sprint board, thanks

**Comment by jimmyDunne** [comment]
I have written some info [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Motion+%28.mot%29+Files), @jenhicks does this look okay? Should I also put a note in the ID documentation?

**Comment by aseth1** [comment]
@jimmyDunne thanks for documenting this. There are few things  to clarify:

1. If you have NaNs it is precisely because the force has gone to zero. When the foot is off the floor the COP is truly NaN. You can get away with putting in a number/value because the force is zero. However, the user has to be careful, because if you use some arbitrary number and the COP value is far from that value, the spline may introduce transients that make the transition from whatever number to the actual COP value be inaccurate. One trick is to linearly interpolate across the NaN region.
2. We should prominently note that users do not have to edit their .mot file and manually remove NaNs. They can use the `C3DReader` with the flag to represent forces and moments at the `origin` of the plate. There is no reason to convert their data to COP and free moment except for visualization. So we can tell them to do both. Visualize data with `COP` in GUI but use `origin` for simulations (no NaNs)
3. There is no practical way for users to include their own splining routine for GRFs and COP. The only requirement is that they provide GRFs without NaNs (with two ways of doing that above).

**Comment by jenhicks** [comment]
@jimmyDunne will document and  create an open issue around visualization of reaction forces with NaNs.

**Comment by jimmyDunne** [comment]
Documented [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/C3D+%28.c3d%29+Files) and [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Motion+%28.mot%29+Files#Motion(.mot)Files-Nansinyourforcefile)

**Comment by jenhicks** [comment]
I made some tweaks. I think this is OK to close.

**Comment by marnunez** [comment]
Sorry for reviving this issue, but I'm currently facing this COP + free moment conundrum.

Newer BTS gaitlabs have the ability to merge the resultant vectors of two or more adjacent force platforms as if they were one, and the output is expressed on global coordinates, COP, forces and torque. If I'm not mistaken, there's no easy way to export this into a c3D apart from faking a custom size type-1 force platform and mapping the analogs. Creating a .mot file seems far simpler.

So acording to what @aseth1 writes, I'd be safe if I:

1. Replace every NaN in forces and torques with zeros
2. Replace the NaN chunks (when the foot is in the air) with a 2D linear interpolation.

Is this still the case? Thanks for your advice
