### ISSUE TITLE
Update XML model version to 40000

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#2260]

**Comment by aseth1** [comment]
Specifically, model versions that arose during the development of 4.0  (e.g. 305xx) should not be distributed. In cases where intermediate versions are part of test cases, the test should be performed with the  4.0 and 3.3 model files since these are the formats that users will be exposed to. I think @aymanhab had proposed making a 40000 version a while back, and I would be in favor of doing that before the official 4.0 to make sure there are no more changes. The latest version (30516) has held nearly 15months now, so it is unlikely to change.

**Comment by aymanhab** [comment]
Option 3 or a variation of it seems best to me. One key question, when we do name search for components do we have expected type(s) or base class to search for? If so then we can bake this in the search without even implementing 3 by making the search filtered, and not introducing artificial components that stick forever in all legacy/pre4.0 models

**Comment by aseth1** [comment]
Type uniqueness cannot be guaranteed. If you have a `Socket<Frame>` and you have a `Body` and `OffsetFrame` of the same name, their is a collision. I believe @tkuchida ran into this type of issue so I don't think it is an abstract problem. Especially now that we can have components located anywhere (not required to put them all in Model's sets). It is even more critical that paths be unique. 

I guess I am arguing since we have Sets in Models,  that these Sets really act like sub-directories in a filesystem structure, which our `ComponentPath` emulates. In which case, including the sub-directory name in the path makes sense and then guarantees existing models with components in different sets are  treated as unique and the renaming problem can be avoided in these instances.

**Comment by chrisdembia** [comment]
What's option 3?

**Comment by tkuchida** [comment]
> What's option 3?

See the 6th comment on https://github.com/opensim-org/opensim-gui/issues/483 (from Ajay).

**Comment by jenhicks** [comment]
Need to review (@aseth1 ) and merge
