### ISSUE TITLE
Default to absolute pathnames when you serialize

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2292]

**Comment by aymanhab** [comment]
@chrisdembia are you working on this or you want me take over?

**Comment by chrisdembia** [comment]
I am not working on this. Thank you for checking.

**Comment by aseth1** [comment]
I forgot why this was on the critical path for 4.0. While I don't think this will break existing models, I do think it makes it more difficult to preserve subassemblies (branch of subcomponents) and to make copies since they are no longer self contained. They will now all refer to components outside the assembly. 

For example  suppose I create a device that controls a joint and you add it to a Joint. The device contains may contain several subcomponents but all it needs to know is the parent joint. So its `Socket_parent = ".."` . If you now copy the device and add it to every joint, you don't need to updated the socket connectee_name. If we make this update, we will then be forced to update each connectee_name one by one and find the absolute path to each joint. Worse, is that inside the assembly it may be wired up by relative paths and these are now going to also be made absolute and will have to be edited if the Device is added elsewhere.

So why is this change needed? I apologize that I cannot remember the rationale.

**Comment by jenhicks** [comment]
If I recall the discussion correctly, we thought that the confusion created by using relative paths (particularly to users who are new to the concept of paths for components) would be greater than the pain created by the case you mentioned above.

I think we discussed still supporting relative paths, so that in the case mentioned above you could define the subassembly using relative paths. The absolute pathnames would just show up when you serialized (presumably after everything was all hooked up).

Once subassemblies become more common and users have a better sense of paths, I think we could change the serialization to relative paths (in a future version).

**Comment by aseth1** [comment]
Thanks Jen, that's helpful. The problem in the solution is that we are storing the absolute pathname (instead of relative) when the socket is Connected. So even it was specified relatively it immediately gets replaced with absolute pathname. So if you create a leg and wire it up, when you copy it and attempt to connect  the copy, its subcomponents will contain absolute paths which try to connect to the existing leg by virtue of the absolute pathnames.

I do think long relative pathnames can be confusing, especially when they traverse through root. Perhaps we could detect those cases and replace them with absolute pathname.

**Comment by chrisdembia** [comment]
I agree with @jenhicks's recollection.

**Comment by aymanhab** [comment]
Trying to implement the change I ran into problems and test case failures (in cases where the models are built programmatically) where the absolute path was incorrect leading to connection failure. Upon discussion with @aseth1 this sounded like something he ran into earlier and made it necessary to do relative paths. @aseth1 will investigate if there's a way to use absolute path only in cases where the path goes up to root then down.

**Comment by chrisdembia** [comment]
> Trying to implement the change I ran into problems and test case failures (in cases where the models are built programmatically) where the absolute path was incorrect leading to connection failure. Upon discussion with @aseth1 this sounded like something he ran into earlier and made it necessary to do relative paths.

This was already a problem and is no more of a problem when using absolute paths. The codebase already has a kludge to make this work in the relative path case.

**Comment by chrisdembia** [comment]
In #2303 @aseth1 said:

> Given the that the reason to use absolute pathnames is to avoid confusion for users inspecting dependencies/Sockets in XML, I don't think that warrants using absolute pathnames everywhere.

> We can make a relatively simple decision to use absolute pathnames when the absolute pathname has fewer elements that the relative pathname. For example, a Force that is dependent on a Body, will typically have a relative path like:  *../../bodyset/##bodyname##* and it is clearly more direct to have the absolute pathname in this case: */bodyset/##bodyname##*, which has 2 path elements vs the 4 of the relative pathname. But this in not going to be true for a Device and its parts. If the Device has a force (say a spring) that connects two OffsetFrames (which are internal to the Device) the its Sockets will have relative connectee pathnames like:  *../anchor_1* and *../anchor_2* which tell you that the anchor's are part of the Device. As absolute pathnames they look like: */jointset/knee_r/device/anchor_1/* and  */jointset/knee_r/device/anchor_2/*. This doesn't seem horrible, but imagine if the device was composed of a dozen components instead of just three. 

> Furthermore, if you clone the device and add it to say the left knee you now have to edit every socket in the device since all the paths are absolute and will no longer be valid. That it going to be a headache for model building. The relative paths within the device are would remain valid no matter where the device is ultimately connected, so you can clone and add the device to get unique instances without having to rename the connections.

> I propose using the absolute pathname ONLY when the relative pathname has more path elements. I think this a good compromise between having readable path names without *../../..* everywhere while keeping assemblies self-contained.

> @opensim-org/dev-team  please let me  know your thoughts.

**Comment by aymanhab** [comment]
Having tried absolute path in my environment in PR #2302 I would say it was orders of magnitude easier to parse/understand the XML. We can make the internals whatever we want but I'd lean to have absolute paths in XML.

**Comment by tkuchida** [comment]
FWIW I agree with @aymanhab: currently, the information necessary to trace through the ownership tree is distributed throughout the (long) XML file, so interpreting relative paths can be challenging.

**Comment by scrum2a** [comment]
Look into delaying changing the connectee name property.

**Comment by jenhicks** [comment]
Requires delaying connectee name: PR #2310

**Comment by chrisdembia** [comment]
What did we decide to do here?

**Comment by aseth1** [comment]
Using references to establish connections without setting their pathname until finalizeConnections, should allow us to build models programmatically without  the issues @aymanhab ran into #2302. If that is the case we could use absolute pathnames. Otherwise, we my have to resort to a compromise and add some logic to minimize the depth of relative pathnames.

**Comment by scrum2a** [comment]
The way to test this is by taking a model roundtrip in the GUI: load, save to the latest format, load again.

**Comment by scrum2a** [comment]
Perhaps use opensim-models' CI to test roundtrips.

**Comment by carmichaelong** [comment]
Tested on W10 Pro with OpenSim 4.0-2018-11-06-f8548147.

1. Opened 2392
2. Saved model to file
3. Searched for all ".." in the file and found they only appeared in tags related to FrameGeometry or Mesh.
4. Opened new file in GUI and saw no issues.

There was a mention about using CI to test, but I did not do this. I will leave this in Needs Verifying now.

**Comment by chrisdembia** [comment]
Thanks @carmichaelong. @jimmyDunne is working on using CI.
