### ISSUE TITLE
Update documentation, etc. to cite recent OpenSim 4.0 paper

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2303]

**Comment by aseth1** [comment]
I would also include Sherm's moment-arm paper. There seems to be confusion about how OpenSim computes moment-arms. It seems most assume we use perturb the model to compute dl/dtheta, which is not the case and Sherm's paper describes effective torque method that we actually use.

**Comment by scrum2a** [comment]
Update About dialog in the GUI.

**Comment by aymanhab** [comment]
We have limited room in the about Dialog, I'll try to show both OpenSim papers, the moment arm paper can be shown  in other places if needed. What is the text you suggest for the 4.0 paper? @jenhicks 
Also do you prefer we keep DARPA on the Acknowledgement list since we were supported in part by them in the past?

**Comment by jenhicks** [comment]
I think you could just list the 4.0 paper. I would leave DARPA for now, since they supported some of the 4.0 development.

**Comment by jenhicks** [comment]
I'll ask Scott what he would like to do.

**Comment by aseth1** [comment]
I don't think we need to remove the 2007 paper.  We can make the citations shorter perhaps and also make the the other wording in the About more succinct.

**Comment by aymanhab** [comment]
Agreed @aseth1 Please feel free to provide the shorter citation(s) and we'll see how it looks in a build. Thank you

**Comment by aseth1** [comment]
@aymanhab  point me to where the text is and I can make the changes.

**Comment by aseth1** [comment]
I'll update `AboutJPanel`

**Comment by aseth1** [comment]
Looks like:

![image](https://user-images.githubusercontent.com/6494122/47945353-8fa66780-debe-11e8-9793-224a4c859d48.png)

**Comment by jenhicks** [comment]
Scott responded that he thinks we should replace with the 4.0 paper in the GUI and list multiple on simtk.

I tend to agree with this -- perhaps we could discuss the rationale at the stand-up today.

**Comment by chrisdembia** [comment]
I updated https://simtk-confluence.stanford.edu:8443/display/OpenSim/License+for+OpenSim+4.0+and+Later:

- Replace old GUI license with Apache 2.0
- Remove statements that using the GUI requires citing any paper.
- Added citation for 4.0 paper.
- Renamed the page title to say "4.0" instead of "3.0" (because the GUI license has changed).

**Comment by jenhicks** [comment]
We need to update the link in About @aymanhab

**Comment by chrisdembia** [comment]
Oh oops! I can change the name of the page back, too.

**Comment by aymanhab** [comment]
@jenhicks We now have
https://doi.org/10.1371/journal.pcbi.100622 for the 4.0 paper and
https://simtk-confluence.stanford.edu:8443/display/OpenSim/License+for+OpenSim+3.0+and+Later

Both links are broken or lead nowhere, what changes you'd like made?

**Comment by jenhicks** [comment]
Chris updated the page to the following:
https://simtk-confluence.stanford.edu:8443/display/OpenSim/License+for+OpenSim+4.0+and+Later

https://doi.org/10.1371/journal.pcbi.1006223
(looks like the 3 at the end got cut-off somehow)
