### ISSUE TITLE
OpenSim::TimeSeriesTable_<SimTK::Rotation> is not SWIG wrapped

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2465]
Access to to resulting `TimeSeriesTable` of Rotations (e.g. using `OpenSenseUtilies`) is opaque in MATLAB.

**Comment by aymanhab** [comment]
While exposing TimeSeriesTable <Rotation> is straightforward, the base class DataTable_<double, Rotation> is harder to wrap because all previous examples were templatized with subclasses of SimTK::Vec. Do you know if that was a limitation on the design of the DataTable_ template, @aseth1 ? 
We get away with it in C++ because methods like averageRow and clone are never generated or invoked but SWIG generates these regardless.

**Comment by aseth1** [comment]
> Do you know if that was a limitation on the design of the DataTable_ template, @aseth1 ?

We use `TimeSeriesTable_<SimTK::Rotation>` everywhere in OpenSense, so I don't think there is any particular issue here, other than creating the specialized `TimeSeriesTableRotation` in [common.i](https://github.com/opensim-org/opensim-core/blob/0af1649e48b88e0a561a73976b8dea4ce56e4809/Bindings/common.i#L123-L134) as was done for the other `TimeSeriesTable_` types.

**Comment by aymanhab** [comment]
Working on this now since otherwise some methods are not available to scripting users

**Comment by aseth1** [comment]
I took the liberty to add these in to common.i  and added the specialization for `DataTable::makeElement_helper` to handle a SimTK::Mat<M,N>. Want me to pus that for you to continue and test @aymanhab?

**Comment by aseth1** [comment]
@aymanhab it is looking like this will be important for scripting users who want to use `TimeSeriesTableRotation` to access individual rotations for comparison (Hannah) as well as to setup the `InverseKinematicsSolver` with an `OrientationsReference` initialized from the table of rotations (current limitation for Patrick).

**Comment by aymanhab** [comment]
I believe this has been fixed by PR #2467 Please let me know otherwise

**Comment by jimmyDunne** [comment]
Waiting to be added to release notes
