### ISSUE TITLE
Remove 'Press any Key...' requirement for OpenSense -Calibrate

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2469]
When running OpenSense -Calibrate, the terminal window asks
`Press any key and return to close visualizer.`

Perhaps this is just on Mac, but I have to first type a key and then press enter for this to register-- hitting only enter/return doesn't work and hitting any other key doesn't do anything, it only works if (in order) you press (i) an alphanumeric key, and then (ii) press enter/return. This caused some pain since the user will press a key and expects a model to be printed, but can't find one and is also stuck in the terminal until you press the correct order of keys.

Since you can't choose to print the model to file or not, there should be no pause asking the user to press any key-- the model should just be printed to file.

**Comment by aseth1** [comment]
The `cin` is currently preventing the visualizer from closing. If we remove it, the visualizer window only flashes open, since it only renders a single frame. So some sort of user input is needed to signal they are done looking at the model in the visualizer. I will add the key press to the visualizer window instead of the terminal.
