### ISSUE TITLE
Consistent interface between Calibration and IK for imu heading

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2474]
For the IMU heading; OpenSimUtilities.calibrateModel...() takes a `const SimTK::CoordinateAxis& baseHeadingAxis = SimTK::ZAxis`. To be consistent with InverseKinematicsStudy, it would have to take a `const std::string& baseHeadingAxis = "" `.

It would be preferable that the OpenSimUtiliies() takes a string ('x','y', or 'z') and the type creation is done internally, that way scripting users don't have to use CoordinateAxis().

**Comment by aseth1** [comment]
I would prefer that the API remain more strict and use `CoordinateAxis`. To make Calibration easier for scripting users (and command line), I suggest we have a settings (.xml) file to handle the growing myriad of options. Since we cannot serialize `CoordinateAxis` as a property, we will have the axis type specified as a string. Scripting users can the populate the settings programmatically (using a string) and the deserialization will test that it forms a valid `CoordinateAxis`.
