### ISSUE TITLE
Using read() or readFile()

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2499]
Differentiate the use of read() and readFile() across the FileAdapaters(). 

We should be able to answer the question "Why do we have multiple methods that do similiar things?"

**Comment by tkuchida** [comment]
IMHO, it seems like there should be only one method. If C3DFileAdapter wants to implement its own read method, it should either override the method from the parent with its own implementation or override the method from the parent to just throw an exception that points to its own method. A potential danger in the current interface is that a user might be using one of the read methods and not know about the other one where you can specify how the forces are expressed.

**Comment by jenhicks** [comment]
Proposal: Make convenience constructors (readFile() ) protected, and instead have users create an instance of reader, set parameters, and then use generic read function.

reader = C3DFileAdapter()
reader.setCOPlocation(...)
tableMap = reader.read()
forces = reader.getTable(tableMap, "Forces")

Changes to interface should not have a huge effect on users as long as we update matlab utility scripts. @tkuchida  how does this sound to you? How big of an effect would this on your existing code?

**Comment by tkuchida** [comment]
LGTM, just so long as there's only one read-related method in the public interface. :book:

**Comment by aymanhab** [comment]
Thanks for the feedback @tkuchida Some investigation shows the following items that should be good to discuss at some point:

1.  The factory feature of FileAdapter::readFile is used in STOFileAdapter_<>::readFile so that the return type of the table is dictated and so that the concrete type of Adapter is hidden. 
2. Same issue for TimeSeriesTable constructor from file, and for Storage constructor from file.
3. In case one Table is returned, the generic interface returns a map from name to a table, we'll need to make-up a name that we didn't have to introduce in the past.

I'll proceed with the assumption that this is the intended behavior per earlier discussion and we can discuss in person or along the review. I will not remove readFile function itself for now, just its usage, in case we want to return it to life under a different name or scope.

**Comment by chrisdembia** [comment]
As I mentioned in the dev meeting, these two functions actually have two different uses. `read()` is for use by users, and `readFile()` is for use by tools. Users should not really ever need `readFile()` unless they do not want to assume the type of file they are reading.

I think the issue is mostly just one of naming. `readFile()` should be renamed to something like `readGeneric()` or `readAnyFile()` or `readFactory()`.

**Comment by aymanhab** [comment]
Had a good discussion with @chrisdembia about the various use cases and will continue to update the code in the PR to eliminate calls to readFile altogether and will see how it looks. @chrisdembia pointed out that we can utilize the table constructor from file directly without creating a reader explicitly to avoid downcasting.

**Comment by aymanhab** [comment]
PR #2535 is ready for review. Only C++ codebase was updated, Java and python bindings and test cases will be updated once changes to the interface are agreed upon. As of now:
- All readFile methods have been removed (commented out).
- For Adapters returning one table of specific type, the explicit reference to Adapter was removed and the constructor of TimeSeriesTable from file is used instead which internally uses factory but without exposing users to this unnecessary complexity.
- The only Adapter that was benefiting from the old scheme is the C3DFileAdapter (it had concrete return type for tables) which is now done by ugly downcast as in testC3DFieAdapter.cpp

Please let me know what you think @aseth1 @chrisdembia @tkuchida @jimmyDunne

**Comment by jenhicks** [comment]
@aseth1 @chrisdembia @tkuchida Can we get a volunteer to review within the next week?

@jimmyDunne Will test on Matlab side now that the bindings have also been updated.

**Comment by jenhicks** [comment]
@carmichaelong Are you available to review? Thanks!

**Comment by carmichaelong** [comment]
Yes I can review the PR.

**Comment by jimmyDunne** [comment]
Below are the three most common uses of the updated interface from this PR in Matlab. Everything looks good and (local) testing of writing with the Adapters is great. 
```
import org.opensim.modeling.*

%% Read a storage file into a TimeSeriesTable
sto_filename = 'Running_GRF_cop_nans.mot';
stoTable = TimeSeriesTable(sto_filename);

%% Read a TRC file into a TimeSeriesTableVec3
trc_filename = 'arm26_elbow_flex.trc';
trcTable = TimeSeriesTableVec3(trc_filename);

%% Read C3D data into a table
c3d_filename = 'walking5.c3d';
% Instantia
c3dReader = C3DFileAdapter();
% Set the expression of the forces to Center or Pressure
c3dReader().setLocationForForceExpression(1)
% Get a map of tables.
tables = c3dReader.read(c3d_filename);
% Get the marker table.
markerTable = c3dReader.getMarkersTimeSeries(tables);
% Get the force table. 
forcesTable = c3dReader.getForcesTimeSeries(tables);
```

**Comment by aymanhab** [comment]
Any reason this is not closed yet? @jenhicks @jimmyDunne

**Comment by jimmyDunne** [comment]
No reason. All the instances of readFile have been addressed in Python and Matlab code.
