### ISSUE TITLE
IKTool gives different results from run to run when <accuracy> value is low

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2502]
### Steps to reproduce
(See attached Zip)
- Run **test_script.m**. The script runs the same IK, numerous times, and plots the knee_angle_r coordinate results.
- There are two setup files, one where the accuracy is low (0.001) and one where the accuracy is high (0.0000000001). 

### Expected result
When plotted, the results should be exactly the same. The below figure is a plot of five knee_angle_r simulations using the accuracy high condition. The results are identical. 

![image](https://user-images.githubusercontent.com/5296507/59794902-ff2f6280-92a7-11e9-9f6b-bef2214971d5.png)

### Actual result
For the accuracy low condition, the results are different for each simulation. 
![image](https://user-images.githubusercontent.com/5296507/59795030-4cabcf80-92a8-11e9-9ef0-3168aff3520a.png)

### Environment and GUI version
Mac.
Tested on the OpenSim 4.0 release and on the current OpenSim master branch. 
[ik_bug_1.zip](https://github.com/opensim-org/opensim-core/files/3307668/ik_bug_1.zip)

**Comment by aseth1** [comment]
This is likely the case in 3.3 as well. Nothing was fundamentally changed between 3.3 and 4.0 w.r.t. IK.
Seeing the solution diverge, it maybe possible that round-off error is contributing to a slightly different initial condition for the next time step.  @sherm1 can comment before we invest too much time into investigating. I agree that even at low accuracy (0.0001) we wouldn't expect angle differences of ~3degs (~0.05 rad). Perhaps accuracy is not the number of digits we can trust in the solution (e.g. joint angel) but of the norm of the solution (so one angle could be 2-3degs off with still have a norm below accuracy)?

**Comment by sherm1** [comment]
If I understand the post, @jimmyDunne is reporting that repeated runs on the *same* machine, with *identical* initial conditions, are producing different answers. That means roundoff can't be the explanation because it is deterministic and would be identical from run to run.

I only know of a few ways for this kind of behavior to occur:
- intentional randomization (that is, there is literally a call to `rand()` or similar somewhere in the code path, with a randomized seed), or
- an uninitialized variable containing random garbage that affects the outcome (a bug), or
- the initial conditions aren't exactly the same for some other reason (like some "warmstart" code getting triggered for the subsequent runs).

I don't know of any intentional randomness in Simbody except in unit tests. Could be randomness somewhere in OpenSim or IPOPT? (IPOPT is used to solve an internal optimization problem in IK.)

Valgrind might be helpful for hunting down uninitialized variables.

The "different initial conditions" hypothesis could be tested by very carefully making the runs independent, e.g. doing each run only after a reboot.

**Comment by aseth1** [comment]
I just ran IK four times using the same setup file and Inverse Kinematics Tool in the GUI but saved to four different locations at low accuracy.

![image](https://user-images.githubusercontent.com/6494122/59948791-198f4a80-9426-11e9-8170-7567cdde2c25.png)

@jimmyDunne in your test were you looping/running IK in MATLAB?

**Comment by jimmyDunne** [comment]
Yep. Ill repeat the test some other way and see what I get. Thanks for running.

**Comment by aseth1** [comment]
In MATLAB:
![image](https://user-images.githubusercontent.com/6494122/59949598-6f64f200-9428-11e9-9c42-3c712880c33f.png)

Caveats are: this is on WinX64 not MacOSX, and I kept getting this error:

```
Error: Functions cannot be indexed using {} or . indexing.

Error in test_script (line 8)
    mot_low.(['trial_' num2str(i)]) =
    osimTableToStruct(STOFileAdapter().read('IKResults/ik_output_run.mot')); % 4.0
    application version
```
requiring me to evaluate each line one by one and then the for loop and that worked. Not sure what that is about.

**Comment by jimmyDunne** [comment]
You have to change read() to readFile since that has changed since the application release. The code is there, you just need to change what is commented out.

**Comment by aseth1** [comment]
That's not it. If I copy and paste your script in the command window it runs fine (that's how I plotted results above). If run the script it gives me that error. Very weird. I wouldn't worry about it.
