### ISSUE TITLE
Can't open model/trc files with non ASCII names

### ISSUE THREAD

**Issue by marnunez** [opensim-org/opensim-core#2506]
### Sample
```python
import opensim

ma = opensim.Model("Nono.osim")
Loaded model 3DGaitModel2392 from file Nono.osim

m = opensim.Model("Ñoño.osim")

RuntimeError: std::exception in 'OpenSim::Model::Model(std::string const &)': Object: Cannot open file Ñoño.osim. It may not exist or you do not have permission to read it.
        Thrown at Object.cpp:105 in Object().
```
### Environment
Current master build, Python 3.7.3, Windows 7 x64, swig 3.0.12

**Comment by marnunez** [comment]
Is this more likely to be a wrapper issue or a core issue?

**Comment by jimmyDunne** [comment]
Hi, Marcos-

Thanks for opening this issue, it is much appreciated. This problem is most likely in how the C++ libraries deal with different character types (core). Taking a cursory look into how to accommodate non-ASCII character types, we feel that the solution is non-trivial and, unfortunately, we don't have the bandwidth right now to address it. We will keep the issue open, and we have added it to our development backlog. 

Let us know if you have any questions or if you see any information that would be useful for us on this issue. 

Thanks!
-J

**Comment by marnunez** [comment]
Thanks for the response @jimmyDunne, I'm not fluent on C++, I was just checking whether this was a superficial problem or a deep rooted one. Strangely enough, OpenSIM 3.3 didn't use to have this issue. I'll try and work around this for the time being.

**Comment by Syvaa** [comment]
While working with Opensim API in Matlab, I encountered the same problem. Is there any way to solve this yet?

**Comment by tkuchida** [comment]
@Syvaa A workaround is to use only ASCII characters. You can monitor this Issue… when it is addressed, it will be linked to the PR that addresses it.

**Comment by Sina-Tabeiy** [comment]
Hi everyone,

I also get @marnunez's error while I was trying to run OpenSim Matlab codes in Matlab. What can I do to overcome? 

Regards,
Sina

**Comment by marnunez** [comment]
Hi! For the time being, you can programmatically rename everything in the
path (filename and/or directories) to have ASCII characters. Or better yet,
move/copy the file to a temporary file in a temporary folder (in Python
there's a package for that, MATLAB might have one as well), work with it,
then when finished bring it back. It's annoying, buy does the trick.

Another thing you could try (i haven't tested it yet though) is to create a
hardlink to the model in a temporary file instead of moving it. That might
be more efficient.

**Comment by jenhicks** [comment]
Closing given age, but please feel free to re-open if it is high priority.
