### ISSUE TITLE
Move CI builds to GitHub Actions

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#2622]

**Comment by chrisdembia** [comment]
We should revisit this, now that the GUI is using GitHub Actions.

https://github.com/opensim-org/opensim-core/blob/master/.github/workflows/continuous_integration.yml

The script needs to be updated to be triggered on push/pull requests, to deploy binaries, to cache the builds of dependencies, to use ezc3d instead of BTK, and to perhaps use VS2019 instead of VS2017.

We should be able to work off of the GUI's latest GitHub Actions script.
