### ISSUE TITLE
Thelen2003Muscle equilibrium solve failure

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#2686]
@chrisdembia reported during a developer meeting that Scott Uhlrich encountered this failure only for specific  model and state values affecting a single muscle. The failure can be reproduced but it is not clear why the algorithm fails to find an equilibrium since it does not appear to be a singularity in fiber or tendon force production. The  Newton solve fails to find appropriate step size and fails due to exceeding the iteration limit. A test case is being added.

**Comment by jenhicks** [comment]
@aseth1 @mjhmilla OK to close?

**Comment by mjhmilla** [comment]
Actually I think this one should remain open. Here's why:

Problem: Several muscle models have the possibility of failing to initialize correctly.

Solution Steps:
1. [Done] Build a general purpose initialization test that can catch all of the various ways a model can fail to initialize. This has been done and the code is currently sitting in the branch feature_equilibrium.
2. [Open] Fix the initialization methods for the models that have initialization problems. 

I have a straight forward fix (remove all Newton methods and replace with bisection + initialize the model so that the tendon is static). I simply haven't gotten to this yet. If there is a date when you'd like to see part 2 completed please let me know.

**Comment by jenhicks** [comment]
Closing as the (important) remaining issues are covered elsewhere.
