### ISSUE TITLE
Model Calibration before IK fails for some configurations

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#2781]
Reported by @malborno

**Comment by aseth1** [comment]
Would be nice to document what the configuration dependent failure is. Can you describe the issue?

**Comment by aymanhab** [comment]
@aseth1 In the example provided by @malborno that fails calibration, the subject is facing a random direction.  The IMU-z axis is aligned with subject Pelvis-x (users can populate this info based on IMU placement) but heading correction was trying to align IMU-z with Ground-x (which is hard to define for users in random configurations since pelvis rotation between ground and pelvis is arbitrary). The result was wrong heading_correction. 

I'll beef up the test case, to include this scenario/data-files so you can see what changed and why or try it for yourself. Please let me know your thoughts.

**Comment by aymanhab** [comment]
More details regarding the workflow used above by @malborno :

- Marker data was used to scale and pose the model
- Resulting pose had non-zero pelvis rotation
- Pose resulting from previous step is set as a default-pose which is used to place/register the IMUs to the model. 
- Because of non-zero pelvis rotation, ground-x and pelvis-x are not aligned. 
- The previous mechanism could have worked by guessing which IMU-axis is aligned with Ground-x and redoing calibration but that's error prone.

@jenhicks @carmichaelong Please let me know if I missed any details that could help clarify the confusion based on our dev meeting discussion. Thank you.

**Comment by jenhicks** [comment]
Thanks @aymanhab for the additional details. @aseth1 please let us know your thoughts or if you have additional questions.

RE you comment on the PR, my understanding is that if you specify a pelvis rotation of zero in the default pose and the subject begins walking forward from the calibration pose, you will still get meaningful pelvis rotation, etc. values. @aymanhab have you run some tests to verify that this is indeed the case?

**Comment by aymanhab** [comment]
@jenhicks That's exactly what's tested in the testOpenSense test case, running IK on a calibrated model with 0 pelvis rotation, results downstream will see no change. I'm beefing up the test case to include calibration with non-zero pelvis rotation.

**Comment by aseth1** [comment]
@aymanhab Thanks for the more detailed description. I see now, and the fix makes sense in this case, I think.  A quicker solution, however, would have been to set the pelvis rotation to zero in calibration pose. It is not very realistic to know the pelvis rotation at calibration time, and this was only known by "cheating" and using the marker-based solution. As noted, the user will have to zero the pelvis-rotation anyway after registration if they want to compare kinematics between subjects. My original implementation also did not alter the IMU z (tilt) and x (list) rotations and in the registration of the IMUs only the pelvis was not pose dependent (i.e. a Pelvis offset is not computed), and the pelvis was in fact rotated to match the base IMU (after heading correction, and that is why it was necessary).  Now, you will get a good fit if you have a good initial pose, but without markers we have no idea how the pelvis should be oriented. Can you double check that the pelvis is still oriented to match the IMU orientation in tilt and list? My worry is that the pelvis IMU is registered directly to the pelvis given the correct orientation from marker-data, but in practice it will not be known. In this case simply setting the calibration pose to have zero-rotation will not be correct, because we still want the pelvis to be tilted and listed to match the IMU and I am not sure that is happening anymore.

**Comment by aymanhab** [comment]
Thanks for the feedback @aseth1 
I beefed up the test case to include a model with non-zero pelvis rotation. Results with the fix (green-pelvis) and with manually zeroing out pelvis rotation (orange-pelvis) are shown below
![opensim_snapshot_bothways](https://user-images.githubusercontent.com/3972208/85619289-ec681000-b616-11ea-9489-bc83e5c02b83.png)
The placement looks reasonable, but the pose looks off (not sure why) when zeroing pelvis rotation.
I'll ask @malborno to try zeroing pelvis rotation and see if it works in a couple problematic scenarios. Ideally users don't need special treatment for pelvis_rotation (if using this model) , so it seems the fix would still have an upside but will see how both approaches perform on a couple trials. 

I don't believe this fix changes anything about the pelvis tilt/list from the previous behavior, since we have always assumed heading correction to be a rotation around world's Y-axis anyway but please let me know if I'm missing anything here. Thank you.

**Comment by carmichaelong** [comment]
> I don't believe this fix changes anything about the pelvis tilt/list from the previous behavior, since we have always assumed heading correction to be a rotation around world's Y-axis anyway

I think this is the case due to [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/OpenSense/OpenSenseUtilities.cpp#L249) and [this line](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/OpenSense/IMUPlacer.cpp#L136) which haven't been changed in the PR.

> A quicker solution, however, would have been to set the pelvis rotation to zero in calibration pose.

I thought that this should be the case too, but it @aymanhab's test with data above seems to indicate otherwise. @aymanhab, how different were the `pelvis_tilt` and `pelvis_list` values between the two cases above?

Given the discussion of use-cases above, it may also be good to update the angle heading correction to compute the angle in the x-z plane (i.e., project the vectors from which the angle is computed into the x-z plane before using `acos`).

**Comment by aymanhab** [comment]
@carmichaelong The only difference above is pelvis_rotation. Here's my interpretation: 
There's no guarantee that IK (done on markers) will produce a solution that has 0 for pelvis_tilt, list and non-zero for pelvis_rotation, only that the three rotations composed match the orientation, so overriding the solution of one coordinate leads to wrong global orientation as seen in the picture above (you can load the new std_* model added in the testOpensense test case in the GUI and modify pelvis_rotation to reproduce). In the case where we start from 0, 0, 0 that is built in by construction.

This is consistent with @malborno observation and feedback regarding why setting pelvis_rotation to 0 didn't work for him.

It's definitely worth trying to do the projection (as I do in the test case) before computing acos when doing the heading_correction, but as a change of the algorithm I'd do it as a separate issue/PR.

**Comment by carmichaelong** [comment]
Thanks, @aymanhab. I was playing around with the series of rotations, and I can see how this would make sense. I think I'm also now seeing how setting pelvis_rotation to 0 as a "pre-process" step to the heading correction calculation is an issue. Perhaps instead what should be done is to perform a space-fixed Y rotation that would set the pelvis_rotation to 0?
