### ISSUE TITLE
Update FV curve to match changes in inverse FV curve in MillardEquilibrium muscle

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#2896]
@mjhmilla I missed something in my review that caught my eye while checking out the changes after #2790 in the GUI. I noticed that the FV curve was not being updated even though the log would note a change. I tried adding a line to update the FV curve at https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L169 but then some tests with the equilibrium muscle fail. 

```
1>The following tests FAILED:
1>	 42 - testOutputReporter (Failed)
1>	 76 - testStaticOptimization (Failed)
1>	 82 - testCMCArm26_Millard (Failed)
1>	 86 - testCMCGait10dof18musc (Failed)

**Comment by mjhmilla** [comment]
Here's my suspicion (I'm replicating this right now):
  1. These tests compare a calculated solution against a pre-computed solution.
  2. Since the force-velocity curve has been altered, the calculated solution will not match IF the simulations go into the region between eccNearVmax and eccAtVmax, and concNearVmax and concAtVmax.

I propose the following:

1. Keep the original behaviour: the force-velocity curve is not modified beyond the original calls to setCurveShape on lines 131 & 146. The tests will then pass & previous simulations will also still look the same.

2. The log statements should be updated: log statements added to lines 131 & 146 (currently missing), update the log statements on 154 & 162 to apply to the force-velocity-inverse curve. Update the variable names conSlopeAtVmax and eccSlopeAtVmax to conSlopeFvInvAtVmax and eccSlopeAtFvInvVmax: then its clearer to developers that these internal variables only apply to the force velocity inverse curve.

I hope to have this fixed and pulled later today.

**Comment by mjhmilla** [comment]
I've just issued a pull request linked to this issue.

**Comment by nickbianco** [comment]
Closing per #2897.
