### ISSUE TITLE
InverseDynamicsTool/InverseDynamicsSolver: issue when a model's coordinates list differs from corresponding state's q's

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-core#2935]
`InverseDynamicsTool` generates a list of coordinates using `getCoordinatesInMultibodyTreeOrder()` (https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseDynamicsTool.cpp#L265) and makes a `FunctionSet` with corresponding splines in the same order (https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/InverseDynamicsTool.cpp#L285).

This is passed to an `InverseDynamicsSolver`, which then iteratively updates a `State` object based on the the order above, however, the `State` object is never checked to ensure that it is in the same order (or length) as the coordinates given by `getCoordinatesInMultibodyTreeOrder()`. This becomes an issue at https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/InverseDynamicsSolver.cpp#L116.

This came up as a concrete issue with the ThoracoscapularShoulderModel (though not necessarily limited to this model), whose State's `q` had a length of 18, but has 17 coordinates (and while the order is correct, there is an extra "unused" q at the 11th element, not at the end).

@nickbianco suggested using a new utility `createSystemYIndexMap()` (https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/SimulationUtilities.h#L152 ) to account for models that might have these issues.

@aseth1 any thoughts on this? Looks to me that this is an ID issue rather than a model issue, but wanted to make you aware of this just in case there might be anything I missed digging into here (and I'm happy to dig into things deeper too).

cc @antoinefalisse

**Comment by aseth1** [comment]
@carmichaelong @antoinefalisse sorry for my slow response. I agree this is an ID bug, but the issue is a bit more widespread. Whenever we map read-in values we have issues assigning them to the state. For example, we are using the Coordinate in all other cases to correctly set its value and speed in the state. This takes a lot of time, and in my initial implementation was likely doing that as well, but then it was taking more time to set values (set coordinate also has the nice feature of doing assembly so that constraints are satisfied in the GUI) than to actually solve.  So, yes I agree we need a way to quickly and robustly map from values (by name) to the correct slot in the state.  I think we could fix the Component interface to actually return SystemYIndex [here](https://github.com/opensim-org/opensim-core/blob/24a9cc74744d40989e45e87c74079d07737f283f/OpenSim/Common/Component.h#L2422-L2429).  @nickbianco your mapping utility would probably be simplified if that method was available. It could also be exposed by Model, since it is the creator of the State. 

Then the solver could create a map of `stateYIndices` once and instead of `q[i] = Qs.evaluate(i, ...)` we have `q[stateYIndices[i]] = Qs.evaluate(i,...) and  the tool does not have to worry about reordering the coordinate trajectories to match the state.  That would be nice!

**Comment by carmichaelong** [comment]
> I think we could fix the Component interface to actually return SystemYIndex here. @nickbianco your mapping utility would probably be simplified if that method was available. It could also be exposed by Model, since it is the creator of the State.

There's a fix in PR #2971 now that's focused on on the Tool level. Since we're aiming for a 4.2 release soon, I figured changing the Tool is safer than the Component interface. That being said, even if the PR is merged to resolve this issue for 4.2, I'd be in favor of creating a new issue to clean up the Component interface for post 4.2.
