### ISSUE TITLE
ID columns order is not consistent with IK (v. 4.x)

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3076]
Hi,

The order of columns in ID results file in OpenSim v. 4.x is not consistent with IK file, while in v. 3.3 this was correct. 

v. 4.x
`time	pelvis_tilt_moment	pelvis_list_moment	pelvis_rotation_moment	pelvis_tx_force	pelvis_ty_force	pelvis_tz_force	hip_flexion_r_moment	hip_adduction_r_moment	hip_rotation_r_moment	hip_flexion_l_moment	hip_adduction_l_moment	hip_rotation_l_moment	lumbar_extension_moment	lumbar_bending_moment	lumbar_rotation_moment	knee_angle_r_moment	knee_angle_l_moment	ankle_angle_r_moment	ankle_angle_l_moment	subtalar_angle_r_moment	subtalar_angle_l_moment	mtp_angle_r_moment	mtp_angle_l_moment`

v. 3.x
`time	pelvis_tilt_moment	pelvis_list_moment	pelvis_rotation_moment	pelvis_tx_force	pelvis_ty_force	pelvis_tz_force	hip_flexion_r_moment	hip_adduction_r_moment	hip_rotation_r_moment	knee_angle_r_moment	ankle_angle_r_moment	subtalar_angle_r_moment	mtp_angle_r_moment	hip_flexion_l_moment	hip_adduction_l_moment	hip_rotation_l_moment	knee_angle_l_moment	ankle_angle_l_moment	subtalar_angle_l_moment	mtp_angle_l_moment	lumbar_extension_moment	lumbar_bending_moment	lumbar_rotation_moment`

Is there any reason that the order has changed? 

As a user, I prefer the second one (v. 3.x) which has the same columns order as IK file and the Kinematics results in Analyze tool. It would be great if the index of each coordinate becomes identical in both ID and IK files.

Regards,
Mohammadreza

**Comment by aymanhab** [comment]
@mrrezaie Going from version 3.x to 4.x there was a major refactoring including building a tree of components, the order in 4.x is dictated by the tree traversal order while in 3.x it was likely based on the order in the file or coordinate list. The new design is more flexible. The key however is to not depend on the ordering of the columns in files since this may change in the future but instead to use API calls to extract data based on column names (DataTable subclasses), as such this is a documented behavior rather than a bug or development issue.
