### ISSUE TITLE
MATLAB MarkersReference not recognized in InverseKinematicsSolver constructor

### ISSUE THREAD

**Issue by CVHammond** [opensim-org/opensim-core#3087]
Using OpenSim 4.3, when declaring a new InverseKinematicsSolver, MATLAB returns a 'no constructor with matching signature' error response despite correct inputs, the issue appears to be in the MarkersReference object.

This bug can be reproduced with the following script on OpenSim 4.2 or 4.3:

```
import org.opensim.modeling.*
model = Model('model.osim')
InverseKinematicsSolver(model, MarkersReference(), SimTKArrayCoordinateReference())
```

If you use the command `methodsview InverseKinematicsSolver` and look at the constructor definitions, you can see the MarkersReference input SWIG value is an autogenerated value rather than the expected `org.opensim.modeling.MarkersReference`.

This bug does not exist in OpenSim 4.0. `methodsview InverseKinematicsSolver` shows `org.opensim.modeling.MarkersReference` for the MarkersReference parameter and the InverseKinematicsSolver can be declared without error.

**Comment by tkuchida** [comment]
Does your code work in previous versions of OpenSim? Based on [this test case in testInverseKinematicsSolver.cpp](https://github.com/opensim-org/opensim-core/blob/a01cf545485e8bc1f6e50b29ddeab229677de2c5/OpenSim/Simulation/Test/testInverseKinematicsSolver.cpp#L400), it seems like you would need to create a `MarkersReference` first and then pass that variable into the constructor for `InverseKinematicsSolver`.

**Comment by CVHammond** [comment]
My script works as expected on OpenSim 4.0. I am using the method you stated, declaring a `MarkersReference` and passing that into `InverseKinematicsSolver`.

**Comment by nickbianco** [comment]
We recently changed the Matlab and Python bindings to disallow wrapping types `std::shared_ptr<MarkersReference>`, due to issues with compatibility with new Moco tools (the changed was introduced when Moco was merged into OpenSim): https://github.com/opensim-org/opensim-core/blob/f9ef95ec8cd86e45a1df0b0faafcd4d6371dd9bc/Bindings/simulation.i#L224.

It looks like we shouldn't have done this, since the [InverseKinematicsSolver constructor you're trying to use](https://github.com/opensim-org/opensim-core/blob/a01cf545485e8bc1f6e50b29ddeab229677de2c5/OpenSim/Simulation/InverseKinematicsSolver.h#L83) takes as argument `std::shared_ptr<MarkersReference>`. We should undo the bindings change and find a better solution for the new Moco tools.

**Comment by aymanhab** [comment]
@nickbianco Thanks for looking into this but the issue with bindings is more complicated than it looks here and is not related to Mocos use of shared_ptr. I'm looking into it and will update here as I find out more.

**Comment by aymanhab** [comment]
@CVHammond You may want to test the branch for this PR, I included a test case that exercises the signature of the constructor, will beef up with more functionality/substance tests as needed.

**Comment by CVHammond** [comment]
Checked out the implementation, works with initial bug script as well as a few other tests
