### ISSUE TITLE
AnalyzeTool.setForceSetFiles() to append actuators not honored (MATLAB API v4.3)

### ISSUE THREAD

**Issue by ajyoder** [opensim-org/opensim-core#3099]
Ran into an issue with Static Opt not converging when executed via the MATLAB (v2021b) API 4.3, which would otherwise run fine if I printed setup.xml and executed in GUI.  This was sourced to reserve actuators not actually being appended by setForceSetFiles() method of AnalyzeTool when executed with the MATLAB environment, despite filename being valid

You can reproduce this issue using James Dunne's simple `matlab_static_optimization.zip` here:
[https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11013&p=40469&start=0&view=](url)
It will not converge in MATLAB API 4.3 as written, but will if you insert below:

```
%% Work-around for setForceSetFiles() not being honored - manually append them to model

model = Model(modelFileName);
so_actuators = ForceSet(forceSetFileName);
forceset = model.updForceSet; 
for fi=(1:so_actuators.getSize)-1
    forceset.cloneAndAppend(so_actuators.get(fi));
end
modelFileName_actuated = strrep(modelFileName,'.osim','_actuators.osim');
model.print(modelFileName_actuated)

%% Instantiate an AnalyzeTool and set the properties
at = AnalyzeTool();
at.setModel(model);
at.setModelFilename(modelFileName_actuated)
```

Perhaps there's a simple fix with an API command I missed, but wanted to point out anyways

Let me know and I can update my responses to a few other forum posts which reported the same issue: 
[https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11013&p=40469&start=0&view=](url)
[https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11791&p=40468&start=0&view=](url)
[https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=13120&p=40484&start=0&view=](url)

**Comment by carmichaelong** [comment]
@ajyoder Thanks for detailing the issue. I was checking out some of the posts again, and looks like another user responded with their fix at the bottom of this thread: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=11013&p=40469&start=0&view=

The gist is that `ArrayStr` wasn't being initialized correctly, likely due to the awkward constructor (see https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Array.html#aa7d3e878a688aadb50918be1f44c9dd3). For whatever reason, the default constructor sets the size of the array to 0, so I'm guessing that even though you passed a default value of the file name in, the `ArrayStr` was still empty. It's possible that your line could be fixed with: `at.setForceSetFiles(ArrayStr(filename, 1, 1))` or perhaps `at.setForceSetFiles(ArrayStr(filename, 1))`.

The user in the post got around this by first creating an empty `ArrayStr`, then adding an element to the `Array`, using the `set()` function.

Please let us know if any of these fixes work for you. While it may not technically be a bug, the interface definitely seems clunky enough to make it hard to debug that we could consider some way to reduce errors for users.

**Comment by ajyoder** [comment]
@carmichaelong to close this out, I can confirm the one-line fix initializing ArrayStr size to 1 works
 `at.setForceSetFiles(ArrayStr(filename, 1))`

As does the equivalent multi-line fix using `set()`, suggested by the user

**Comment by carmichaelong** [comment]
Thanks so much for checking @ajyoder! Please let us know if there is anything else that could be helpful for you.
