### ISSUE TITLE
Functions used by the GUI now missing

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#314]
- [ ] The method model.getSimbodyEngine().getWrapObject("wrapObjectName") used by muscle editor
- [ ] constructor of MarkerSet from a file without a model
- [ ] Easy way to swap in/out states used for backup/restore and by plotter
- [ ] Easy way to assign state vector to State (used by motion playback)

**Comment by jenhicks** [comment]
@aymanhab Are these all still missing and needed?

**Comment by aymanhab** [comment]
yes still missing, an alternative is still needed in each case.

**Comment by aseth1** [comment]
> model.getSimbodyEngine().getWrapObject("wrapObjectName") 

-> `model.getComponent<WrapObject>(wrapObjectName)`

> constructor of MarkerSet from a file without a model

I was unaware of this change. It appears @aymanhab made this change 2yrs ago?
Are you sure you still need it?

> Easy way to swap in/out states used for backup/restore and by plotter

please specify what functionality was changed/removed to disable what was working before. My belief is that the code (by Kevin) to update the state from properties and vice-versa remained intact since it accessed and restored state values by name (not index). Is that incorrect?

> Easy way to assign state vector to State (used by motion playback)

what methods were you calling to do this in the past or is the "Easy way" something new you are looking for?

@aymanhab let me know!

**Comment by aymanhab** [comment]
First item, great, that wasn't possible before making WrapObject into a component, now it is possible :+1:

MarkerSet from file, used by GUI to import a marker set, I think it'd be useful but would like to hear from @jimmyDunne or @chrisdembia if they used it.

For the last two, there are case where we know the model isn't changing (e.g. the plotter, changes coordinate value in a range to compute moment arm) and needs to restore full state at the end. As long as we can swap out/in Y vector (then call realize) then we're good. 
For motion playback, again we don't want name lookup for every coordinate on every frame, instead we use setY() directly. As long as we can do that (we can precompute indices as needed) then there should be no issues. Don't know the effect of the latest change in traversal order interacting with AnalyzeTool as used by plotter.

**Comment by aseth1** [comment]
@aymanhab thanks for the added details:

> MarkerSet from file, used by GUI to import a marker set, I think it'd be useful but would like to hear from @jimmyDunne or @chrisdembia if they used it.

It sounds like it could be important. Do you know why that constructor was removed/replaced? Feel free to put it back in.

> For the last two, there are case where we know the model isn't changing (e.g. the plotter, changes coordinate value in a range to compute moment arm) and needs to restore full state at the end. As long as we can swap out/in Y vector (then call realize) then we're good. 

I believe that or holding onto the backup state will also work.

> For motion playback, again we don't want name lookup for every coordinate on every frame, instead we use setY() directly. As long as we can do that (we can precompute indices as needed) then there should be no issues. 

I don't think you want to map indices either. This would be a great use case for the `StatesTrajectory`. You could rely on it to map from .STO to States for playback. What do you think @chrisdembia? 

> Don't know the effect of the latest change in traversal order interacting with AnalyzeTool as used by plotter.

Analyses are not Components and haven't been updated in a long time, so I am certain they rely on the Component of interest (`Body` -> `BodyKinematics`, `Joint`->`JointReaction`, ...) to live in a `Model` level `Set`. For old models this will be fine, but for newer models with nesting of subcomponents (like Bodies and Joint in a Device) this may be problematic since those Components will not be seen by the Analysis.

**Comment by chrisdembia** [comment]
> MarkerSet from file, used by GUI to import a marker set, I think it'd be useful but would like to hear from @jimmyDunne or @chrisdembia if they used it.

I think being able to deserialize a MarkerSet is important.

> I don't think you want to map indices either. This would be a great use case for the StatesTrajectory. You could rely on it to map from .STO to States for playback. What do you think @chrisdembia?

StatesTrajectory should be useable in its current state for motion playback. But I think it would be good to be able to map indices; #1112.

**Comment by aymanhab** [comment]
Perfect, thanks @aseth1 and @chrisdembia for the feedback. Will definitely try the StateTrajectory as a first choice. The interface from Java looks promising @chrisdembia except for some iterators that are unusable. Will tackle then.
