### ISSUE TITLE
Matlab Crash: solver.get_parallel() 

### ISSUE THREAD

**Issue by stingjp** [opensim-org/opensim-core#3187]
Was trying to play around with parallelization. Set up a full muscle-driven, 3D tracking simulation. After getting the solver object, tried to call solver.get_parallel(), and it crashes MATLAB. 
Attached the crash log.
[solver.get_parallel_crashReport.txt](https://github.com/opensim-org/opensim-core/files/8498969/solver.get_parallel_crashReport.txt)

**Comment by stingjp** [comment]
Just tried to replicate, but used the `solver.set_solver(int)` call first, and it didn't crash.

**Comment by nickbianco** [comment]
`solver.get_parallel()` crashes because the `parallel` property is optional, so it doesn't have a value by default. Makes sense that it doesn't crash after you set it. 

There's some comments about why it is optional in the `MocoCasADiSolver` documentation.

**Comment by nickbianco** [comment]
It's not great that a crash occurs when the value is not set, but this property needs to stay optional [so that the parallel setting logic remains intact](https://github.com/opensim-org/opensim-core/blob/6953a250f6dd6ffab2ebefdab03575973cfd80a3/OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.cpp#L152).

Perhaps we add a warning in the `MocoCasADiSolver` docs that this property is optional and will crash if accessed before setting.

**Comment by aymanhab** [comment]
@nickbianco What is the meaning of the value passed in to set_parallel()? I'd assume some default of 0 or 1 would mean no parallelization without additional work but I don't know enough about how the solvers internals work.

**Comment by nickbianco** [comment]
The settings are described here: https://github.com/opensim-org/opensim-core/blob/6953a250f6dd6ffab2ebefdab03575973cfd80a3/OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.h#L145

**Comment by jenhicks** [comment]
Please re-open if this is still causing issues.
