### ISSUE TITLE
WARNING: Thelen2003Muscle::computeInitialFiberEquilibrium(SimTK::State& s) 

### ISSUE THREAD

**Issue by 19islandprincess96** [opensim-org/opensim-core#3240]
Hi! I am trying to simulate the LLSM in OpenSim (https://simtk.org/projects/llsm/) and I get the following error for multiple muscles:

WARNING: No suitable initial conditions found for
  ADD_LONG_5_R: 
  by 

WARNING: Thelen2003Muscle::computeInitialFiberEquilibrium(SimTK::State& s) 
Continuing with an initial fiber force and length of 0 and 0.105730
    Here is a report from the routine:
 
        Solution Error      : 3696554.733092 > tol (0.000003) 
        Newton Iterations   : 200 of max. iterations (200)
    Check that the initial activation is valid, and that the whole 
    length doesn't produce a pennation angle of 90 degrees, nor a fiber
    length less than 0:
        Activation          : 0.050000 
        Whole muscle length : 1.#QNAN0 

Any idea how I can fix this?

**Comment by tkuchida** [comment]
The `computeInitialFiberEquilibrium()` method could not find an equilibrium solution between the fiber and tendon. You can try contacting the model's authors to see whether they have an updated version of the model---presumably they have solved this issue already since I see that they published a paper using the model. If you need to solve the problem yourself, you can try setting the muscle's `default_activation` and/or `default_fiber_length` properties. Please post questions of this nature to the [OpenSim User's Forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91) as GitHub is used to track software development tasks.
