### ISSUE TITLE
Thelen2003Muscle fails to update upon setPennationAngleAtOptimalFiberLength()

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#326]
The Thelen2003Muscle uses a MuscleFixedWidthPennationModel component internally which also has the same pennation property. If the convenience constructor of the muscle is called with the pennation as an argument it is pushed down to the pennation model, but if `setPennationAngleAtOptimalFiberLength()` only the muscle's property is updated and the pennation model remains out-of-date.

**Comment by tkuchida** [comment]
@aseth1 It seems like an easy solution would be to make [`Muscle::setPennationAngleAtOptimalFiberLength()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Model/Muscle.h#L117) virtual and override it in Thelen2003Muscle, but that seems unhygienic. I'm guessing you had something else in mind?

**Comment by tkuchida** [comment]
:thought_balloon: Could also put a check in [`getPennationModel()`](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Thelen2003Muscle.cpp#L206) to make sure all its properties are correct, and ensure `getPennationModel()` is called in place of `penMdl`(e.g., [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Thelen2003Muscle.cpp#L598)). Seems less bad, but still not great.

**Comment by aseth1** [comment]
or, make a pendulum model a ModelComponent and a a real subcomponent of the Thelen muscle. Then replace `buildMuscle` and  `ensure<>UpToDate()` methods with a complete `extendFinalizeFromProperties`.

**Comment by tkuchida** [comment]
@aseth1 Why is the `activation_time_constant` property duplicated in `Thelen2003Muscle()` and `MuscleFirstOrderActivationDynamicModel()`? Is this duplication necessary to get the property to show up in the GUI?

**Comment by aymanhab** [comment]
Tom,

The Gui does no special treatment of objects so all properties are editable
and exposed as far as I know.

Ayman

**Comment by tkuchida** [comment]
Thanks, @aymanhab. I think I understand now: since `MuscleFirstOrderActivationDynamicModel` is currently a private member of `Thelen2003Muscle()` (not a subcomponent), the properties of `MuscleFirstOrderActivationDynamicModel` aren't visible from the GUI. Seems like a good opportunity to take advantage of the Component interface.

**Comment by tkuchida** [comment]
@aseth1 Please take a look at OptimizationExample.cpp (under Examples - exampleOptimization). Here's what I get when printing out the properties of the pennation model immediately before `// Optimize it!` (see image). Apparently, the properties of the pennation model are not being set during deserialization! What is the extent of this bug :worried:? My changes are causing testOptimizationExampleRuns to time out because it's solving a different problem (i.e., one with the correct pennation model properties) and the stopping criteria are not appropriate; I will update these criteria in my branch.
![pennationmodelbug](https://cloud.githubusercontent.com/assets/4203505/6456815/a02f2076-c11f-11e4-8cd3-4d62b03d5378.png)

**Comment by tkuchida** [comment]
@aseth1 I tested with Simbody 3.3.1/OpenSim 3.2 and the pennation model parameters *are* being set correctly, so this is a post-3.2 issue.
cc/ @chrisdembia

**Comment by aseth1** [comment]
Yes, it is a post 3.2 issue! I broke it when I added `finalizeFromProperties` and/or `extendFinalizeFromProperties()`. I likely eliminated a call to buildMuscle. The muscle property value should get pushed  down to the pennation model component in the muscle's `finalizeFromProperties`.

**Comment by sherm1** [comment]
> this is a post-3.2 issue

Yay! My faith in simulation has been restored.

**Comment by chrisdembia** [comment]
:fireworks: Is there a systematic way to ensure we didn't break other things since 3.2?

**Comment by sherm1** [comment]
Er, regression tests?

**Comment by aseth1** [comment]
> Is there a systematic way to ensure we didn't break other things since 3.2?

Practically, no. In general I think the tests do an OK job to prevent new bugs being introduced. It is clear that the tolerances are lax but also t the model is relatively insensitive to pennation angle in general. So it was kind of a fluke that it passed the the regression tests. 

In this particular set of code, there is simply too much micro-management by the developer who tried to pre-empt any changes by peppering the code with `ensureMuscleIsUpToDate` and `buildMuscle` calls everywhere. I think that approach was doomed. I could also have been more careful :grin:
