### ISSUE TITLE
Controller::addActuator() should take pointer not reference

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#329]
The `Controller::addActuator()` method is defined to take a `const Actuator&`. It then goes through horrifying contortions [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Simulation/Control/Controller.cpp#L156) to turn that into a non-const pointer and then take over ownership as though it had received a heap-allocated object!

I noticed this because the very first example we have for the OpenSim API, in the `README.md` file, treats this method inconsistently from all the others. Here is an excerpt:

``` c++
    OpenSim::Body* link1 = new OpenSim::Body("humerus", 1, Vec3(0), Inertia(0));
    OpenSim::Body* link2 = new OpenSim::Body("radius", 1, Vec3(0), Inertia(0));
    // etc.
    PrescribedController* brain = new PrescribedController();
    brain->addActuator(*muscle); // NOTE reference passed; should be heap ptr

    // Everything else takes a pointer:
    brain->prescribeControlForActuator("biceps",  new StepFunction(0.5, 3, 0.3, 1));
    model.addBody(link1); model.addBody(link2);
    model.addJoint(joint1); model.addJoint(joint2);
    model.addForce(muscle);
    model.addController(brain);
```

**Comment by chrisdembia** [comment]
There's a comment also above those contortions saying:

```cpp
    // want to keep a reference not make a clone
    // but set interface does not take const pointer
    // just const ref that forces a copy
    // const_cast only to add to the private set of actuators
```

@aseth1 will connectors allow us to get rid of the Controller's Set of actuators? It seems like they won't, because there are a fixed number of connections at compile-time. Would it be possible to add connections at runtime?

**Comment by sherm1** [comment]
From discussion, the API might be right as is but it shouldn't be adopting internally. Ajay will take a look.

**Comment by aseth1** [comment]
The confusion is that `Set::adoptAndAppend()` is not adopting the pointer if `Set::setMemoryOwner(false)`, which it is.  The Set is not necessary in this context and we could just have an internal Array of actuators. We should do our best to stop using the `OpenSim::Set` in my opinion. 

I think `addActuator(const Actuator& act)` is correct and the  `Model::add<Component>()` methods should be renamed to `adopt` since Model is taking ownership of Components. It might be nice to have `add` as well where we keep a reference and no ownership occurs.

**Comment by aseth1** [comment]
@chrisdembia I am thinking that a Connector for lists of dependencies of the same type would be useful instead of list of Connectors. You are right that this is just a list of dependencies  on Actuators like two Bodies for a Joint.

**Comment by aseth1** [comment]
> From discussion, the API might be right as is but it shouldn't be adopting internally. Ajay will take a look.

To reiterate. The Controller does NOT take ownership (adopt) even though the `Set::adoptAndAppend()` is invoked because we call `Set::setMemoryOwner(false)`.  This is internal details of the Controller, which admittedly is ugly, but does not impact the API.

A modest improvement would be to use the a `ListSocket` now that we have them.  I think we can push that to the next release (or during GUI testing).

**Comment by aseth1** [comment]
@jenhicks @chrisdembia I think this can be closed. It is not a bug. It could be updated to use list socket for Controller's dependency on actuators.

**Comment by chrisdembia** [comment]
We do not yet have list sockets (just list inputs), but most of the infrastructure should now be there to enable list sockets when/if we decide to implement them.

**Comment by chrisdembia** [comment]
I agree that the longer-term fix is to use list sockets.

**Comment by jenhicks** [comment]
I think it is OK to close and reopened later, as needed.
