### ISSUE TITLE
Manager constructor that doesn't take integrator leads to exception

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#335]
```
simbody/SimTKmath/Integrators/src/TimeStepperRep.h:66: SimTK::Integrator &SimTK::TimeStepperRep::updIntegrator(): Assertion `integ' failed.
```

I guess we have no use cases of this in the code.

See related https://github.com/opensim-org/opensim-core/pull/106

**Comment by sherm1** [comment]
Per Ajay: would be better to replace this with a sensible Solver component in 4.0.

**Comment by chrisdembia** [comment]
#156.

**Comment by mizimmer** [comment]
I've just run into this error using the Java bindings.  Is there a workaround, e.g. a class other than Manager that can be used to integrate a model in time?  A change to the underlying C++ code might be in order...

**Comment by chrisdembia** [comment]
Yes; directly use Simbody classes to do the integration (like [here](https://github.com/opensim-org/opensim-core/blob/ea91ce0fc8759fc249d26b232695f00e33b6e5ed/OpenSim/Common/Test/testDelay.cpp#L187)).

**Comment by mizimmer** [comment]
chrisdembia, thanks so much for your reply!  More precisely, my issue is that the Java bindings do not expose any SimTK implementations of Integrator, so I cannot instantiate a Manager with an existing instance of Integrator.  Using the Manager constructor without an Integrator (which is presently my only option) leaves the manager with a NULL pointer to an Integrator, so I get a C++ segfault when calling methods like doIntegration(...) from Java.

There is also something strange about the SWIG-generated getIntegrator() method in the Manager Java class.  It creates a new Integrator and returns it; is this the expected behavior?

I wonder if it would be possible to add a convenience method to the Manager C++ class to generate a new Integrator internally. Another option would be to expose the RungeKuttaMersonIntegrator, etc. to SWIG for Java wrapping.

I could help if you have some guidance on which solution might be best.  I'm trying to integrate OpenSim into a couple of ongoing research projects and am happy to dive deep into the code base.

**Comment by aymanhab** [comment]
@mizimmer Wonderful to have you on board. Should I assume you're working with the master branch? If so, can you describe at a high level what you're trying to accomplish so we know if you'll need more of the simbody internals?

**Comment by mizimmer** [comment]
@aymanhab Thanks for your reply.  I am working with the master branch. In short, I'd like to add my own decorative geometry to a OpenSim full-body model and develop my own GUI for posing and doing science-grade analysis of forces on the body with massive accessories attached. I need to work exclusively with the Java bindings.

It would be really neat to implement dynamic feedback when posing the model, like a muscle "resisting" the motion of a limb as it is being posed by a user (e.g. eventually saturating and limiting the motion of the limb). I am still learning about the capabilities of OpenSim and human body modeling so I don't know if this would be possible.

I have experience using open-source codes on other scientific projects, and I could help with the implementation of a bug fix for the present issue, if needed.

**Comment by aymanhab** [comment]
Thanks for sharing your thoughts and plans @mizimmer we should definitely discuss the GUI side (you can email my simtk.org user account to discuss further) to see if we can coordinate to help the user community. 

From what you describe it sounds like you'll need more of the underlying Simbody classes exposed thru SWIG down the road. I'd suggest you take a stab at exposing the Integrator(s) as a first step (create a Fork/branch/PR etc.), once we have this sorted out we can go to the next step (wrapping more classes, wrapping Simbody as a separate module etc.). Please let me know what you think or if you need help getting started.

**Comment by chrisdembia** [comment]
We should time those changes with the removal of the SWIGSimTK folder.
