### ISSUE TITLE
'InverseKinematicsSolver' object has no attribute 'addOrientationValuesToTrack'

### ISSUE THREAD

**Issue by flamerten** [opensim-org/opensim-core#3415]
I am currently attempting to recreate the [OpenSenseRT](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Wearable+and+Real-time+Kinematics+Estimates+with+OpenSense). I have successfully flashed a microsd card with Ubuntu Server 20.04, built opensim on Linux and prepared it for scripting in python. 

However, while following the file [ik_streaming.py](https://github.com/pslade2/RealTimeKin/blob/main/ik_streaming.py), I got stuck, and was unable to run the full program due to the error as written in the title.

    Starting recording...
    Traceback (most recent call last):
      File "ik_streaming.py", line 153, in <module>
        ikSolver.addOrientationValuesToTrack(time_s+dt, rowVec)
    AttributeError: 'InverseKinematicsSolver' object has no attribute 'addOrientationValuesToTrack

I'm not too sure why Im facing such an error. From looking through the documentation, I do not find any methods that mention addOrientationValuesToTrack. However, OpenSenseRT is based on a research paper and its weird there is a function that does not exist.  Are there other alternatives to that line which I could consider to continue on with the OpenSenseRT code?

**Comment by aymanhab** [comment]
The API referred to here is obsolete and was only used during the development of 4.3 but then got subsumed by more recent versions. Please point to the code base using this interface so we can upgrade or use it with pre-built version of the libraries consistent with this API.

**Comment by flamerten** [comment]
Hi @aymanhab thanks for the reply, this makes sense. 

The code base that was using it was the Github Repo of OpensenseRT 
https://github.com/pslade2/RealTimeKin/blob/94b6f6dda6d369ea565517c2878d1c164f5424ab/ik_streaming.py#L150 

By any chance, would you know how i could replace that line? Thank you!

**Comment by flamerten** [comment]
@aymanhab I would like to provide an update.

It seems as though that the `addOrientationsToTrack` method has been replaced by the `BufferedOrientationsReference` object, where you keep a buffer to store data. From there, I modified the code based on 2 Pull Requests i found: #2843 and #2855. #2843 uses `addOrientationsToTrack` but #2855 updated this with certain changes. However, my attempts to replicate this have led to 2 errors. 

# Error 1 - BufferedOrientationsReference object Declaration
```python
quatTable = osim.TimeSeriesTableQuaternion(sto_filename)
orientationsData = osim.OpenSenseUtilities.convertQuaternionsToRotations(quatTable)
oRefs = osim.BufferedOrientationsReference(orientationsData) #error
```

```
TypeError: Wrong number or type of arguments for overloaded function 'new_BufferedOrientationsReference'.
  Possible C/C++ prototypes are:
    OpenSim::BufferedOrientationsReference::BufferedOrientationsReference()
    OpenSim::BufferedOrientationsReference::BufferedOrientationsReference(OpenSim::BufferedOrientationsReference const &)
    OpenSim::BufferedOrientationsReference::BufferedOrientationsReference(OpenSim::BufferedOrientationsReference &&)

```

I am not sure why `orientationsData` cannot be passed in as a parameter, as `BufferedOrientationsReference` is a subclass of `OrientationsReference`. 

# Error 2 - putValues method

```python
quatTable = osim.TimeSeriesTableQuaternion(sto_filename)
orientationsData = osim.OpenSenseUtilities.convertQuaternionsToRotations(quatTable)
rowVecView = orientationsData.getNearestRow(time_s)
rowVec = osim.RowVectorRotation(rowVecView)


oRefs.putValues(time_s+dt, rowVecView)
```

```
Traceback (most recent call last):
  File "ik_streaming.py", line 183, in <module>
    oRefs.putValues(time_s+dt, rowVec)
  File "/home/ubuntu/opensim-core/sdk/Python/opensim/simulation.py", line 34068, in putValues
    return _simulation.BufferedOrientationsReference_putValues(self, time, dataRow)
TypeError: in method 'BufferedOrientationsReference_putValues', argument 3 of type 'SimTK::RowVector_< SimTK::Rotation > const &'
```

I find this strange as well, because there was a very similar line that was one in the testLiveIK.cpp file, in this line [here](https://github.com/opensim-org/opensim-core/blob/791b41ba3b9fb92b94bcc2c585b86bd540cdce3e/Applications/IK/test/testLiveIK.cpp#L350). From what i understand, the reason why this error is thrown is due to `getNearestRow` returning a `rowVectorView` object. However, the `putValues` method wants a `rowVector` object. Again, this is strange because rowVectorView in a subclass of rowVector so it should be accepted as a `rowVector`. 

# 
I'm not sure the reason for these errors. After debugging, I have a feeling there might be an issue with the python build, perhaps the SWIG script had some errors leading to some public methods not being exported when the python version was built. 

Hope you can provide some assistance by clarifying if there is indeed a bug with SWIG, a problem with my python build or a misunderstanding of the C++ API. Thank you.

**Comment by RTnhN** [comment]
This is still a problem. I have tried changing to Swig version 4.0.2 to see if it is a problem with the newest version. I also noticed that the real time part of opensense (specifically the bufferedOrientationReference part) is not part of the test suite.

**Comment by RTnhN** [comment]
I found the problem. Evidentially there were some missing types. While it might have worked for c++, I think that it confused Swig. I fixed it here: https://github.com/opensim-org/opensim-core/commit/b6862e9815252790691c549c810ab921fc02a387. I will plan on making a PR this week.

**Comment by nickbianco** [comment]
Good catch @RTnhN! Happy to review your PR whenever it comes in.

**Comment by RTnhN** [comment]
Thanks, @nickbianco! The PR is #3644.

**Comment by RTnhN** [comment]
We should be able to close this issue now that the PR is merged, right?

**Comment by aymanhab** [comment]
Sure, closing!

**Comment by RTnhN** [comment]
I realized that this is not completely solved. SWIG has a problem with initializing constructors from base classes using `using super::super;`. This was a problem until swig 4.2.0 which was released recently. I need the constructor of OrientationReference for BufferedOrienationReference to add the Names for the different orientations and initialize it correctly. I thought that just using the method `putValues` could be used for initialization, but it does not initialize it properly as seen in https://github.com/pslade2/RealTimeKin/issues/8.

You can see where they fixed the problem here: https://www.swig.org/Doc4.2/CPlusPlus11.html#CPlusPlus11_object_construction_improvement (notice that they say that using the `using` keyword is not possible with earlier versions of SWIG)

So I think the solution would be to change to SWIG 4.2.0, but this is kind of a headache. I have done a little work with it, and it looks like they made a bunch of changes, so it is not as easy as changing all references of SWIG 4.1.1 to 4.2.0. For example, [they removed an interface file `std_carray.i` and merged it into `std_array.i`](https://github.com/swig/swig/commit/00d3b04b46e1b8a58fbf77fd377133fee816ae5a), so where we reference it below will need to be changed. 

https://github.com/opensim-org/opensim-core/blob/4c76879d2c2d9a01697fe51bc0a460d362a83f3c/Bindings/Python/swig/python_preliminaries.i#L15

**Comment by aymanhab** [comment]
@RTnhN Thanks for reporting, with that should this issue be reopened? Also did the previous commit make any difference to justify patching into 4.5 release as it stands? Thank you

**Comment by RTnhN** [comment]
@aymanhab Maybe it might be good to open up another issue and reference this one. This issue had a bunch of different problems, some of which were resolved. 

The previous commit does make a difference. It resolved one of the problems in this issue, so I think it justifies patching into 4.5.

**Comment by RTnhN** [comment]
Acutally, I will just open it again.

**Comment by RTnhN** [comment]
I tried manually changing the `using` statement to the explicit declaration, and this compiled well and the bindings were able to be made and used. 
``` diff
     // CONSTRUCTION
     //--------------------------------------------------------------------------
     BufferedOrientationsReference();
+    // Constructor with orientation file name and model units
+    BufferedOrientationsReference(const std::string& orientationFileName,
+                                  Units modelUnits=Units(Units::Radians))
+        : OrientationsReference(orientationFileName, modelUnits) {}
+    // Constructor with TimeSeriesTable and optional OrientationWeightSet
+    BufferedOrientationsReference(const TimeSeriesTable_<SimTK::Rotation_<double>>& orientationData,
+                                  const Set<OrientationWeight>* orientationWeightSet=nullptr)
+        : OrientationsReference(orientationData, orientationWeightSet) {}
     BufferedOrientationsReference(
             const BufferedOrientationsReference&) = default;
     BufferedOrientationsReference(BufferedOrientationsReference&&) = default;
     BufferedOrientationsReference& operator=(
             const BufferedOrientationsReference&) = default;
 
-    // Use OrientationsReference convenience costructor from TimeSeriesTable
-    using OrientationsReference::OrientationsReference;
 
     virtual ~BufferedOrientationsReference() {}
```
Using [this](https://github.com/opensim-org/opensim-core/blob/791b41ba3b9fb92b94bcc2c585b86bd540cdce3e/Applications/IK/test/testLiveIK.cpp) as a reference, I made some tweaks to Patrick's code, and while I was able to create a copy of BufferedOrientationsReference with a data table so that I could get the names of the segments, I ran into a problem. 

When I ran approximately these commands, I got the following runtime error:

``` python
quatTable = osim.TimeSeriesTableQuaternion(sto_filename)
orientationsData = osim.OpenSenseUtilities.convertQuaternionsToRotations(quatTable)
oRefs = osim.BufferedOrientationsReference(orientationsData)
oRefs.setDefaultWeight(1.0)
init_state = model.initSystem()
mRefs = osim.MarkersReference()
coordinateReferences = osim.SimTKArrayCoordinateReference()
model.initSystem()
s0 = init_state
ikSolver = osim.InverseKinematicsSolver(model, mRefs, oRefs, coordinateReferences, constraint_var)
ikSolver.setAccuracy = accuracy
s0.setTime(0.)
ikSolver.setAdvanceTimeFromReference(True)
ikSolver.assemble(s0)
```

```
  File "/home/sage/RealTimeKin/ik_streaming.py", line 117, in <module>
    ikSolver.assemble(s0)
  File "/home/sage/.local/lib/python3.7/site-packages/opensim/simulation.py", line 33344, in assemble
    return _simulation.AssemblySolver_assemble(self, s)
RuntimeError: std::exception in 'void OpenSim::AssemblySolver::assemble(SimTK::State &)': getNextValuesAndTime method is not supported for this reference {}.
```

This is exactly what is expected if I was using the "OrientationsReference" object in the `inverseKinematicSolver`.

https://github.com/opensim-org/opensim-core/blob/98c70b1fd5bc74da63e69a52e860c742840a9a16/OpenSim/Simulation/OrientationsReference.h#L129-L134

I was explicitly not using the base `OrientationsReference` though. In fact, if I manually call the `getNextValuesAndTime` method on the `oRef` variable, it returns the expected information. So for some reason, the `InverseKinematicsSolver` object is using the base (super) method instead of the derived (self) method. I see that `InverseKinematicsSolver` constructor is defined with the `std::shared_ptr<OrientationsReference>` which hopefully won't cause the `InverseKinematicsSolver` to use the base class method instead of the derived class method. We don't need to create a constructor for the `InverseKinematicSolver` that explicitly uses like a shared pointer to `BufferedOrientationsReference`, right? 

As a sanity check, the `getNextValuesAndTime` method is declared as `virtual` in the base class, it has the same signatures in both the base class and the derived class, and it has the override keyword even though this is more optional. I don't get any squawks from the compiler about not having a corresponding virtual method, so it seems that the compiler associates these two methods well. 

I also tried not using "setAdvanceTimeFromReference" and manually adjusting the time, but that just gave me a "key not found" error which is what is expected if it was calling the base method and was trying to find a value in the table just used to construct the `BufferedOrienationsReference`.

Do you have any idea why the inheritance is not working as expected?

**Comment by aymanhab** [comment]
Thanks for investigating this, I'd try a constructor for the solver that takes the shared_ptr to BufferedOrientationsReference to test if this is a swig issue or something else as handling of smart pointers across the interface  is rather fragile. Let me know what you find out. Thank you

**Comment by RTnhN** [comment]
That's a great point. I can try that and see if that fixes it. Thanks for the idea.

**Comment by RTnhN** [comment]
Okay, I added the right constructor and it works somewhat. I can put data into the data queue for the bufferedOrientationsReference, but it still hangs at the `ikSolver.track(s0)` step. I found out that the oRefs object in python and the oRefs object in the ikSolver object are different. I put logging in the queue to tell me when data is pushed or popped. I push data and it says that it is pushed. I go to pop the data, but there is no data to pop. I use the python method to get data, and it says that it was popped. It does not say that it was popped any other time, so I think they are two different objects: the `oRefs = osim.BufferedOrientationsReference(orientationsData)` object and the object referenced in the ikSolver object. Overall, I think this is probably a smart pointer problem. 

When digging into how Swig deals with smart pointers, I did see some things that might need to change in the interface files for it to work. 

This is all from the [SWIG documentation on smart pointers](https://www.swig.org/Doc3.0/SWIGDocumentation.html#Library_std_shared_ptr:~:text=causing%20a%20crash.-,9.4.4%20shared_ptr%20smart%20pointer,-Some%20target%20languages)

1. Strangely enough, the definition needs to happen _after_ the shared pointer macro is used. So, it should be:
```
%shared_ptr(BufferedOrientationsReference);
%include <OpenSim/Simulation/BufferedOrientationsReference.h>
```
["Note that the %shared_ptr(IntValue) declaration occurs after the inclusion of the boost_shared_ptr.i library which provides the macro and, very importantly, before any usage or declaration of the type, IntValue."](https://www.swig.org/Doc3.0/SWIGDocumentation.html#Library_std_shared_ptr:~:text=Note%20that%20the%20%25shared_ptr(IntValue)%20declaration%20occurs%20after%20the%20inclusion%20of%20the%20boost_shared_ptr.i%20library%20which%20provides%20the%20macro%20and%2C%20very%20importantly%2C%20before%20any%20usage%20or%20declaration%20of%20the%20type%2C%20IntValue.)

2. This is a pretty large change, but I think that _every_ base class of a derived class needs to be defined as a smart pointer using the macro. 

["A proxy class derived from a base which is being wrapped with shared_ptr can and must be wrapped as a shared_ptr too. In other words all classes in an inheritance hierarchy must all be used with the %shared_ptr macro."](https://www.swig.org/Doc3.0/SWIGDocumentation.html#Library_std_shared_ptr:~:text=A%20proxy%20class%20derived%20from%20a%20base%20which%20is%20being%20wrapped%20with%20shared_ptr%20can%20and%20must%20be%20wrapped%20as%20a%20shared_ptr%20too.%20In%20other%20words%20all%20classes%20in%20an%20inheritance%20hierarchy%20must%20all%20be%20used%20with%20the%20%25shared_ptr%20macro.)

When I compiled with the right order (macro before definition), it gave me the expected warnings: 

```
/home/sage/opensim-workspace/opensim-core-source/OpenSim/Simulation/BufferedOrientationsReference.h:44: Warning 520: Base class 'OpenSim::OrientationsReference' of 'BufferedOrientationsReference' is not similarly marked as a smart pointer.
/home/sage/opensim-workspace/opensim-core-source/OpenSim/Simulation/BufferedOrientationsReference.h:44: Warning 520: Base class 'OpenSim::StreamableReference_< SimTK::Rotation_< double > >' of 'BufferedOrientationsReference' is not similarly marked as a smart pointer.
/home/sage/opensim-workspace/opensim-core-source/OpenSim/Simulation/BufferedOrientationsReference.h:44: Warning 520: Base class 'OpenSim::Reference_< SimTK::Rotation_< double > >' of 'BufferedOrientationsReference' is not similarly marked as a smart pointer.
/home/sage/opensim-workspace/opensim-core-source/OpenSim/Simulation/BufferedOrientationsReference.h:44: Warning 520: Base class 'OpenSim::Object' of 'BufferedOrientationsReference' is not similarly marked as a smart pointer.

```

The macro is seemingly used correctly in most of the repo except for below where they should be moved up:

https://github.com/opensim-org/opensim-core/blob/f291e0b887fd8c44c6520f333749bf7c5117194f/Bindings/simulation.i#L213-L223

Actually, when I rearrange it, I get this error:

```
/home/sage/opensim-workspace/opensim-core-build/Bindings/Python/python_simulation_wrap.cxx: In function ‘PyObject* _wrap_delete_OrientationsReference(PyObject*, PyObject*)’:
/home/sage/opensim-workspace/opensim-core-build/Bindings/Python/python_simulation_wrap.cxx:329637:26: error: ‘smartarg1’ was not declared in this scope
       (void)arg1; delete smartarg1;
                          ^~~~~~~~~
/home/sage/opensim-workspace/opensim-core-build/Bindings/Python/python_simulation_wrap.cxx:329637:26: note: suggested alternative: ‘slartg_’
       (void)arg1; delete smartarg1;
                          ^~~~~~~~~
                          slartg_
/home/sage/opensim-workspace/opensim-core-build/Bindings/Python/python_simulation_wrap.cxx: In function ‘PyObject* _wrap_delete_BufferedOrientationsReference(PyObject*, PyObject*)’:
/home/sage/opensim-workspace/opensim-core-build/Bindings/Python/python_simulation_wrap.cxx:332713:26: error: ‘smartarg1’ was not declared in this scope
       (void)arg1; delete smartarg1;
                          ^~~~~~~~~
/home/sage/opensim-workspace/opensim-core-build/Bindings/Python/python_simulation_wrap.cxx:332713:26: note: suggested alternative: ‘slartg_’
       (void)arg1; delete smartarg1;
                          ^~~~~~~~~
                          slartg_
ninja: build stopped: subcommand failed.

``` 

When I researched it, it turned out to be the problem of not having all of the base classes defined as smart pointers based off of [this stack overflow question](https://stackoverflow.com/a/11426877/11351671). I think the solution to this will be a lot harder than expected. I am still trying things, but I just wanted to get an update out.

**Comment by RTnhN** [comment]
I don't think that using smart pointers will be a viable solution since the swig support for them is lacking and is causing major problems. 

It seems that the only way to get real-time inverse kinematics going is to do something similar to how the iksolver did real time in the past. This involves using a method connected to the iksolver object rather than the directly on the orientaionsReference object. I have tested the following addition into the InverseKinematicsSolver class, and it is able to run the RealTimeKin code. 

``` cpp
void InverseKinematicsSolver::updateOrientationData(double time, const SimTK::RowVectorView_<SimTK::Rotation_<double>>& dataRow)
{   
_orientationsReference->putValues(time, dataRow); 
}
```
What do you think are next steps? I could just use my fork of the repo for my work, but I would rather find a workable solution for the main repo.

**Comment by aymanhab** [comment]
Thanks for your work on this @RTnhN much appreciated 👍 

It would be good to take a look before lifting the API to the solver (because this type of call is supported only for the special BufferedOrientationReference and not any other Reference type so could be confusing to users). I totally agree that SWIG handling of shared_ptr is poorly documented, but hopefully we can figure out the issue/learn something from it for wider use before changing the API on the c++ side. Maybe a PR wit the problem code would help. Thanks again

**Comment by RTnhN** [comment]
Okay, I created a PR so that you can see the code so far. I did find out that the namespace was missing. Once I added it, I did not have any problems with it compiling, but it still does not work. I put data in the queue, but the queue is empty when I go to get data.
