### ISSUE TITLE
Updates to `CustomStaticOptimization` for 485

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3430]
This issue is to capture changes we need to implement in `CustomStaticOptimization.m` for the ME/BIOE 485 class this spring.

FYI @carmichaelong, @nicos1993, @gurchiek: feel free to add anything you think we need.

### Changes needed
- [x] Add pennation angle (or cos(angle)) to the [Confluence page](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Custom+Static+Optimization+in+MATLAB).
- [x] Add note about why we need reserve/residual moments to the confluence page.
- [x] Clarify what is dependent on the `ignore_tendon_compliance` property and what is not. (Maybe point out how the number of state variables change when the property is enable/disabled).
- [x] Discuss muscle-tendon equilibrium (if solutions require the `ignore_tendon_compliance` property).
- [x] Discuss obtaining the characteristic curves from the Millard model (if solutions do not require the tendon compliance property).
- [x] Provide the code for setting coordinate values, and then instruct students to set the coordinate speeds.
- [ ] Add a note about assembling the `SimTK::State` to the Confluence page.

**Comment by nicos1993** [comment]
These are a couple of things I also noticed that perhaps need to be changed/investigated:

- The external loads file to perform ID does not explicitly mention in the filename that it is the file needed to `idTool.setExternalLoadsFileName()` - so I would perhaps considering changing to `grf_walk_external_loads.xml`
- Myself and Reed noticed that setting a muscle's tendon compliance and activation dynamics to ignore by using `muscle.setIgnoreTendonCompliance(state,true)` and `muscle.setIgnoreActivationDynamics(state,true)` does not seem to work as expected, as after reinitializing the state and querying the number of state variables they are not reduced. Using `muscle.set_ignore_tendon_compliance(true)` and `muscle.set_ignore_activation_dynamics(true)` has the desired effect after reinitializing the state and querying the number of state variables.
- In the API for the Equilibrium model https://simtk.org/api_docs/opensim/api_docs/classOpenSim_1_1Millard2012EquilibriumMuscle.html there is actually no mention of the methods: `setIgnoreTendonCompliance`, `setIgnoreActivationDynamics`, `set_ignore_tendon_compliance`, `set_ignore_activation_dynamics`... there is however `setMuscleConfiguration` which lets you edit the tendon compliance and activation dynamics flags. Interestingly, calling `methodsview(muscle)` in Matlab lists the methods: `setIgnoreTendonCompliance`, `setIgnoreActivationDynamics`, `set_ignore_tendon_compliance`, `set_ignore_activation_dynamics`

@nickbianco @gurchiek @carmichaelong

**Comment by nickbianco** [comment]
Based on [this Muscle virtual method override](https://github.com/opensim-org/opensim-core/blob/68b37e1d2b327cdb7629f910d614ce45193d7272/OpenSim/Simulation/Model/Muscle.cpp#L233), the following code should work as expected:

```matlab
muscle.setIgnoreTendonCompliance(state, true);
muscle.setIgnoreActivationDynamics(state, true);

 % Then, you need to make this extra call on the Model:
model.setPropertiesFromState(state);
```

**Comment by nicos1993** [comment]
Added pennation angle to the relevant confluence page.

**Comment by nickbianco** [comment]
I've created a PR for the small changes we want to make for the lab. @nicos1993 and @gurchiek, feel free to leave any feedback on other changes based on your testing.

**Comment by nicos1993** [comment]
Setting: `muscle.set_ignore_tendon_compliance(true);` and `muscle.set_ignore_activation_dynamics(true);` **_does not_** appear to then necessity the usage of `muscle.computeEquilibrium(state);`
The results I obtained were identical between circumstances.
Further note, these results were based on extracting the necessary multipliers.

**Comment by nickbianco** [comment]
Awesome. Now we need to double check if this is true or not for the method that @gurchiek used.

**Comment by nicos1993** [comment]
Comment: Add note about why we need reserve/residual moments to the confluence page.
I'm thinking that a note could be added at the end of Part 3, something like this:
_Note I: For certain degrees-of-freedom, depending on the motion of interest and muscles included in your model, it will be necessary to include reserve actuators. A reserve actuator serves to contribute towards a given joint moment when the muscles spanning that joint are not able to generate the necessary moment alone. The reserve actuators should also be minimized within the cost function, with a large weighting to prevent their usage. For this lab they are **not required**._
_Note II: The inverse dynamics analysis performed in Step 2 had dynamic inconsistencies in the form of residual forces and moments at the pelvis (e.g., pelvis_rotation_moment and pelvis_ty_force).  There may also be circumstances in which actuators for the residuals at the pelvis must be included due to dynamic inconsistencies.  For instance, when performing a tracking simulation using OpenSim Moco the forces/moments from the residual actuators should be minimal (preferably null) from a dynamic consistency standpoint. However, since static optimization relies on solving each frame independently it is not necessary to include reserve actuators.  The best practice in this scenario would involve determining the generalized forces for the motion of interest with limited/null residuals by performing, and then perform static optimization to solve the muscle activations - in doing so the muscle activations/forces determined are for a dynamically consistent motion. For this lab continue with the inverse dynamics results already obtained._

**Comment by nickbianco** [comment]
I think Note 1 is good, although I don't think you need the last sentence. Students might find it helpful to add in reserves while solving completing the lab.

I think Note 2 has a bit too much detail. I would leave out the Moco comparison, students won't fully grasp that one yet. I think it would be fine to just say something to the effect of "the inverse dynamics solution has dynamic inconsistencies, but it's fine to ignore them/add residuals for the purposes of this lab". Lab 3 will give them the tools to understand and reduce residuals when they really need to.

**Comment by nicos1993** [comment]
Thanks Nick! The suggestion for Note 2 is very useful. I will implement both of those in the confluence page!
