### ISSUE TITLE
Undefined reference in libosimCommon.so errors on linux

### ISSUE THREAD

**Issue by aclouthier** [opensim-org/opensim-core#3480]
I'm trying to build the code on a linux system; however, I get a bunch of these errors when trying to build the code:

[ 16%] Linking CXX executable ../../../testComponentInterface
../../../libosimCommon.so: error: undefined reference to '__libc_single_threaded'
../../../libosimCommon.so: error: undefined reference to 'std::__throw_bad_array_new_length()'
collect2: error: ld returned 1 exit status
make[2]: *** [OpenSim/Common/Test/CMakeFiles/testComponentInterface.dir/build.make:97: testComponentInterface] Error 1
make[1]: *** [CMakeFiles/Makefile2:2877: OpenSim/Common/Test/CMakeFiles/testComponentInterface.dir/all] Error 2
[ 16%] Linking CXX executable ../../../testSTOFileAdapter
../../../libosimCommon.so: error: undefined reference to '__libc_single_threaded'
../../../libosimCommon.so: error: undefined reference to 'std::__throw_bad_array_new_length()'
collect2: error: ld returned 1 exit status
make[2]: *** [OpenSim/Common/Test/CMakeFiles/testSTOFileAdapter.dir/build.make:97: testSTOFileAdapter] Error 1
make[1]: *** [CMakeFiles/Makefile2:2850: OpenSim/Common/Test/CMakeFiles/testSTOFileAdapter.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

There are a couple of things that I can think of that could be potentially causing issues
- It's actually opensim-jam that I'm trying to build (https://github.com/opensim-jam-org/opensim-core). I did successfully build this on a different linux computer though.
- I'm building it under my account on a computing cluster.
- I'm using swig 4.0.1 because that is the newest version available on the cluster.
- I copied spdlog from an installation on a different linux computer because I was having issues getting it to install through the superbuild.

If anyone has any insight as to what the problem might be that would be much appreciated!

**Comment by aymanhab** [comment]
@aclouthier while using swig 4.0.1 is problematic I don't think it's the problem here since it doesn't come into play until you build the bindings. Copying spdlog is likely the culprit here if it is linked against some library on one machine and a different version of the same library is available on the cluster which is rather common.  I'd try to build opensim-core main branch first on the cluster and then go back to troubleshoot the issue as opensim-jam has been forked a couple years ago and it's hard to keep track of how up-to-date with opensim-core  it has been kept.

**Comment by aclouthier** [comment]
I got spdlog to install and that did seem to be the issue. Now I think I'm at the swig version issue so I'll see if I can do anything about that.

Thanks for the help!
