### ISSUE TITLE
Packages not available for Google colab Conda install 

### ISSUE THREAD

**Issue by alexsalguero** [opensim-org/opensim-core#3538]
conda install -c opensim-org opensim — this works fine

Ran the following code in colab:
!conda install -c opensim-org opensim-moco

error:
 Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - opensim-moco

Current channels:

  - https://conda.anaconda.org/opensim-org/linux-64
  - https://conda.anaconda.org/opensim-org/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org/

and use the search bar at the top of the page.

I’m just starting out with opensim any recommendations to books, links, maybe even math prerequisites would be greatly appreciated. I’m trying to specialize in biomechanics & hopefully get as good as you guys. Starting college next year. I appreciate the help.

**Comment by aymanhab** [comment]
Thanks for reaching out but the conda packages for linux do not have moco variant (as reported correctly by conda) due to the complexity of building the whole stack of libraries from sources (some of them use source versions that go back years before the currently available compilers). We'll upgrade to a more recent version of these libraries to make these packages available, in the meantime you can use the opensim-moco package locally on windows machines.
