### ISSUE TITLE
Cannot run forward kinematics in python. 

### ISSUE THREAD

**Issue by LucosidE** [opensim-org/opensim-core#3543]
Hello, 

I am trying to simulate an IMU attached to a model using python bindings. 
However, I cannot figure out how to set the acceleration at a joint. 

Here is my simple 1 DOF model 
```
# Import opensim 
import opensim as osim
# Define global model where the arm lives.
arm = osim.Model()
# Add single rigid link 
humerus = osim.Body("humerus",
                    1.0,
                    osim.Vec3(0, -0.5, 0),
                    osim.Inertia(0, 0, 0))
# Connect the link with a simple pin joint 
shoulder = osim.PinJoint("shoulder",
                         arm.getGround(), # PhysicalFrame
                         osim.Vec3(0, 1, 0),
                         osim.Vec3(0, 0, 0),
                         humerus, # PhysicalFrame
                         osim.Vec3(0, 0, 0),
                         osim.Vec3(0, 0, 0))

# Build model with components created above.
arm.addBody(humerus)
arm.addJoint(shoulder)

# Create a frame to represent the IMU 
imu_frame_offset = osim.PhysicalOffsetFrame("imu_frame_offset", humerus, osim.Transform())
imu_frame_offset.set_translation(osim.Vec3(1, 0.0, 0.0))  # Set the translation of the IMU relative to the body origin
imu_frame_offset.set_orientation(osim.Vec3(0, 0, 0))  # Set the translation of the IMU relative to the body origin
humerus.addComponent(imu_frame_offset)

# Initialize the system 
state = arm.initSystem()
```

Now I can set the joint position and velocity and run forward kinematics as follows:
```
shoulder.getCoordinate().setValue(state, np.pi/4)
shoulder.getCoordinate().setSpeedValue(state, np.pi/4)

arm.realizeAcceleration(state)
```

Finally I can get the spacial acceleration in ground frame:
```
print(imu_frame_offset.getAccelerationInGround(state))
```

This produces expected values for the position and velocity of the joint, given that the acceleration of the joint is 0. 

I see there is no setAcceleration method for Coordinate. What is the proper way to set the acceleration of a joint and run forward kinematics?

The closest I found in the API is `Moco::Components::AccelerationMotion` which has a method `setUDot()` that appears to internally update `m_dvIndices` however it does not seem I can create an AccelerationMotion in python. 

Thank you in advance

**Comment by nickbianco** [comment]
Hi @LucosidE, if you wanted to directly set the acceleration, an approach using prescribed motion would be the right approach. `AccelerationMotion` is a class for prescribing accelerations, but it is reserved internally in Moco for solving direct collocation problems using implicit dynamics formulations (i.e., it is not exposed to Python). 

It would be better to use [`PositionMotion`](https://github.com/opensim-org/opensim-core/blob/3f1fe3804a85ba1bcc84e8e1b4544f9aeec02a21/OpenSim/Simulation/PositionMotion.h#L52), which sets the coordinate value, speed, and acceleration, and is available in Python. Adding this component will add "motion" forces to the model to compute the generalized forces needed to achieve the accelerations you prescribe.

**Comment by nickbianco** [comment]
> It was not clear to me how to use PositionMotion since it expects a differentiable function

You can use [`PositionMotion::createFromTable()`](https://github.com/opensim-org/opensim-core/blob/2eab3bb6f88b8cdb211ad663514c9125cfb4fa83/OpenSim/Simulation/PositionMotion.h#L84) to convert a TimeSeriesTable of data to a `PositionMotion` object using `GCVSplines`, which are differentiable. Here's an example that creates one [from a StatesTrajectory](https://github.com/opensim-org/opensim-core/blob/2eab3bb6f88b8cdb211ad663514c9125cfb4fa83/OpenSim/Moco/MocoInverse.cpp#L63C19-L63C33), but adding it to the model will work the same way. 

> For example, I don't understand how gravity is implemented in the Model.

If you're using the `IMU` component, then the `[0,9.80665,0]` at rest on ground is correct. [Gravitational acceleration is added to the acceleration reading from `IMU::calcAccelerometerSignal()`](https://github.com/opensim-org/opensim-core/blob/2eab3bb6f88b8cdb211ad663514c9125cfb4fa83/OpenSim/Simulation/OpenSense/IMU.h#L100) to mimic how a real IMU measures acceleration (i.e., relative to free fall). 

> Also what is the best process for getting additional information regarding the inner workings of opensim? Should I open a new issue for every question or just continue in this thread?

For questions like this it is preferred to submit a post to [the OpenSim user forum](https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB). GitHub issues are reserved for bugs in the codebase that need to be fixed. Therefore, I'm going to close this issue since it seems like you have what you need. Please post to the forum if you have any follow up questions. Or, if you indeed find a bug, please feel free to open a new issue for it.
