### ISSUE TITLE
An output with a dependsOn stage above Velocity causes SimTK::TimeStepper::initialize to throw an exception

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#356]
This hasn't come up yet because we don't have any tests that test integrating a system with outputs above Velocity that are wired up.

I don't understand the cause of the issue. I presume the TimeStepper has no reason to realize past Velocity when just initializing. I also presume that sherm has had to deal with a similar issue for Measures (how are measures handled during initialization for measures that depend on stages beyond Velocity?).

**Comment by chrisdembia** [comment]
I removed the milestone to make sure we discuss this at the next dev meeting.

**Comment by sherm1** [comment]
> how are measures handled during initialization for measures that depend on stages beyond Velocity?

Initialization is always tricky! Since Measures can depend on other Measures at initialization, and Measures can affect accelerations, realizing everything to Acceleration stage prior to Measure initialization can't work right.

Instead it works like this: when an Integrator's initialize() method gets called, it goes through [this code](https://github.com/simbody/simbody/blob/master/SimTKmath/Integrators/src/Integrator.cpp#L387) which realizes kinematics (that is, through Velocity stage) and then generates an initialization "event". That invokes the System's initialization event handler, which calls each Subsystem's initialization event handler, which invokes each Measure's initialize() method. Those are expected to do further realization of the Measures they depend on, based on the depends-on stage of those dependencies. [Here](https://github.com/simbody/simbody/blob/master/SimTKcommon/Simulation/include/SimTKcommon/internal/MeasureImplementation.h#L1225) is an example.

So during initialization it is allowed to do any amount of realization needed, but it is left up to the thing being initialized to do so. That is generally true in event handlers because it avoids expensive realizations if they aren't needed (admittedly that isn't an issue during initialization).

**Comment by chrisdembia** [comment]
Ah great. Thanks for that explanation.

**Comment by jenhicks** [comment]
@chrisdembia is this issue holding you up at the moment?

**Comment by chrisdembia** [comment]
This came up when I was working on the Delay component. Ian Stavness woud like that in OpenSim and has helped a bit with it. But right now, no one is working on the Delay component. We could probably hold off on this.

**Comment by jenhicks** [comment]
Thanks for clarifying @chrisdembia
