### ISSUE TITLE
ComponentList and ComponentListIterator are not exported.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#360]
Should they be? I'll do this quickly if we agree it should be done.

**Comment by chrisdembia** [comment]
By exported, I mean the OSIMCOMMON_API macro.

**Comment by aymanhab** [comment]
@chrisdembia I agree they need to be exposed, feel free to add the macro. 
I'd have to say though that this has no bearing on wrapping since swig uses its own macro and export the instantiated classes correctly as I've been using them from Java without any problems but for access from another c++ library the macro maybe needed.

**Comment by chrisdembia** [comment]
> I've been using them from Java without any problems

Good to know. Related to the performance question, do you ever need to use the iterator repeatedly?



> for access from another c++ library the macro maybe needed.

K I'll do this. Thanks for the input.

**Comment by aymanhab** [comment]
@chrisdembia I have to reuse the iterator to cycle through all components to generate DecorativeGeometry.  The amount of work done iterating is likely small relative to the processing we do but we need to profile to have a quantitative measure.  In essence, our separate lists inside a Model for Bodies, Forces, ... are caches that are more efficient but are also harder to maintain, particularly when we get to hierarchical models that are composed of other models.

**Comment by chrisdembia** [comment]
@aymanhab clarified that template classes don't get exported.
