### ISSUE TITLE
Question about exampleMocoTrack.py

### ISSUE THREAD

**Issue by Hippozhibos** [opensim-org/opensim-core#3643]
Hi:

I was trying to use Moco to estimate muscle activity without the measured GRF. So I run the exampleMocoTrack.py twice, 1st with the external loads "grf_walk.xml", 2nd with this line "modelProcessor.append(osim.ModOpAddExternalLoads("grf_walk.xml"))" toggled to comments. Then the muscle activity is quite the same, but in the visualization results the model without GRF did not walk normally, instread it's jumping at every step. I wonder what is the reason?
![image](https://github.com/opensim-org/opensim-core/assets/73272889/9fab2207-de4f-4e88-9fd4-13cde6c0b2de)
![image](https://github.com/opensim-org/opensim-core/assets/73272889/8d74a906-3992-4546-b595-6a0f4d0602a1)
![image](https://github.com/opensim-org/opensim-core/assets/73272889/4daefd20-9956-4f3f-a3fd-b8aae0c5bd65)

Another question is: I have a model built in OpenSim, and a .mot file which could be opened normally. But when I load it in Moco, it's coordinates would generate mistakes:  the parent frame and child frame of CustomJoints would be separated very large in GUI. I'm wondering why is that? 

Thanks for your time to read this, and looking forward to your reply!

**Comment by aymanhab** [comment]
@nickbianco Does this look like a bug on our side, or more of a documentation/explanation issue? If the latter then a forum post and pointer to documentation is more appropriate. Thank you

**Comment by nickbianco** [comment]
Hi @Hippozhibos, the model is "jumping" because the actuators at the pelvis are no longer strong enough to match the pelvis translations in the data with the external GRFs. I would not expect the kinematics or muscle activity to look similar without the GRFs. 

> the parent frame and child frame of CustomJoints would be separated very large in GUI.

This is likely a radians/degrees error, or some other modeling issue.

@aymanhab, indeed this is better suited to the forum. @Hippozhibos, if you have any further questions related to this post, please post them on either the OpenSim or Moco forum and we can assist you further there.
