### ISSUE TITLE
Important windows dependencies missing from readme

### ISSUE THREAD

**Issue by msdemers** [opensim-org/opensim-core#374]
The windows build -> Get Dependencies -> API Documentation lists Doxygen as the only dependency.  This is incorrect.  The doxygen build on windows also depends on:

1. Tex
2. LaTex
3. GhostScript

There are many distributions and options for obtaining any/all three, so some discussion about the best, recommended options is in order.

**Comment by jimmyDunne** [comment]
> API documentation (optional): Doxygen >= 1.8.6

Listed as optional. Tex, Latex and Ghostscript are also optional (if you want pretty equations). We have links to distributions here;

http://simtk-confluence.stanford.edu:8080/display/OpenSim/Guide+to+Building+Doxygen

Should we link them through the readme?

**Comment by msdemers** [comment]
Unfortunately, pretty equation printing is not behaving as "optional" right now. If you build the documentation, all four dependencies are required. Using a fresh window 8 install, with only doxygen and lacking the other 3, building the doxygen target yields build errors. Once Tex, LaTex, and Ghostcript are installed, the doxygen target builds just fine.

Therefore, Tex, LaTex, and GhostScript currently are dependencies and see as necessary as Doxygen. They should be on the github ReadMe list of dependencies. If they are  supposed to be a sub-option of the already optional documentation build, we'll have to find and squash some bugs.

**Comment by chrisdembia** [comment]
I'm strongly in favor of using mathjax instead: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/doc/Doxyfile.in#L1195

Let me know if people agree, and I'll make a PR. 

We'd have to add mathjax.js to the repository. It takes up about 2 mb if we remove all the fluff. https://github.com/mathjax/MathJax-docs/wiki/Guide%3A-reducing-size-of-a-mathjax-installation

**Comment by sherm1** [comment]
I have mixed feelings. MathJax does produce nicer equation rendering. But, it requires more infrastructure on the user's machine, increasing the chance that they won't see properly rendered equations. The manual steps required to reduce its footprint means we have a maintenance issue at our end -- we will have to upgrade it long after anyone remembers how to do that. The LaTeX alternative requires nothing at the user end since we ship a bunch of equation gifs.

**Comment by moorepants** [comment]
New lightweight math renderer that could be an alternative: https://github.com/Khan/KaTeX.

Can't you just point to the Mathjax CDN (i.e. don't include Mathjax in your source) and have a fall back to pre-rendered png's of math equations generated by LaTeX if the user doesn't have internet access?

We typically do this:

1. Try to render with MathJax cdn.
2. Render with local Mathjax if user has it installed.
3. Try to render with LaTeX if the user has it installed.
4. Finally, render with pure unicode if the user doesn't have any of the above.

I don't know what doxygen supports, so maybe this isn't easy.

**Comment by sherm1** [comment]
I like the idea of using MathJax cdn because it doesn't require maintenance on our part (doxygen handles formatting; MathJax handles bug fixes). The downside is that offline users will see no equations. The alternative we currently use is to have doxygen format with LaTeX in which case the resulting documentation is self contained. Doxygen runs as part of our build to produce the reference documentation; it never runs on the user's side so it can't re-render then. So we have a choice of having it generate MathJax or gifs via LaTeX. It would be ideal if we could generate MathJax, expect to use the cdn, and fall back to pre-generated gifs if not. Then we wouldn't have to attempt to maintain and deliver our own MathJax installation, but most users would get to see beautiful equations, and the rest wouldn't have to look at empty squares.

**Comment by msdemers** [comment]
uh oh.  same issue with the OS X build out of the box on fresh os image.  fixed with quick install of mactex.  luckily it's and easy install with homebrew ( brew cask install mactex ) 

I've never worked with MathJax so I won't weight in on that.

**Comment by chrisdembia** [comment]
@sherm1 I agree with you that that's the optimal solution. However, I don't know how to get doxygen to fall back on pre-generated gifs by detecting that there's no internet access, and creating doxygen for MathJax vs LaTeX is different: in the former case, the html files contain latex markup, while in the latter case, the html only contains links to images (I think).

Another option is to use CMake `file(DOWNLOAD ...)` to download MathJax during the cmake build process. That way, we don't maintain a copy of MathJax, and offline users can still see equations, since wherever we put the doxygen, we'll bring the MathJax installation along with it.

It's fairly reasonable to expect someone to have internet access when running CMake, since they had to get OpenSim from the internet. However, if they don't have internet when running CMake, we could fall back to using the CDN or to LaTeX. I guess we'd try to fall back to LaTeX, since the CDN also requires internet access.

**Comment by sherm1** [comment]
I would be happy to ignore the case where a CMake user doesn't have internet access! If we can easily download MathJax at the time we're creating our documentation so that it is self-contained after that, it seems like a good option.

**Comment by chrisdembia** [comment]
Thanks @sherm1. A few days ago I experimented with downloading MathJax via CMake. I ran into some problems and I don't know of a good solution. The ways of downloading MathJax are:

1. Downloading a zip from GitHub and then unzipping it. This isn't good because CMake does not provide an easy way to unzip a file in a cross-platform way.
2. Clone as a git repository. The MathJax git repository is 250 mb, which is larger than I like. However, CMake can reliably use git in a cross-platform way, I think. It's possible we can cause a shallow clone of the git repository, leading to a 50 mb download.

**Comment by chrisdembia** [comment]
My experimental branch is https://github.com/chrisdembia/opensim-core/tree/doxygen-mathjax

**Comment by sherm1** [comment]
Looks like `cmake -E tar` can unzip on all platforms: http://www.cmake.org/cmake/help/v3.1/manual/cmake.1.html

(haven't tried it though!)

**Comment by chrisdembia** [comment]
Oh!! Thank you!

**Comment by chrisdembia** [comment]
#565 addresses the original issue. However I'm not sure we should close this issue until we update confluence docs.
