### ISSUE TITLE
Menu is distorted at high resolution laptops

### ISSUE THREAD

**Issue by wbadry** [opensim-org/opensim-core#3788]
Hello,
I have a Dell XPS 13 with a resolution of `3456 x 2160` pixels.  Whenever I open the OpenSim software, I see distorted menus:
![image](https://github.com/opensim-org/opensim-core/assets/5664750/dcdc8bd3-552b-4fe5-9a2b-ad484cb1d189)

May I know the maximum resolution supported? Also, would that be considered in the upcoming versions?

Thank you so much

**Comment by aymanhab** [comment]
Thanks for reporting @wbadry The issue has been addressed on the user forum here
https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=13900&p=49341&start=0&view=
Since this is not an ongoing development issue, I'm closing. Please let us know on the user forum what works for you so other members of the community can benefit.
