### ISSUE TITLE
Nans in Moco initial guess

### ISSUE THREAD

**Issue by mrrezaie** [opensim-org/opensim-core#3866]
Hi, there are similar issues reported on the forum about the `Invalid_Number_Detected` error. I checked the initial guess file in [my case](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=18504&p=0&start=0&view=) and found that the last row of the slack variables are nans.
I wrote the initial guess to an sto file, manually modified the nans to zeros, and finally, I set the new initial guess from the adjusted file using `solver.setGuessFile` and it worked.

I wonder if you could fix the nans in the initial guess under the hood. Also, there is no way to set the slack variables programmatically; I was looking for some methods such as `getSlackNames`, `getNumSlacks`, `setSlack`, but there was none and I had to do it manually.

Thank you in advance.

**Comment by nickbianco** [comment]
@mrrezaie, thank you for posting this issue. Since the slack variables are not defined at all time points in a problem, we use NaNs to fill in the other time slots under the hood. But when returning solutions, the NaN values should get interpolated over. However, it seems like the NaNs are not getting interpolated over in some cases.

@AllisonJohn, we should make this one a high priority.

**Comment by AllisonJohn** [comment]
Note to self where I'll be looking for bugs:
https://github.com/opensim-org/opensim-core/blob/02a4b9803066d8561d09b8d1b9bd41933a1553da/OpenSim/Moco/MocoCasADiSolver/MocoCasADiSolver.cpp#L354
https://github.com/opensim-org/opensim-core/blob/02a4b9803066d8561d09b8d1b9bd41933a1553da/OpenSim/Moco/MocoCasADiSolver/CasOCTranscription.cpp#L633

**Comment by AllisonJohn** [comment]
These lines claim to remove NaNs but in fact they do not.
https://github.com/opensim-org/opensim-core/blob/02a4b9803066d8561d09b8d1b9bd41933a1553da/OpenSim/Moco/MocoTrajectory.cpp#L875-L880

**Comment by mrrezaie** [comment]
Hi, I think the `interpolate` function doesn't work as expected when the last element is NaN. Please see these examples:
```python
import opensim as osim
x = osim.Vector([0,1,2,3,4,5])

y1 = osim.Vector([0,0,0,0,float('nan'),0])
osim.interpolate(x,y1,x,True).to_numpy() # array([0., 0., 0., 0., 0., 0.])

y2 = osim.Vector([0,0,0,0,0,float('nan')]) # the last element is nan
osim.interpolate(x,y2,x,True).to_numpy() # array([ 0.,  0.,  0.,  0.,  0., nan])
```

**Comment by AllisonJohn** [comment]
Yes, thank you.
We found that this line should be deleted:
https://github.com/opensim-org/opensim-core/blob/02a4b9803066d8561d09b8d1b9bd41933a1553da/OpenSim/Common/CommonUtilities.cpp#L119
so that the result will be filled with non-NaN values even if the x is outside the bounds. This is fine because the piecewise function can extrapolate. I will add this and some more tests in a PR soon!
