### ISSUE TITLE
Can components of the same "level" have the same name?

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#387]
It is possible to have a Coordinate and Actuator of the same name. I think with the new component structure, this is still true. However, could I have a joint and Actuator of the same name? Previously, you could, but now I don't think so. What would I get if I called model.getComponent("duplicate_name")?

This potentially introduces a backwards-incompatibility in models.

**Comment by aseth1** [comment]
If you call `const Component& comp = getComponent("someName");` then there is no guarantee you will get the type you want.

There is also the type qualified `const C& comOfTypeC = getComponent<C>("someName");` access only the component of that type. Connectors are using the typed lookup to avoid the problem you describe. This is part of change #370.

**Comment by chrisdembia** [comment]
Perfect! When we merge #370, we can close this issue.

**Comment by aymanhab** [comment]
@chrisdembia A related issue that I'm dealing with in a test failure is that the connections depend on name to be established (connected_to_name Property) while there's no guarantee that all objects are named.This policy (un-named is not allowed) should be enforced. A name could be autogenerated if needed.

**Comment by chrisdembia** [comment]
> @chrisdembia A related issue that I'm dealing with in a test failure is that the connections depend on name to be established (connected_to_name Property) while there's no guarantee that all objects are named.This policy (un-named is not allowed) should be enforced. A name could be autogenerated if needed.

+1! I'll create a new issue for that.

**Comment by aseth1** [comment]
I like that idea of an auto generated name to facilitate connections, @aymanhab.  Are these for objects that were private to a component now being elevated to Components themselves? E.g. PathPoints and WrapObjects, etc...?

**Comment by aymanhab** [comment]
@aseth1 The issue I was dealing with was creating a Body (unnamed) since the Body now has a PhysicalFrame that's connected to it (to show its coordinateSystem)     but I see that happening more and more as we change Properties into Connections. PathPoints and WrapObjects are perfect examples since when they use connections they can't connect to unnamed Body or unnamed PhysicalFrame.

**Comment by aseth1** [comment]
@aymanhab how were they "connecting" to the correct Body without connectors if the name was "unknown"? I don't see how it used to work!

**Comment by aymanhab** [comment]
@aseth1 For the Frame part, there were no connections or even properties, the frames were implicit (show-all, hide-all in API-Visualizer or created on the fly by the GUI) other "future" connections are now properties that get wired when you call connectToModel. PathPoints and WrapObjects were never incorporated into the Components framework so they had their own kludges.

**Comment by aseth1** [comment]
@aymanhab I understand there were no connectors, but how were they obtaining the Body or whatever they needed in order to attach themselves. At some point they are given the thing they depend on or they get the thing. The Connector allows you to do both. You can satisfy the Connector with the thing or it will look up the thing according to the property (name) it has in hand. You have to make sure the connector is satisfied or has a valid name by the time connectToModel() is called.

**Comment by jimmyDunne** [comment]
If the combination of name and type are unique, you can have it
