### ISSUE TITLE
Kinematic Reconstruction Issue with OpenSense Framework

### ISSUE THREAD

**Issue by danielselmin** [opensim-org/opensim-core#3894]
I am using the OpenSense framework to reconstruct kinematics from IMU data acquired during walking. Due to inaccuracies during data acquisition or sensor drift, the reconstructed kinematics show the musculoskeletal model walking diagonally. Instead of moving forward, the model takes steps that also move the legs toward the left.

To correct this error, I attempted to rotate the rotation matrices of the sensors on the legs, trying to find the optimal angle that would minimize the adduction angle during walking, making the steps as straight as possible. However, I noticed that changing the rotation matrices of the sensors on the legs did not affect the kinematic reconstruction in any way. I then tried rotating the acceleration vector around the vertical axis, but this also had no impact on the kinematics.

Ultimately, I was able to correct the walking direction by rotating the rotation matrix of the pelvic sensor (which was set as the reference sensor). This solution gives me reasonably good results, but it does not allow me to correct the orientation of a single limb, only the reference sensor.

I am wondering how it is possible that rotating the rotation matrices and acceleration vectors does not affect the kinematic reconstruction. Is it possible to get more information on how the OpenSense framework processes IMU data and, if necessary, which adjustments (rotations) I should make to the collected data in order to correct the kinematics?

Thank you very much.

**Comment by aymanhab** [comment]
This seems more like a forum discussion topic rather than a development issue, as such I recommend posting to the user forum where lot more members of the community solve or work around IMU system specific issues. If an actual bug/issue is identified then you can re/open the issue and attach all the files necessary to reproduce. Thank you. User forum link is here just in case
https://simtk.org/plugins/phpBB/indexPhpbb.php?group_id=91&pluginname=phpBB
