### ISSUE TITLE
Models with massless bodies and muscles can not be visualized

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#429]
This maybe expected behavior now but version 3.2 allowed models with massless bodies and muscles  (e.g. WristModel.osim) to be loaded/used.  Trying to visualize this wrist model now (using the API visualizer & GUI) throws an exception trying to realize to Dynamics stage (in order to compute color).
We either need to recognize the situation and fix it or give a more meaningful specific message (more than SimTK Exception thrown at SmallMatrixMixed.h:87 Error detected by Simbody method lapackInverse(Mat<>): Matrix is singular or can't be inverted ....)

**Comment by aymanhab** [comment]
@jenhicks This issue keeps coming up with the model conversion test case I'm writing because many models used in earlier distributions (e.g. both_legs, wrist) have no mass properties and very likely many user models have the same issue. Do you see this worth supporting going forward?

**Comment by sherm1** [comment]
I think this could possibly be addressed in Simbody by deferring some Dynamics stage computations that depend on mass until they are asked for. I don't think the mass matrix needs to be inverted to calculate the forces that are needed for muscle visualization.

**Comment by aymanhab** [comment]
Thanks @sherm1 My main worry is that while model building from scratch (human, animal and toy models) users are likely to do kinematic models to begin with (e.g. the Jaw model from workshop) and when it all works they add mass properties and inertia. From what you said I'll take it that we can continue to support these models going forward.

**Comment by aseth1** [comment]
If the issue keeps coming up why isn't there a test case for it?
Why don't we begin with what is different between the 3.2 and current. Who or what is realizing to Dynamics now that wasn't before? `PathActuator::computePathColor()` is called when Dynamics is realized. This is unchanged from 3.2 AFAIK.

**Comment by sherm1** [comment]
Nothing has changed on the Simbody side, but I'm guessing the new component-generated geometry in OpenSim uses realize(Dynamics) to compute forces where the old muscle-aware visualization did it by querying the muscles. In any case I don't think there is any downside to deferring the mass-inverting computations to as late as possible. I filed a Simbody issue simbody/simbody#370 on the topic.

**Comment by aseth1** [comment]
I am just curious as to how things differ. `GeometryPath::generateDecorations()` in both master and 3.2 realize to Dynamics. This should have failed to draw in the Visualizer in 3.2 as well.

**Comment by sherm1** [comment]
Wild guess: these no-mass models would have failed in the API visualizer in 3.2 but succeeded in the GUI. Now they will fail in both places. Ayman will know the true answer!

**Comment by aseth1** [comment]
@sherm1 Deferring of the mass-matrix still seems good but isn't a robust solution for this problem. If I want to generate decorations that are related to derivative values, then I will need to evaluate to acceleration. There is nothing stopping a new Component to realize to Acceleration to compute derivatives and then draw.  In most cases you still want the Component to draw something (its Geometry) but ethereal attributes like color or direction may change with the derivative values. How do we: 1) not have `generateDecorations()` drive the realization stage for the purpose of visualization (this seems wrong to me) and, 2) have `generateDecorations` only draw what it can up to the current stage and thus avoid triggering these problems?

**Comment by sherm1** [comment]
I would argue that if visualization depends on acceleration but the model can't be used to calculate acceleration, then it is fine to issue an error message. As I understand the situation here, visualization depends only on forces, the model is capable of calculating forces, but we blow up anyway. That seems bad.

**Comment by aymanhab** [comment]
Thanks @sherm for explaining. Indeed the change to realize Dynamics dates back to 4/2013 but generateDecorations was not used for visualization in the GUI but now it does.

**Comment by aymanhab** [comment]
@aseth1 I agree that visualization should probably not change realization stage but I'm not sure if there's a way to enforce this.

**Comment by sherm1** [comment]
> I agree that visualization should probably not change realization stage

I don't think it is necessarily a bad thing. The alternative is to have the caller guarantee a certain realization level, in which case it must realize to the maximum needed level even if no one is using it. With OO visualization like we have now, only the lowest-level method knows the requirements. I think a good compromise is to have the caller guarantee a certain level of realization (say Stage::Velocity) and leave it up to the visualization code to realize if it needs more than that. The realization call could be surrounded by try/catch in the visualization code if there is a chance it will fail, with some fallback visualization scheme if it does.

**Comment by aymanhab** [comment]
@aseth1 On a related topic, if we decide down the road to use "connector" to decide how to color muscles, the color connector can be wired to either Activation, Force, FiberLength, ShorteningVelocity, ... etc. How's realization level decided in these cases. I'd assume these "outputs" are valid for specific realization stages.

**Comment by aseth1** [comment]
@sherm1 I don't believe it makes sense for the decoration generator to be driving the computation. If someone wants to pose and view a model they are working on why should dynamics be realized to obtain a color? The zero mass properties is one symptom of a more general problem. I may not have valid fiber length and tendon slack length properties when building a model. I am going to get a whole slew of exceptions (thanks to Millard's checks, for example) if the model is realized to dynamics just so it can be visualized. If the person is performing a forward simulation or some muscle level analysis  I think it is perfectly reasonable to throw exceptions. 

Since generate decorations has access to the state and the current stage it should only draw what it can up to the current stage. We can assume that the minimum stage for visualization is position so you only have to check if you have visualizations on velocity or higher. 

Wouldn't this solve the existing problem and the invalid muscle property problem if GeometryPath just drew its path (known at position stage) and then if and only if Dynamics (or higher) has been realized also update the color?

**Comment by sherm1** [comment]
> Wouldn't this solve the existing problem and the invalid muscle property problem if GeometryPath just drew its path (known at position stage) and then if and only if Dynamics (or higher) has been realized also update the color?

No, because the caller wouldn't know to what stage it should have realized. In this case the only reason to realize Dynamics is that the visualization code wants to use a Dynamics-stage quantity to colorize the muscles. The caller likely has no use for that quantity at all. To do it the way you're suggesting would work fine, but would result on muscles never being colorized during kinematic analyses; maybe that's fine but it seems like a downgrade.

On the other hand, you can certainly blame visualization code if it does something that blows up a study. Realizing beyond what the model can sustain is one way to do that, dividing by zero would be bad too! 

In general anyone who has const access to a State is allowed to realize it to whatever level they want. That is usually a good thing!

**Comment by aseth1** [comment]
@aymanhab can correct me if I am wrong, but there would be no loss of functionality for muscles since they are simply drawn as red (or whatever default color we choose) unless a forward simulation is invoked. I believe the GUI does that now - that is why muscles remain red during replay of IK. If the color value is meaningless (which it is without it being a muscle driven simulation) then I don't see any harm in the Stage being dictated by the Solver instead of the the decoration generator.

We might use something like this as a mechanism for controlling what is drawn and the quality of rendering during a simulation. If I run a forward simulation (forward solver) I get the system realized to acceleration each time step and can view ground reaction forces as rays (fast and cheap) but if the Study attaches a fancy Reporter that realizes to Report it could do more calculations to render pressure distributions of the foot contact elements. We would encourage fancy/costly decoration generation to be performed only if at the Report stage. As we have it now, a component itself forces a realization to Report to draw itself no matter how involved it is to generate.

**Comment by sherm1** [comment]
> I don't see any harm in the Stage being dictated by the Solver instead of the the decoration generator.

That's not even possible, assuming that you pass a State to the decoration generator.

> If I run a forward simulation (forward solver) I get the system realized to acceleration each time step

That is not necessarily the case when a reporter is invoked. Simbody only guarantees that kinematics are realized because you don't know if the state that you are reporting is one at which accelerations were needed (interpolation can have this effect as can other things). When people want to display reaction forces or accelerations, the reporter realizes the State to Acceleration stage. That cannot be done efficiently from the solver because it has no way of knowing whether those will be needed.

**Comment by aymanhab** [comment]
Regardless of how we decide to implement this change I'd insist that generateDecorations never throws an exception. The method should execute and return as fast as possible and a try/catch around any call would be expensive. I do think that based on the context in the GUI we'd know if we want to color by activation or not and we should pass that to the method as an option.

**Comment by jenhicks** [comment]
Closed per https://github.com/simbody/simbody/pull/435
