### ISSUE TITLE
Signbit issue

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-core#441]
@sherm1 or @aymanhab Can you elaborate?

**Comment by chrisdembia** [comment]
Does this have to do with the version of visual studio?

**Comment by sherm1** [comment]
Visual Studio 2010 didn't provide C++ standard methods [std::signbit()](http://en.cppreference.com/w/cpp/numeric/math/signbit). Simbody 3.3 (used in OpenSim 3.2) provided implementations of these missing methods. In Visual Studio 2013 Microsoft added the missing implementations, so the Simbody 3.3 implementations conflict with the library and prevent compiling with 2013. Later versions of Simbody added an `#ifdef` so that the missing methods are only added for Visual Studio 2010 or earlier. But the Simbody 3.3 source provided with OpenSim 3.2 doesn't have that `#ifdef` and hence won't build with VS 2013.

The best fix is probably to add the missing `#ifdef` to the Simbody 3.3. source distributed with OpenSim 3.2; a more dangerous alternative would be to upgrade to a later version of Simbody.

**Comment by jenhicks** [comment]
Thanks @sherm1. We discussed upgrading to Simbody 3.5.1 for OpenSim 3.2.1. Is this too dangerous?

**Comment by aymanhab** [comment]
We'll need input from Sherm on that, if nothing there affects opensim functionality and/or performance I'd lean toward not upgrading.

**Comment by sherm1** [comment]
I think we're mixing two different things: the signbit issue was just a patch to allow people to compile OpenSim 3.2 using Visual Studio 2013. I think we should stick to the original Simbody 3.3 in that case.

For OpenSim 3.2.1 we already decided to upgrade to Simbody 3.6 for a variety of good reasons; there is no signbit problem there.

**Comment by aymanhab** [comment]
This can be closed since we already build with VS2013

**Comment by jenhicks** [comment]
OK ... closing
