### ISSUE TITLE
master branch build failing on Travis (and splitting up python wrapping)

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#455]
Both gcc and clang appear to be failing with internal compiler errors. That's quite a trick since they are different compilers! The build is succeeding on AppVeyor (Windows).

Unless anyone is working on this I will try to reproduce it on my Ubuntu VM.

/cc @aseth1 @aymanhab @chrisdembia @klshrinidhi

**Comment by chrisdembia** [comment]
> Unless anyone is working on this I will try to reproduce it on my Ubuntu VM.

@sherm1 I've spent a lot of time down this road with almost no success. I think it's because the VM is running out of memory. After multiple days of trying this locally and giving up and getting motivated again, I haven't figured it out. It'd be awesome if you do. I have never had this failure locally. I'm happy to talk to avoid replicating efforts. I tried limiting the memory available to GCC to try to replicate the issue (http://unix.stackexchange.com/questions/44985/limit-memory-usage-for-a-single-linux-process). but wasn't successful.

**Comment by chrisdembia** [comment]
@sherm1 check out https://github.com/travis-ci/travis-ci/issues/1972

**Comment by chrisdembia** [comment]
Also see #132, #140

**Comment by chrisdembia** [comment]
The reason I think the VM is running out of memory is because of posts like this: http://stackoverflow.com/questions/13103396/c11-g-4-7-internal-compiler-error.

You could also try to instrument the build somehow to print memory usage throughout the build process to see if the out-of-memory hypothesis is true.

**Comment by chrisdembia** [comment]
Sorry to keep spamming everyone, but perhaps you could limit your VM to 3 gb of RAM (or less) to reproduce: ["On the Linux platform, builds have 3 GB of memory available"](http://docs.travis-ci.com/user/ci-environment/#The-Build-Machine).

Also, I don't understand why this happens with OpenSim and never with Simbody.

**Comment by sherm1** [comment]
I was able to reproduce this on my VM by enabling Python wrapping. The resulting SWIG-generated file was 500,000 lines long. I used `top` to watch clang 3.4 compile this monster. I saw it creep to over 3.5GB of virtual memory and then it crashed. I'm trying it in Debug now -- I'm thinking that one possibility would be to disable optimization on this file; I don't think there would be a noticeable performance impact.

**Comment by chrisdembia** [comment]
Great idea! GCC crashes as well though; on travis, the gcc build does not build either python or java wrapping.

**Comment by sherm1** [comment]
> GCC crashes as well though; on travis, the gcc build does not build either python or java wrapping.

Oh well. So much for that theory! I'll try the Debug build anyway with clang.

**Comment by chrisdembia** [comment]
No I think you're right. We removed the wrapping from gcc builds because it allowed the build to complete at all (with wrapping enabled, gcc would *always* crash; now it crashes only sometimes).

**Comment by sherm1** [comment]
I was able to build python wrapping in Debug. The virtual memory maxed at just over 2GB and compilation time was very fast. With optimization it got to at least 3.5GB and took a very long time. So suppressing optimization on this file might help get wrapping through clang.

2GB is still a lot of memory for a compile, though! I wonder if SWIG has an option to generate a set of smaller files rather than jam everything into one?

**Comment by chrisdembia** [comment]
> 2GB is still a lot of memory for a compile, though! I wonder if SWIG has an option to generate a set of smaller files rather than jam everything into one?

As far as I know, you must manually build multiple modules. I've spent time doing this for python, creating a module for each of the 5 opensim libraries. I never finished, but I shared the branch with Ayman at one point.

**Comment by sherm1** [comment]
Built fine on my VM with gcc 4.8.2 (no wrapping). I might have missed it but I didn't see any individual compile that used more than 0.8GB of virtual memory.

**Comment by chrisdembia** [comment]
Here's my attempt to split python wrapping into multiple modules. https://github.com/opensim-org/opensim-core/tree/python-wrapping-multiple-modules

**Comment by chrisdembia** [comment]
I just tested that branch...it works! So if we want to split opensim wrapping into multiple modules it's possible but requires some manual effort. I've pushed my branch to the opensim-org repo as well.

**Comment by sherm1** [comment]
gcc with wrapping worked with optimization on my VM. Virtual memory got close to 3GB but didn't go as high as clang did.

**Comment by sherm1** [comment]
I restarted failed builds on master and now both gcc (no wrapping) and clang (wrapping) completed successfully. Something is flaky with Travis' virtual machines. I suppose there could be some kind of combined limit we're hitting by coincident timing of simultaneous compiles. It's annoying though because we aren't doing anything wrong.

**Comment by sherm1** [comment]
> So if we want to split opensim wrapping into multiple modules it's possible but requires some manual effort. 

It seems bad to split it to require multiple python import statements (assuming users would see that). It would be better if we could split the swig-generated .cxx files and then link them together to create a single .pyd. We probably ought to do something though since these files are only going to get bigger over time.

Makes me wonder if gcc and clang have memory leaks!

**Comment by chrisdembia** [comment]
> It seems bad to split it to require multiple python import statements (assuming users would see that). It would be better if we could split the swig-generated .cxx files and then link them together to create a single .pyd. We probably ought to do something though since these files are only going to get bigger over time.

It's very easy to hide the multiple libraries from the user; they would still only need `import opensim`.

**Comment by aymanhab** [comment]
Thanks @sherm1 and @chrisdembia for the investigation. My thoughts:
- For "scaling" in the future, I agree we need a better arrangement for wrapping. Some suggestions:
+ If we're going to split then I'd split off the Simbody part since it is self contained, live in a different namespace and can be useful on its own if we put effort on them rather than split across OpenSim libraries since the lines there are rather arbitrary (e.g. simulation vs. actuators) Chris's branch is a great place to start.
+ The size of the source .cxx files generated by swig is very large indeed but the Java one is about half the size of python, is that due to documentation, error-checking, what else? May not even be a factor in the memory footprint needed for compilation.
- I would lean to disable optimizations since these are all thin layer of one line calls to C++, so there's nothing to optimize most of the time.
- It would be good to revisit what we expose since this maybe a sign of a more generic problem of way too many classes that serve very narrow functionality and some are/will-be obsoleted but that discussion doesn't belong here.

**Comment by chrisdembia** [comment]
Good idea about splitting off Simbody.

**Comment by sherm1** [comment]
> Good idea about splitting off Simbody

I like it too. It would be nice to have at least the beginnings of a python/java interface to the Simbody API that would be useful both for OpenSim and independently. That seems like a much more maintainable way to construct the OpenSim/Simbody stack.

**Comment by chrisdembia** [comment]
It'd be nice if it lived with Simbody. I think @peastman has experience with getting two modules like that to work together.

**Comment by chrisdembia** [comment]
In #487, I might have reduced the chance of a clang failure. I think part of the issue was that the java wrapping and the python wrapping were being compiled at the same time. WIth #487, I force the two wrappers to be compiled one at a time.
