### ISSUE TITLE
Current Visualization Design may lead to numerous Geometry and Appearance classes

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#482]
Currently Components are offloading their visualization to Geometry and using Appearance to control how it is visualized. For example, Components can have lines drawn via a LineGeomtery component. A LineAppearance controls its thickness when drawn in a Visualizer. Similarly, a Frame (component) has a FrameGeometry but is has `display_radius` to control the thickness of the axes. Changing a property of Component is interpreted as a change in its behavior so changing axis thickness will force a recreation of the system. It seems we would then want a FrameAppearance. I think this becomes the case for Point (to exposed radius of the sphere) and AnalyticalGeomtery (to describe the number of facets used to visualize smooth analytical shapes). 

I really like the idea of having an Appearance that only changes the visualization and not the physics of the model. The current approach is coming at the expense of duplicate code and multiple (practically empty) classes (e.g. to expose a property).

Would it be easier/cleaner to then to have a new AppearanceProperty of an Object/Component? The purpose of Appearance is to expose properties that can affect the appearance of a Component and not its physics. The Appearance classes only contain properties (as far as I can tell) and that makes me question their existence (i.e. they have no actions). Unlike regular properties, AppearanceProperties could have their values changed and they would not mark the Object as not being up-to-date (thus would not trigger setting up from properties, connecting, etc.. to re-initSystem). That is my main worry for including things that only affect visualization as properties. We must have a clear separation between physics (properties) and visuals (appearance) and the latter should have absolutely no effect on the former. For example Line would have `thickness` as an AppearanceProperty.

Perhaps another way of controlling appearance without polluting the modeling/physics API with Appearances or AppearanceProperties is for the Visualizer to employ a Visitor to apply appearances based on the Component (and its Geometry) that are encountered. That is, the Visualizer maintains a mask to apply to individual Components or by types (e.g. draw WrapObjects as wireframe  or make PhysicalFrame axes green), 

A combination of the two may be best. Where Components have default AppearanceProperties defined by the modeler but the Visualizer/GUI is free to override based on direct user input. Neither of which affects the computations of the system.

**Comment by sherm1** [comment]
I wonder if we should call these specified-by-the-model properties `DefaultAppearance` or something like that. I think that's what they are and if so they are just kind of a hint by the modeler as to how they think the user will want to view things. But the actual appearance might be quite different after the user takes control in the GUI.

With that distinction I wouldn't care about separating the default visualization properties from the physical properties because the defaults wouldn't change much. This would be similar to how we deal with changing names of things -- those don't affect the physics but we would regenerate the system anyway. It doesn't matter because we expect those kinds of changes to be rare.
