### ISSUE TITLE
A Frame should draw itself without the help of FrameGeometry.

### ISSUE THREAD

**Issue by aseth1** [opensim-org/opensim-core#542]
Frame and FrameGeometry relationship adds unnecessary confusion and occupies a lot of space in XML.

``` XML
<Body name="ball">
    <!--List of Geometry that is attached to this Model Component.-->
    <geometry>
        <FrameGeometry name="frame_geometry">
            <!--List of connectors (structural dependencies) that this component has.-->
            <connectors>
                <Connector_Frame_ name="frame">
                    <!--Name of the component this Connector should be connected to.-->
                    <connected_to_name>ball</connected_to_name>
                </Connector_Frame_>
            </connectors>
            <!--Scale factors in X, Y, Z directions respectively.-->
            <scale_factors>0.2 0.2 0.2</scale_factors>
            <!--Default appearance for this Geometry-->
            <Appearance>
                <!--The representation (0:Hidden, 1:Points, 2:Wire 3:Shaded) used to display the object. -->
                <representation>0</representation>
            </Appearance>
            <!--The radius of the arrow-shaft used to display the frame.-->
            <display_radius>0.004</display_radius>
        </FrameGeometry>
        <Mesh name="ball_geom_1">
            <!--List of connectors (structural dependencies) that this component has.-->
            <connectors>
                <Connector_Frame_ name="frame">
                    <!--Name of the component this Connector should be connected to.-->
                    <connected_to_name>ball</connected_to_name>
                </Connector_Frame_>
            </connectors>
            <!--Scale factors in X, Y, Z directions respectively.-->
            <scale_factors>1 1 1</scale_factors>
            <!--Name of geometry file.-->
            <mesh_file>sphere.vtp</mesh_file>
        </Mesh>
    </geometry>
    <!--The mass of the body (kg)-->
    <mass>1</mass>
    <!--The location (Vec3) of the mass center in the body frame.-->
    <mass_center>0 0 0</mass_center>
    <!--The elements of the inertia tensor (Vec6) as [Ixx Iyy Izz Ixy Ixz Iyz] measured about the mass_center and not the body origin.-->
    <inertia>0.00025 0.00025 0.00025 0 0 0</inertia>
</Body>
```

A Frame has FrameGeometry. A FrameGeometry is Geometry. Geometry requires a connector to a Frame. That Frame is the frame that the FrameGeometry is supposed to represent - it is never supposed to be anything else - this is confusing.  Even worse,  the properties are exposed/editable! So one can make the FrameGeometry of the ball above appear on ground by editing the connector to connect to `ground`. Why is this possible??

Frame should implement `generateDecorations` to draw itself and have some DefaultAppearance attributes that can be overriden by the user such as .. axes length, thickness, color and not use scale factors IMHO.

**Comment by aymanhab** [comment]
@aseth Indeed Frame can use FrameGeometry utilizing generateDecorations mechanism rather than the Properties mechanism, what we lose is the flexibility to control if/how an individual frame is displayed (they are all either shown or get hidden, at same size for example) which is a major disadvantage most of the time. Is this worth the tradeoff in XML is something I welcome feedback on. The functionality has been there in ad-hoc way in the current custom GUI.

My latest rearrangement of Appearance classes moves the size properties to the corresponding Appearance separate from the scale factors as you suggested indeed.

The nature of connectors is that they don't have a default value so I can't drop the Connector_Frame from XML, if there's a general solution I'd love to hear it. That's true though for all/any-other geometry that users can pick wrong frame as much as they can pick wrong body to apply force or for a PathPoint attachment, or pick same body for joitns etc.

**Comment by sherm1** [comment]
> That's true though for all/any-other geometry that users can pick wrong frame as much as they can pick wrong body to apply force or for a PathPoint attachment, or pick same body for joints etc.

It makes sense to me that a user can pick the "wrong" frame for geometry when "wrong" is only a matter of opinion (like where should the force have been applied). But if it is clear from context what the right frame is, it would be a design bug IMO if the user could change it.
