### ISSUE TITLE
Non-virtual interface naming; update CONTRIBUTING.md

### ISSUE THREAD

**Issue by sherm1** [opensim-org/opensim-core#648]
Per our discussion the other day I tried modifying a real non-virtual interface class in Simbody that was using the trailing `Virtual` convention to one using the leading `implement` convention. I posted it in a [gist](https://gist.github.com/sherm1/01adcdbb93105f3a7fea) with two files showing the old and new conventions. Please check it out and comment here (don't use the gist comment section because they don't handle notifications properly).

/cc @chrisdembia @klshrinidhi @aymanhab @aseth1 @tkuchida  @msdemers @jenhicks

**Comment by sherm1** [comment]
The change in capitalization is bothering me. The public method is `doSomething()` but the protected one is `implementDoSomething()`, as though the original method were named `DoSomething()` which by our convention looks more like a class name. Does that bother anyone else?

**Comment by tkuchida** [comment]
> Does that bother anyone else?

It's been keeping me awake at night. I also don't like the inconsistency between `upd` and `implement`---why not `impl`? :sheep:

**Comment by aymanhab** [comment]
It's bothering me as well. The older version feels cleaner somehow.

**Comment by chrisdembia** [comment]
@aymanhab what do you mean by the older version?

**Comment by chrisdembia** [comment]
> why not impl?

I don't like `impl` because it can be confused with PIMPL's "impl", and the `l` could be mistaken for a  `1` in this context.

**Comment by sherm1** [comment]
> I also don't like the inconsistency between upd and implement---why not impl.

I picked `upd` a long time ago to extend the conventional set of "accessor" names which were either `get` or `set` which were already 3-letter verbs. Accessors were considered an annoyance in C++ (and still are I think) so the goal is usually to get the over with as fast as possible. At the time I thought `update` was an excessively long prefix for such a trivial and annoying method. I think I still agree with that assessment because accessors are used so often in our code.

OTOH, the virtual methods in the non-public interface are in general much more significant than accessors, and there is no particular reason to abbreviate them since people aren't every supposed to call them directly. And the general rule is to spell things out rather than abbreviate unless there is a good reason, so I don't think we should abbreviate just to match the `upd` abomination.

**Comment by msdemers** [comment]
@sherm1 I'm a fan of StudyX.h and using the implementMethodInPublicInterface() naming convention. The capitalization mismatch doesn't bother me at all, but I can understand how it might be bothersome to other people.

My only gripe with using the "Virtual" term in the name is that I can already see that it's Virtual from the method signature. 

Virtual methodInPublicInterfaceVirtual() wastes space with the extra Virtual suffix, but 
Virtual implementMethodInPublicInterface() makes it clear (to me) that I should override this method to create the specific implementation and change the behavior of methodInPublicInterface(), thus the extra text is justifiable to me.  Just a preference, not a strong feeling from my perspective.

**Comment by sherm1** [comment]
@msdemers, I like your argument. One possible fix for the capitalization problem (if it is really a problem) would be `implement_methodInPublicInterface()`. But if we did that we ought to use `extend_methodInPublicInterface()` too.

**Comment by aymanhab** [comment]
@chrisdembia I mean that Study.h looked cleaner the StudyX.h.but realistically this is all hypothetical until you try to use Study?.h  and see if the errors/warning you get make sense to the user of it.

**Comment by chrisdembia** [comment]
Related #640

**Comment by klshrinidhi** [comment]
Until today, I didn't have any preference on this. Now I strongly prefer to let the programmer/designer(s) decide what is appropriate and not turn (our) personal preferences into public conventions that programmers have follow in order to contribute code.  After a certain point, conventions start to look like restrictions to programmers.

**Comment by aseth1** [comment]
> I strongly prefer to let the programmer/designer(s) decide what is appropriate and not turn (our) personal preferences into public conventions that programmers have follow in order to contribute code. After a certain point, conventions start to look like restrictions to programmers

The difference is that WE are implementing the interface not some arbitrary programmers. I want a convention that is consistent so I don't have to think about it. The fact that we have different terms peppered around our code (that we've written) means that this isn't a "freedom" that we the developers know what to do with. As much as the naming as we can establish, frees the developer to focus on the functionality/implementation in my opinion.

**Comment by klshrinidhi** [comment]
I am including me as developers. 

I don't think this convention is a good idea. I think of this more as a restriction than a convention.  Developers don't need freeing. They (including me) don't think of this as a burden. They should be able to decide what to name their functions and variables as long as the documentation is clear.

In general, having worked with other C++ libraries, I feel that beyond a set of conventions that are publicly available (Google style guide, Boost style guide etc), developers need/deserve complete freedom in how they write code and as project maintainers, we need to able to read their code the way they are written, not the way we them to write.

If other publicly available conventions have some thing in place for this case, we should just adopt that. Otherwise, we should leave it open.

This naming concerns only developers deriving from the class and he/she should read the documentation and understand the class before deriving it. There will be compiler error if the function is not implemented and the documentation should provide details on what is expected from the derived class.

**Comment by sherm1** [comment]
Every well-managed organization has a set of coding conventions. It doesn't matter nearly as much exactly what they are as that they are followed to produce a consistent code base and to avoid repeated decision making about trivial things (like capitalization or indenting). I think it makes sense to argue about what exactly the conventions should be (as we did recently for "implement" vs. "extend") but I don't think it makes sense to say there shouldn't be any conventions.

**Comment by klshrinidhi** [comment]
I agree there should be conventions and I understand implications of not having *any* conventions. That would be really bad. But we should not go beyond what there are in publicly available conventions. 
Decisions on what to name the functions should be left to the developer. You can have conventions for your code but should not expect others to follow your preferences if those conventions are not part of publicly available conventions.
Personally, as a developer, I think I ought to be able to read other code that don't follow my preferences/conventions as long as they comply to basic set of conventions of the project, which should really be basic.

**Comment by sherm1** [comment]
OpenSim's conventions are publicly available, just like Google's and OSRF's and many others. And our conventions are considerably *less* prescriptive than Google's -- just as an example as you know Google prohibits use of C++ exceptions. We actually went to a lot of trouble not to be too restrictive -- for example we don't have strict rules about placement of curly braces because we felt that indenting is the important part of conveying structure to other programmers.

Currently our conventions do include naming conventions for visible names and local variables also. Clearly the local variables are less important; we could discuss with the team whether our conventions should be looser in that area.

**Comment by klshrinidhi** [comment]
Sorry. I know OpenSim conventions are publicly available. When I said "publicly available conventions", I intended to refer to other conventions that are being used by more than one project -- Google, Boost, and few others.

**Comment by aseth1** [comment]
We should adopt conventions in so far they are helpful, result in more clarity and reduce potential for mistakes. I think most are willing to sacrifice some freedom for those benefits. For me a naming tip like "implement" or "extend" is helpful and it avoids having to come up with another name, which I like.
@klshrinidhi can you help me understand what is restrictive about introducing this convention for OpenSim. It is very possible that I am being short-sighted.

**Comment by klshrinidhi** [comment]
I think developers will want to name their functions on their own depending on the case they are dealing with. They don't need tips and I don't think they consider fixed names as benefits. It is subjective.

For this particular case, as a developer wanting to derive from a class, I will (ought to) read the documentation and understand what is expected from the derived class. Based on my requirements, I will implement(or override) the pure (or not) virtual methods based on the class documentation and have the exact same signature. There will be a compiler error otherwise. So I don't think there is a ton of benefit from enforcing a naming convention for something a compiler will throw an error if not done right.

If such a convention exists in Boost or Google style guide or any other guide that is being used by more than one project, I am fine with adopting what is in that convention. I would like OpenSim to adopt more conventions that are in these style guides.

**Comment by aseth1** [comment]
I don't necessarily disagree with anything you said but I have three observations:

1. you assume that developers do not want tips (because you don't want to be told) in the same way I assumed the tips are helpful (because I don't want to think too hard about names).

2. you will NOT get a compiler error of any useful message if your forget to call `Super::doSomething`. In many cases nothing bad even happens. That is why it is a painful mistake when a developer forgets since odd behavior can only appear downstream. That is why we decided to add the `extend` convention so we can have a hard and fast rule that you must call the super method first. Anything that can remind the developer is helpful in my view to avoid the painful process of debugging potentially months later. I, for one, have benefited by the 'extend' naming convention.

3. there are differences between Boost, Google frameworks and OpenSim. They are primarily concerned about programming constructs aimed at developers who are building software.  They have relatively flat class inheritance hierarchies and their target audience are developers without exception.  For better or worse (which could be the more fundamental problem) our inheritance hierarchies reflect a particular view of physical system hierarchies. The primary concern of our user/developers (not us in the core) is writing the code they need to simulate things- our main audience is not the computer scientist but scientists and engineers with varying levels of programming competency.  At any rate, there are numerous constructs/conventions in one domain that would not apply across the board for all software development projects.

**Comment by aseth1** [comment]
I didn't mean to imply at all that we know better than Google and Boost on how to write software. I agree we should adopt practices/standards that they have proven successful. I was just trying to say that we have different audiences/user bases, so some things may uniquely apply.

**Comment by klshrinidhi** [comment]
>you assume that developers do not want tips (because you don't want to be told) in the same way I assumed the tips are helpful (because I don't want to think too hard about names).

I am saying that not all developers like the idea, just like I don't like it. So I think they should have the option of not following your convention. You can suggest them to use your preferred names in the review but they should have the option to reject your suggestion. 

>you will NOT get a compiler error or any useful message if you forget to call Super::doSomething. In many cases nothing bad even happens. That is why it is a painful mistake when a developer forgets since odd behavior can only appear downstream. That is why we decided to add the extend convention so we can have a hard and fast rule that you must call the super method first. Anything that can remind the developer is helpful in my view to avoid the painful process of debugging potentially months later. I, for one, have benefited by the 'extend' naming convention.

Like I mentioned before, if I am deriving from a class, I ought to understand the class by reading its documentation, which should tell me what is expected of my implementation of virtual functions. For me, having read a other C++ libraries, the documentation is more important than the name. Even with fixed prefixes/suffixes like "implement" and "extend", I still need to read the documentation to know what is expected when the function name contains "implement" and "extend".

>there are differences between Boost, Google frameworks and OpenSim. They are primarily concerned about programming constructs aimed at developers who are building software. They have relatively flat class inheritance hierarchies and their target audience are developers without exception. For better or worse (which could be the more fundamental problem) our inheritance hierarchies reflect a particular view of physical system hierarchies. The primary concern of our user/developers (not us in the core) is writing the code they need to simulate things- our main audience is not the computer scientist but scientists and engineers with varying levels of programming competency. At any rate, there are numerous constructs/conventions in one domain that would not apply across the board for all software development projects.

I disagree with this point. I think OpenSim needs to learn a lot from Boost libraries and like. These libraries use sophisticated techniques underneath and expose a simple and easy to use interface for users that does not rely on users knowing any of those techniques. I think it is possible to do that with OpenSim too with careful design. Users of these libraries are not all computer scientists. They are being used in a variety of domains.


I don't want to keep arguing about this issue. I just wanted to express my opinion. I am using "implement" prefix in the pure virtual methods.

**Comment by chrisdembia** [comment]
> I don't want to keep arguing about this issue.

The tone here has been tense but I don't know if it was arguing. Anyway, one of the best ways for us to improve is to disagree with each other.

**Comment by aseth1** [comment]
This has been a good discussion. I am learning a lot. Probably best to discuss these types of things in person, I know, but it was nice to write down my reasoning. I apologize if I sounded argumentative - it was not my intention!

**Comment by sherm1** [comment]
Back to the actual topic of this issue -- non virtual interface naming. I have come around to @chrisdembia's point of view that it would be better to follow the non-virtual interface design pattern even for pure virtuals. That's because we can't know in advance whether a base class may want to insert some functionality, even if only a debugging printf or breakpoint, at some time later. If so, it would be too late to change the API once people are using it because it wouldn't be compatible. That would mean `clone()` for example would typically look like:
```c++
class Base {
public:
    std::unique_ptr<Blah> clone() const {return implementClone();}
protected:
    virtual std::unique_ptr<Blah> implementClone() const = 0;
};

class Derived : public Base {
private:
    std::unique_ptr<Blah> implementClone() const override {
        return std::unique_ptr<Blah>(new Derived(*this););
    }
};
```
With `clone()` written that way it would be no problem, for example, if in a later release we decided we needed to keep a mutable counter of the number of times `Base` objects were cloned.

Is that what you had in mind @chrisdembia?

**Comment by chrisdembia** [comment]
> Is that what you had in mind @chrisdembia?

Yes! :smile:

**Comment by chrisdembia** [comment]
Following the non-virtual interface idiom is much more important than choosing a naming convention for the protected pure virtuals.

@sherm1 I'm confused about the private/protectedness of implemented virtual methods. You can make Derived::implementClone private even if Base::implementClone was protected?

**Comment by chrisdembia** [comment]
Related: #640.

**Comment by chrisdembia** [comment]
Just to remind those interested in the non-virtual interface idiom:

> Pre- and post-condition checking is known to be a useful object-oriented programming technique particularly at development time. Pre- and post-conditions ensure that invariants of a class hierarchy (and in general an abstraction) are not violated at designated points during execution of a program. Using them at development time or during debug builds helps in catching violations earlier. To maintain consistency and ease of maintenance of such pre- and post-conditions, they should be ideally modularized at one location. In a class hierarchy, where its invariants must be held before and after every method in the subclasses, modularization becomes important.

> Similarly, acquiring and releasing locks on a data structure common to a class hierarchy can be considered as a pre- and post-condition, which must be ensured even at production time. It is useful to separate the responsibility of lock acquiring and releasing from subclasses and put it at one place - potentially in the base class.

That is an excerpt from a very thorough page on NVI: https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Non-Virtual_Interface

That page has some example code that uses the naming convention `method_name_impl()`.

**Comment by sherm1** [comment]
> That page has some example code that uses the naming convention method_name_impl().

@tkuchida will love that! The trailing `_impl` addresses the capitalization problem also. To me the main problem with that convention is that it is inconsistent with our existing `extendMethodName()` convention. It also puts the action verb at the end.

**Comment by sherm1** [comment]
> I'm confused about the private/protectedness of implemented virtual methods. You can make Derived::implementClone private even if Base::implementClone was protected?

Yes. And if I remember correctly, it even works if the *Base* method is private; you can still override it. The reason we don't so that is so that doxygen will document the protected members.

**Comment by chrisdembia** [comment]
> And if I remember correctly, it even works if the Base method is private; you can still override it.

I'm not sure we're on the same page. I'll ask the next time I see you in person.

> The reason we don't so that is so that doxygen will document the protected members.

I think we could get doxygen to show private methods ([see here](https://github.com/opensim-org/opensim-core/blob/master/doc/doxyfile_shared.in#L359). The bigger issue is scripting, IIRC.

**Comment by sherm1** [comment]
> I think we could get doxygen to show private methods

Yes, but we normally don't *want* doxygen to show private methods. Using `protected` here gives us exactly what we want -- a separate section in doxygen that will only be read by users who may be extending the class but can be ignored by users who are just using the class as-is (via its public interface). The only reason I mentioned it is that lots of the NVI literature recommends putting the base class virtuals in the private section; we shouldn't follow that advice.

**Comment by jenhicks** [comment]
Need to update contributing.md to specify convention for naming virtual methods, which is extend* when the base class also has an implementation of the virtual method and use implement* when the base class virtual method is pure. Then we can close this issue.
