### ISSUE TITLE
AbstractTool::updateFromXMLNode can modify files

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#654]
This issue is to follow up on issue #652 where a missing header in AnalyzeTool XML file (pilot error) causes the user file to be modified. This behavior is specific to ExternalLoads file because at some early version we decided to move properties from the Tool's XML file to ExternalLoads.xml. In this case the XML/DOM modification of the deserializing object is not sufficient and there's no ExternalLoads object in memory to work with.

**Comment by aseth1** [comment]
I am not sure I understand the difference between creating an ExternalLoads object (that did not exist in the old format) and creating any new objects (Connector, Frame, etc...) that we do routinely. We edit  the node so that the XML representation of the new object is present and then kick up to the base to reinterpret the node which correctly updates the object that now exists. Why is `ExternalLoads` special in this case?

**Comment by aymanhab** [comment]
@aseth1 It is special because there's no live ExternalLoads object at this point (during deserialization), instead it gets created down the line (inside the run method by calling createExternalLoads) so the only way to communicate changes from the Tool to the ExternalLoads object is thru the _externalLoadsFileName.

**Comment by aseth1** [comment]
OK, I think I understanding a bit more. The tool thinks it is has to create the external loads file because of the incorrect version number. In the test case it wasn't actually editing `externalForces.xml`  the tool was overwriting the existing file because it thought it had to build one? It just happened to be that the difference between the two files was cutoff frequency? Wouldn't there have been other tell-tale differences like the version number also changed to the current value?

**Comment by sherm1** [comment]
@aymanhab says this should be done for 4.0.

**Comment by sherm1** [comment]
@aseth1 sez: should throw an exception if it finds an "unreasonable" file for the conversion.
