### ISSUE TITLE
Linking Simbody and OpenSim in Debug mode cmake issue

### ISSUE THREAD

**Issue by eobropta** [opensim-org/opensim-core#693]
I'm new to the community here. Thanks for being so active! 

After compiling Simbody 3.6 and opensim-core from Github, both in Debug mode I tried to compile the simple arm and one muscle example on the main Github page using the SampleCMakeLists.txt as a template CMakeLists.txt file.

I got the following error message after calling `make` on the example

```
/usr/bin/ld: cannot find -lSimTKcommon
/usr/bin/ld: cannot find -lSimTKmath
/usr/bin/ld: cannot find -lSimTKsimbody
```

When I looked in <opensim-install>/cmake/OpenSimTargets-debug.cmake

I found 

```
set_target_properties(osimCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "SimTKcommon;SimTKmath;SimTKsimbody"
  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/lib/libosimCommon_d.so"
  IMPORTED_SONAME_DEBUG "libosimCommon_d.so"
  )
```

which looked suspicious since my SimTKcommon, SimTKmath, and SimTKsimbody files all have the trailing _d from Debug mode.

After modifying this .cmake file to this in a couple places

```
"SimTKcommon_d;SimTKmath_d;SimTKsimbody_d"
```

My problems were solved and the example program compiled and ran successfully. I'm sure there's a real way to fix this or maybe I compiled something wrong, but I thought I'd post my findings since it took a while to track down. Thanks.

**Comment by klshrinidhi** [comment]
Hi @eobropta,
Can you post the steps you took to compile both Simbody and OpenSim (including which version of Simbody and OpenSim you are using) ?

**Comment by chrisdembia** [comment]
What did you use for `CMAKE_BUILD_TYPE` (assuming you used Unix Makefiles) in the example projects? Did you set this to `Debug`, or did you leave it unset?

**Comment by eobropta** [comment]
Sure! I think it was a pretty vanilla install. Everything was bleeding-edge, git clones as of today.

OS: Ubuntu 15.04

```
# Simbody Install
$ git clone https://github.com/simbody/simbody.git ~/simbody-source
$ mkdir ~/simbody-build
$ cd ~/simbody-build
# use cmake-gui
# set the CMAKE_BUILD_TYPE to Debug
# set the CMAKE_INSTALL_PREFIX to ~/simbody
# configure and generate
$ make 
$ make install

# OpenSim Install
$ git clone https://github.com/opensim-org/opensim-core.git ~/opensim-core-source
$ mkdir ~/opensim-build
$ cd ~/opensim-build
# use cmake-gui
# set the CMAKE_BUILD_TYPE to Debug
# set the CMAKE_INSTALL_PREFIX to ~/opensim
# OPENSIM_COPY_SIMBODY is checked on, which I think is default
# set SIMBODY_HOME to ~/simbody
# configure and generate
$ make 
$ make install
```

After the install my ~/opensim/lib folder has these contents.
```
$ ls ~/opensim/lib/
libosimActuators_d.so  libosimSimulation_d.so   libSimTKmath_d.so
libosimAnalyses_d.so   libosimTools_d.so        libSimTKmath_d.so.3.6
libosimCommon_d.so     libSimTKcommon_d.so      libSimTKsimbody_d.so
libosimLepton_d.so     libSimTKcommon_d.so.3.6  libSimTKsimbody_d.so.3.6
```

**Comment by eobropta** [comment]
@chrisdembia - yes, in the example project I set the CMAKE_BUILD_TYPE to Debug. Should it be unset?

**Comment by chrisdembia** [comment]
No it should be set. 

I successfully reproduced your problem. Thanks for reporting this bug.

I've tried a fix in this branch: https://github.com/opensim-org/opensim-core/tree/cmake-simbody-libs-debug.  I tested this locally and it fixed the problem. It's not a satisfactory solution to put into master; I need to properly account for the OPENSIM_COPY_SIMBODY flag. Let us know if you get a chance to try out the fix.

I've explained my understanding of the bug [here](https://github.com/opensim-org/opensim-core/blob/cmake-simbody-libs-debug/cmake/OpenSimConfig.cmake.in#L72).

**Comment by elen4** [comment]
Hi @chrisdembia,
I had similar issues with my "downstream" Opensim projects.
On my Ubuntu 14.04 machine, I have a *master* Simbody version, against which I compiled *master* OpenSim, which is installed in a non-system directory, and an older Simbody 3.5 version installed in /usr (it lurked in when I installed Gazebo). Of course, libraries in the system directory get picked up instead of the ones I want, and I have to explicitly add a `find_package(Simbody)` to my CMakeLists.txt so that CMake associates proper targets to the Simbody library names.
I tested the `cmake-simbody-libs-debug` branch after rebasing onto master, and it solved my issue. I understand that the "Opensim copies Simbody" case is not addressed (I think, I didn't test it) and the optimal solution might not be trivial, still maybe a partial solution would be better than the current situation?

Also, I found similar issues related to the BTK dependency (not sure if I should open a dedicated issue):
on a Windows machine, @lucaTagliapietra installed OpenSim through the superbuild, building also BTK. To use OpenSim in downstream projects, he needs to add the `find_package(BTK)` command and include the `BTK_USE_FILE` (:confounded:) to make things work. Of course, this makes his CMake code not portable across machines. I did not get from #766 if BTK is going to be a hard dependency or if it is going to remain optional. In the latter case, OpenSim's config file should also indicate if OpenSim was built with BTK or not, in case the user project needs BTK-related features (maybe this might also be handled as a COMPONENT passed in to find_package, not sure).

Further comments:
- in CMake >=3, they introduced a `find_dependency` macro, that basically wraps a find_package call but propagates arguments and so on. You might want to use it when available.
- I think that solving this issue would also address #738.

**Comment by chrisdembia** [comment]
Thanks for all of that. This stuff is super confusing and surprisingly hard to get right. 

`find_dependency()` looks like it is meant for this problem. However, it'd be nice to enforce that the same exact Simbody is used in the downstream OpenSim project as used when building OpenSim (that is, invoke `find_package(Simbody  It doesn't look like `find_dependency()` supports this. This may only make sense when building the whole stack from source on the same machine, I suppose.

**Comment by klshrinidhi** [comment]
I will work on this. Good to get this fixed asap.

**Comment by jenhicks** [comment]
@klshrinidhi Is this fixed?

**Comment by chrisdembia** [comment]
Shrinidhi put in a partial fix for the developer's workshop but a comprehensive fix is still needed.

**Comment by jenhicks** [comment]
Who is working on this?

**Comment by aymanhab** [comment]
@klshrinidhi is working on this per @chrisdembia
