### ISSUE TITLE
Tools crash Matlab if model_file is not specified

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#697]
This may become obsolete if we move away from using Tools but for the time being, some tools (e.g. RRATool) crashes rather than throw an exception if model file is not specified in XML. A meaningful error message should be reported instead ( reported by user on the forum https://simtk.org/forums/viewtopic.php?f=91&t=5192&view=unread#unread)

GUI created files do not have <model_file> specified since the GUI works on live models.

**Comment by chrisdembia** [comment]
This might be more about exception handling in SWIG; as I've indicated before, at least with python, we should move toward handling all C++ exceptions through swig.

**Comment by aymanhab** [comment]
@chrisdembia AFAIK all C++ exceptions are translated through SWIG to Java exceptions and so wouldn't cause a crash. In this case I think we just dereference a null pointer directly, and that's what we need to fix/change I think.

**Comment by jenhicks** [comment]
@jimmyDunne Can you verify that this is fixed? Matlab shouldn't crash and you should get a useful exception warning message (e.g., tool is missing a model)

**Comment by jimmyDunne** [comment]
Not having a model specified in the Fwd Setup XML does **still** crash Matlab (tested using the gait2392 pipeline).

**Comment by jimmyDunne** [comment]
Can confirm, NOT having the model specified in the Setup XMLs for RRATool, CMCTool, and ForwardTool, all cause a fatal Matlab crash when Tool is instantiated.

**Comment by chrisdembia** [comment]
Darnit. Is anything useful printed? Is there a crash log (in your home directory) that might show a stack trace?

**Comment by jimmyDunne** [comment]
MATLAB crash file:/Users/jimmy/matlab_crash_dump.3303-1:


------------------------------------------------------------------------
       Segmentation violation detected at Thu Feb 23 19:55:08 2017
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Current Visual      : Quartz
  Default Encoding    : ISO-8859-1
  Host Name           : mpu
  MATLAB Architecture : maci64
  MATLAB Root         : /Applications/MATLAB_R2015b.app
  MATLAB Version      : 8.6.0.267246 (R2015b)
  OpenGL              : hardware
  Operating System    : Darwin 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
  Processor ID        : x86 Family 6 Model 70 Stepping 1, GenuineIntel
  Virtual Machine     : Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : Quartz

Fault Count: 1


Abnormal termination:
Segmentation violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007f99220c3400
  RCX = 0000700003429c60  RDX = 000000012ca3cb11
  RSP = 0000000000000548  RBP = 00007f9913596d20
  RSI = 0000000000000019  RDI = 0000000000000021

   R8 = 00007f99220c3400   R9 = 0000000000000000
  R10 = 0000000000000000  R11 = 0000000000000000
  R12 = 0000700003429ce0  R13 = 000000012c9c3564
  R14 = 0000000000000090  R15 = 00007f992553a400

  RIP = 0000000000000000  RFL = 0000000000000000

   CS = 0000000000000000   FS = 0000000000000031   GS = 0000000000000025

Stack Trace (from fault):
[  0] 0x0000000103d7ca34 /Applications/MATLAB_R2015b.app/bin/maci64/libmwfl.dylib+00027188 _ZN2fl4diag15stacktrace_base7captureERKNS0_14thread_contextEm+00000052
[  1] 0x0000000103d8035a /Applications/MATLAB_R2015b.app/bin/maci64/libmwfl.dylib+00041818 _ZN2fl4test17terminate_handledEv+00000746
[  2] 0x0000000103d7fe08 /Applications/MATLAB_R2015b.app/bin/maci64/libmwfl.dylib+00040456 _ZN2fl4diag13terminate_logEPKcPK17__darwin_ucontext+00000152
[  3] 0x0000000107a15316 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00336662 _Z32mnRunPathDependentInitializationv+00002806
[  4] 0x0000000107a155a9 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00337321 _Z32mnRunPathDependentInitializationv+00003465
[  5] 0x0000000107a138ca /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00329930 mnFatalSignalHandler+00000282
[  6] 0x00007fffeb701bba           /usr/lib/system/libsystem_platform.dylib+00011194 _sigtramp+00000026
[  7] 0x00007fffea109e2e                           /usr/lib/libc++abi.dylib+00146990 _Znwm+00000030
[  8] 0x0000000127cc57c1 /Users/jimmy/repository/opensim-master/opensim-install/lib/libosimTools.dylib+00239553 _ZN7OpenSim7CMCToolC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEb+00000561
[  9] 0x000000012bffa3b9 /Users/jimmy/repository/opensim-master/opensim-install/lib/libosimJavaJNI.dylib+04813753 Java_org_opensim_modeling_opensimModelJNI_new_1CMCTool_1_1SWIG_12+00000153
[ 10] 0x00000001151b6758                                   <unknown-module>+00000000
[ 11] 0x00000001151aa175                                   <unknown-module>+00000000
[ 12] 0x00000001151a44e7                                   <unknown-module>+00000000
[ 13] 0x0000000110538b58 /Applications/MATLAB_R2015b.app/sys/java/jre/maci64/jre/lib/./server/libjvm.dylib+02997080 _ZN9JavaCalls11call_helperEP9JavaValueP12methodHandleP17JavaCallArgumentsP6Thread+00000554
[ 14] 0x0000000110538928 /Applications/MATLAB_R2015b.app/sys/java/jre/maci64/jre/lib/./server/libjvm.dylib+02996520 _ZN9JavaCalls4callEP9JavaValue12methodHandleP17JavaCallArgumentsP6Thread+00000040
[ 15] 0x000000011056c4a7 /Applications/MATLAB_R2015b.app/sys/java/jre/maci64/jre/lib/./server/libjvm.dylib+03208359 _ZL20jni_invoke_nonstaticP7JNIEnv_P9JavaValueP8_jobject11JNICallTypeP10_jmethodIDP18JNI_ArgumentPusherP6Thread+00000698
[ 16] 0x000000011055dcaa /Applications/MATLAB_R2015b.app/sys/java/jre/maci64/jre/lib/./server/libjvm.dylib+03148970 jni_NewObjectA+00000212
[ 17] 0x000000010f937cc0 /Applications/MATLAB_R2015b.app/bin/maci64/libmwjmi.dylib+00163008 _Z16mljCreateObjectAP7_jclassP10_jmethodIDPK6jvaluemPKc10JavaThread+00000144
[ 18] 0x000000010f988c88 /Applications/MATLAB_R2015b.app/bin/maci64/libmwjmi.dylib+00494728 _Z19ojRegisterFunctionsv+00013272
[ 19] 0x000000011008f8f4 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcos_impl.dylib+01833204 _ZN22Mfh_opaque_constructor11dispatch_mfEiPP11mxArray_tagiS2_+00000244
[ 20] 0x0000000107aa9126 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_dispatcher.dylib+00016678 _ZN13Mfh_MATLAB_fn11dispatch_fhEiPP11mxArray_tagiS2_+00000502
[ 21] 0x000000011008ddbc /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcos_impl.dylib+01826236 _ZN10Mfh_opaque11dispatch_fhEiPP11mxArray_tagiS2_+00000028
[ 22] 0x000000010ae6d787 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+08943495 _ZNK9MathWorks3lxe21UnboundFunctionHandle26invokeAfterPossibleRefreshEmPP11mxArray_tagmPKPKS2_+00000151
[ 23] 0x000000010ae6d873 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+08943731 _ZNK9MathWorks3lxe21UnboundFunctionHandle6invokeEmPP11mxArray_tagmPKPKS2_+00000019
[ 24] 0x000000010ae6d97a /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+08943994 _ZNK9MathWorks3lxe21UnboundFunctionHandle6invokeEmPNS0_6xvalueEmPKS2_+00000186
[ 25] 0x000000010ae7392c /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+08968492 _ZN9MathWorks3lxe20call_global_functionERNS0_14ILxeDispatcherEPKcPKNS0_29DispatcherFunctionHandleTokenEmPNS0_6xvalueEmPKS8_+00000156
[ 26] 0x000000010acb3a48 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+07133768 _ZN9MathWorks3lxe17LxeDispatcherImpl14apply_dispatchEPKcPKNS0_29DispatcherFunctionHandleTokenEmPNS0_6xvalueEmPKS7_+00000184
[ 27] 0x000000010ae201c6 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+08626630 _ZN9MathWorks3lxe14apply_dispatchEPvNS_2ts4TypeEPKvS1_S1_+00000454
[ 28] 0x000000010add64c5 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+08324293 _ZN9MathWorks3lxe38cpp_primitive_template_fn_with_contextIXadL_ZNS0_14apply_dispatchEPvNS_2ts4TypeEPKvS2_S2_EEEEbS2_S4_S6_S2_S2_+00000021
[ 29] 0x000000010a9ca70b /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+04081419 callPrimitiveWrapper+00000299
[ 30] 0x000000010a9b24ef /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+03982575 _ZN9MathWorks3lxe15ExecutionDriver9ThreadRunEv+00000639
[ 31] 0x000000010a9c3150 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+04051280 _ZN9MathWorks3lxe12IrEngineImpl5ApplyERKN2ir6IrTreeEPvS6_+00000352
[ 32] 0x000000010abafa93 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+06068883 _ZN9MathWorks3lxe17IrEngineDecorator5ApplyERKN2ir6IrTreeEPvS6_+00000211
[ 33] 0x000000010ab74ac2 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+05827266 _ZN9MathWorks3lxe9Evaluator15ApplyStatementsERKN2ir6IrTreeERNS0_18IEvaluationContextE+00000450
[ 34] 0x000000010ab767a7 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+05834663 _ZN9MathWorks3lxe9Evaluator17EvalStatementImplEPKcRNS0_18IEvaluationContextE+00000167
[ 35] 0x000000010ab76854 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+05834836 _ZN9MathWorks3lxe9Evaluator13EvalStatementERKNSt3__112basic_stringIDsNS2_11char_traitsIDsEENS2_9allocatorIDsEEEERNS0_18IEvaluationContextE+00000100
[ 36] 0x000000010abef36c /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+06329196 _ZN9MathWorks3lxe9LxeBridge7EvalCmdERKNSt3__112basic_stringIDsNS2_11char_traitsIDsEENS2_9allocatorIDsEEEEb+00000396
[ 37] 0x000000010abef217 /Applications/MATLAB_R2015b.app/bin/maci64/libmwm_lxe.dylib+06328855 _ZN9MathWorks3lxe9LxeBridge7EvalCmdERKNSt3__112basic_stringIDsNS2_11char_traitsIDsEENS2_9allocatorIDsEEEEb+00000055
[ 38] 0x000000010a5abe6d /Applications/MATLAB_R2015b.app/bin/maci64/libmwbridge.dylib+00061037 _Z28evalCommandWithLongjmpSafetyRKNSt3__112basic_stringIDsNS_11char_traitsIDsEENS_9allocatorIDsEEEE+00000093
[ 39] 0x000000010a5ac3af /Applications/MATLAB_R2015b.app/bin/maci64/libmwbridge.dylib+00062383 _Z8mnParserv+00000655
[ 40] 0x00000001079fef92 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00245650 _ZN11mcrInstance30mnParser_on_interpreter_threadEv+00000034
[ 41] 0x00000001079e42d1 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00135889 _ZN3mcr7runtime17InterpreterThread4Impl22TypedInvocationRequestIvE29doNotRethrowMxArrayExceptionsERKN5boost8functionIFvvEEE+00000033
[ 42] 0x00000001079e4d99 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00138649 _ZN5boost3_bi5list1INS0_5valueINS_8functionIFvvEEEEEEC2ES6_+00000569
[ 43] 0x00000001079e4726 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00136998 _ZN5boost6detail9task_baseIvE3runEv+00000182
[ 44] 0x00000001079e44d7 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00136407 _ZN5boost13packaged_taskIvE10get_futureEv+00000343
[ 45] 0x00000001079e04e3 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00120035 _ZN3mcr7runtime17InterpreterThread4Impl26invocation_request_handlerEl+00000035
[ 46] 0x0000000107599b4f /Applications/MATLAB_R2015b.app/bin/maci64/libmwservices.dylib+00183119 _ZN10eventqueue18UserEventQueueImpl5flushEv+00000975
[ 47] 0x000000010bc3f325 /Applications/MATLAB_R2015b.app/bin/maci64/libmwuix.dylib+00041765 _Z25isHandleUserEventCallbackPFvPvE+00000645
[ 48] 0x00000001076825cc /Applications/MATLAB_R2015b.app/bin/maci64/libmwservices.dylib+01136076 _Z40svWS_ProcessPendingEventsWithLimitedRateb+00016332
[ 49] 0x000000010767dd62 /Applications/MATLAB_R2015b.app/bin/maci64/libmwservices.dylib+01117538 _Z25svWS_ProcessPendingEventsiib+00000898
[ 50] 0x000000010767da3b /Applications/MATLAB_R2015b.app/bin/maci64/libmwservices.dylib+01116731 _Z25svWS_ProcessPendingEventsiib+00000091
[ 51] 0x00000001079e0717 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00120599 _ZN3mcr7runtime17InterpreterThread4Impl14process_eventsERKN5boost10shared_ptrIS2_EE+00000103
[ 52] 0x00000001079e0a06 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00121350 _ZN3mcr7runtime17InterpreterThread4Impl3runERKN5boost10shared_ptrIS2_EEPNS2_12init_contextE+00000358
[ 53] 0x00000001079c9116 /Applications/MATLAB_R2015b.app/bin/maci64/libmwmcr.dylib+00024854 _Z26run_init_and_handle_eventsPv+00000054
[ 54] 0x00007fffeb70baab            /usr/lib/system/libsystem_pthread.dylib+00015019 _pthread_body+00000180
[ 55] 0x00007fffeb70b9f7            /usr/lib/system/libsystem_pthread.dylib+00014839 _pthread_body+00000000
[ 56] 0x00007fffeb70b221            /usr/lib/system/libsystem_pthread.dylib+00012833 thread_start+00000013


If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.

**Comment by jimmyDunne** [comment]
No, not really. Just the typical crash message from Matlab. 
[matlab_crash_dump.3303-1.txt](https://github.com/opensim-org/opensim-core/files/798335/matlab_crash_dump.3303-1.txt)

**Comment by aseth1** [comment]
#793 is the PR that should throw a meaningful Exception, which I though had been merged. It was not merged (my bad) but I was probably waiting for the tests to pass. @klshrinidhi can you revive #793 and let's get it merged when the tests pass. Sorry about that!
