### ISSUE TITLE
Possible memory leak in GCVSpline.cpp

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#725]
I notice a possible memory leak in [GCVSpline.cpp : line 297, 298](https://github.com/opensim-org/opensim-core/blob/2e0e9e8690a02f034f4eea8f38eb79faa47cd17c/OpenSim/Common/GCVSpline.cpp#L297:L298) at lines 297 and 298 (maybe there are more).

Problem -- Variables x and y are *dynamically allocated arrays* but are being deleted as if they were *dynamically allocated non-arrays*.

**Comment by sherm1** [comment]
Good find! Shouldn't cause a problem in practice though since these are arrays of doubles so no destructor call is required for the original elements. Ought to be done correctly, though. Better if these were replaced with `std::vector<double>` I think.

**Comment by klshrinidhi** [comment]
I agree. I think RAII container should be used.

**Comment by chrisdembia** [comment]
I suggest we close this as a result of #726, but I'm fine with us leaving it open given that my solution only fixed the leak but did not use `vector`.

**Comment by sherm1** [comment]
I agree -- we should close this because GCVspline is basically an old C program that works and no one is realistically going to rewrite it to modernize it. Also, we have a lot of other mathematical code here and there that was grabbed long ago from some open source algorithm repository (Simbody's polynomial solver comes to mind). We can open a new issue if there is an actual problem.

**Comment by chrisdembia** [comment]
Fixed by #726.
