### ISSUE TITLE
InverseDynamicsTool is not a member of OpenSim?

### ISSUE THREAD

**Issue by eobropta** [opensim-org/opensim-core#734]
I have OpenSim compiled on Ubuntu 15.04. I'm writing a C++ driver using the OpenSim API. I would like to run a Inverse Dynamics simulation, but when I write

`OpenSim::InverseDynamicsTool idTool;`

in my main, I get 

"InverseDynamicsTool is not a member of OpenSim."

I found in <opensim-install>/include/OpenSim/Tools/osimTools.h does not have the line "#include "InverseDynamicsTool.h". Is this right? Or is it an error that would cause my error?

**Comment by chrisdembia** [comment]
That is a bug; thanks for reporting. As you see, InversKinematicsTool.h *does* appear in osimTools.h. Would you like to submit a PR with the fix?

**Comment by eobropta** [comment]
I've added `#include "InverseDynamicsTool.h"` to the <opensim-source>/OpenSim/Tools/osimTools.h header file, and rebuilt the OpenSim library as well as reinstalled it, but when I run my main program I still receive the error. I think there must be something else I also need to modify.

Here's my simple driver.

```
#include <OpenSim/OpenSim.h>
#include <iostream>
using namespace SimTK;
using namespace OpenSim; using OpenSim::Body;
using namespace std;

int simpleID() {
  OpenSim::InverseKinematicsTool ikTool;
  ikTool.setName("simpleIK");
  OpenSim::InverseDynamicsTool idTool;
  idTool.setName("simpleID");
  return 0;
}

int main() {
  return simpleID();
}
```

The driver will not compile and gives the error
```
error: ‘InverseDynamicsTool’ is not a member of ‘OpenSim’
   OpenSim::InverseDynamicsTool idTool;
   ^
```
If I remove the InverseDynamicsTool line, it does compile and execute so I know InverseKinematicsTool is "working" and OpenSim is linked properly.

Any idea where I would need to make a change? I've been looking around for tests or examples. I think the only test appears in <opensim-source>/Applications/ID/test/testID.cpp, but that file does not use `#include OpenSim/OpenSim.h` and instead includes each header file individually which I can do I suppose, but I don't think that's inline with the current style for the "OpenSim API".

**Comment by chrisdembia** [comment]
It's OK to include just the header file you need; this may actually improve compile times (if you are able to avoid including `OpenSim/OpenSim.h`). But you are right that you should be able to include only `OpenSim/OpenSim.h`, and so you shouldn't need to resort to what you see in testID.

What you did should have fixed the problem. Are you sure that the re-intsallation took your change into account? Check the copy of osimTools.h in your installation.

Perhaps try removing `OpenSim::` from `OpenSim::InverseDynamicsTool` (it's not necessary since you are using the OpenSim namespace); perhaps the compiler will give you a different more meaningful error?

**Comment by jenhicks** [comment]
Thank you for reporting this issue and we hope that you've found a resolution. We are closing this issue. If you are still having a problem and would like to work with us to resolve, we are happy to reopen.
