### ISSUE TITLE
Component::updComponentList()

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#759]
We plan to use `getComponentList()` to replace most uses of sets, but people often loop through sets to modify the entries of the set (e.g., increase muscle strength). Right now, `getComponentList()` gives back const components; we must also have a `updComponentList()` to provide writable components.

Discovered with @klshrinidhi

**Comment by chrisdembia** [comment]
#810 and other PRs introduce member subcomponents. Since member subcomponents should not be modified, the `updComponentList()` should not be able to iterate over the member subcomponents. Only the `getComponentList()` should iterate over them.

**Comment by aymanhab** [comment]
@chrisdembia Wouldn't that produce inconsistency? In all other API contexts, the difference between getXX and updXX is the const vs. writable return type rather than actual contents. Thoughts?

**Comment by aymanhab** [comment]
It may be less confusing to have two methods one that gets all components (const) and a get/upd pair that return only "public/non-internal/non-private/...." components.

**Comment by chrisdembia** [comment]
Good point. +1

**Comment by aseth1** [comment]
@aymanhab I like your suggestion and agree having the get/upd pair mirror each other in terms of which Components are accessed is important and would be confusing otherwise and these lists wold exclude member and adopted components. I was thinking that a protected get/upd for all of a Component's local (direct children of this) would be sufficient, since only the parent component that has member or adopted subcomponents is expected to update their properties, otherwise it should have been added as a property. What would be a good name for the local list accessors? `get/updLocalComponentList<C>()` with the filtering capabilities as the public `getComponentList<C>()` but for local subcomponents only. Thoughts?

**Comment by aymanhab** [comment]
@aseth1 Local seems fine but there are too many names floating around, is intention direct children (which would I'd call local) or all descendants of children as well?

**Comment by aseth1** [comment]
> Local seems fine but there are too many names floating around, is intention direct children (which I'd call local) or all descendants of children as well?

In which context are you referring to? Yes, local means the immediate children of a Component for the protected methods. Does calling them children make i more clear? Do you prefer `get/updChildren()` or `get/updChildrenComponentList()`? What are you proposing?

**Comment by aseth1** [comment]
It would be similar to how we have public `getStateVariableNames()` which lists all the names of state variables that fall under the Component (including those of its subcomponents) opposed to the private `getStateVariablesNamesAddedByComponent` that yields only the state variable names of those StateVariables added by this component. 

I would make `get/updLocalComponentList<C>()` protected so that derived Components can access their immediate children quickly and easily.
