### ISSUE TITLE
Issues discovered when writing hopper device example

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#764]
@klshrinidhi ran into a few issues when writing the hopper device. I tried to create individual Issues for most of the problems, but here are some for which I didn't want to create a new issue. Perhaps we can discuss in a dev meeting.

1. The process for adding geometry to a body seems a little unintuitive, though I'm not sure it can be improved. Example from the hopper device:

    ```cpp
    OpenSim::Sphere sphere{0.1};
    sphere.setName("sphere");
    sphere.setFrameName("massA");
    massA->append_geometry(sphere);
    ```

2. Geometry classes have duplicate methods for accessing/mutating properties; we can remove these, as the macro-generated methods are now documented in doxygen.

3. Connecting to ground from a nested component should not be possible with `"ground"`; one should have to provide `"/ground"`. I think @aseth1 is fixing this in an upcoming PR.

4. We need a glossary of terms concerning component path names (what does a "component's name" mean? what is a relative component path?) .

5. There is not an easy way right now to check if there *is* a component (that is, `hasComponent()`). @klshrinidhi resorted to using `std::find_if()`. I discussed this with @aseth1, so he may have a plan here.

6. The internals of `Connector<T>::connect()` does *not* use full path names (only the component's name). This might be because it's currently possible to connect to Objects (not only Components), and Objects may not have a full path?

7. Writing the hopper device example would have been a little easier with `Time` and `Constant` outputs. The `Time` output should just output time. That way, functions could use time as an input.

**Comment by aymanhab** [comment]
@chrisdembia Happy to discuss the Geometry related issues in person whenever you have a chance.

**Comment by aymanhab** [comment]
Based on discussion with @chrisdembia the plan is to:
1. Move "addMeshGeometry" currently available for convenience on Body to Frame and keep setting Frame name internally
2. Add a new method "addGeometry" that takes a constructed Geometry object, sets the frame name and proceed as current addGeometry.
3. Eliminate custom setters/getters from concrete Geometry subclasses if they can be replaced by the property Macro.

One issue that still feels a bit iffy is the use of the name "addGeometry" since users may not expect "add"  to also set the frame name, better names are welcome. (addAttach or addAndAttach
