### ISSUE TITLE
Homebrew installation for OpenSim in 2 commands on OS X 10.10 & 10.11

### ISSUE THREAD

**Issue by klshrinidhi** [opensim-org/opensim-core#765]
I am able to successfully install OpenSim from sources including all the dependencies on OS X 10.11 (El Capitan) and OS X 10.10 (Yosemite) with the following two commands:

``` shell
brew tap klshrinidhi/tap
brew install opensim-core
```

Give it a try.
The above two commands install **all** the dependencies for OpenSim including Simbody and BTKCore. Currently, I have set it up to build Simbody and BTKCore from source. This is **not super-build**. Dependency management is done by Homebrew. Future updates will make _bottled_ binaries available for both OS X 10.11 and OS X 10.10.

The install directory is `/usr/local/Cellar`. A symbolic link is also created (in normal case) in `/usr/local/opt`. Because OpenSim copies Simbody headers, Homebrew has to overwrite previously installed Simbody headers and refuses to do so until we explicitly ask it to overwrite. This problem should be solvable but for now `/usr/local/Cellar` will contain `opensim-core` installation and is ready to use.

If we clone [my repo](https://github.com/klshrinidhi/homebrew-tap) into a repo under opensim-org, the above commands will become:

``` shell
brew tap opensim-org/tap
brew install opensim-core
```

**Comment by chrisdembia** [comment]
Exciting! I'll try this soon.

**Comment by sherm1** [comment]
:+1:

**Comment by aymanhab** [comment]
That sounds exciting indeed @klshrinidhi 
Can you or anybody on this trail describe where homebrew fits in the OSX echo system, are there any pointers, statistics out there? Just trying to understand what segment of the OSX crowd we're catering to, and if it justifies the work/effort. Thanks.

**Comment by chrisdembia** [comment]
> Just trying to understand what segment of the OSX crowd we're catering to,

I think there are 4 types of consumers of our software:

1. **End-users** who use the GUI and don't know any programming (analogous program: Microsoft Word)
2. **API users** who use the API through either Python, MATLAB or C++ (main programs). (analagous: IPOPT/LAPACK/BLAS).
3. **Plugin developers** who extend classes from the OpenSim API for use by other OpenSim for all 4 types of users (including end-users, API users).
4. **Contributors** who edit OpenSim API source code and contribute it back to opensim-core.

Obtaining OpenSim through homebrew caters to **API users** and **Plugin developers**. Not to End-users because we cannot expect end users to use Homebrew (Microsoft doesn't expect you to install anything else first). Not to contributors, since you cannot reasonably edit and recompile the OpenSim source code from a Homebrew installation.

Note that a Homebrew installation *can* be used by **Contributors** to fetch the dependencies of OpenSim.

> and if it justifies the work/effort.

I think homebrew scripts are relatively easy to maintain (compared to debian, for example), and so it is easy to justify the work. It is also common for such scripts to be maintained by people *other* than the developers, so the burden may not be on us. For example, OSRF maintains the homebrew for Simbody.

> Can you or anybody on this trail describe where homebrew fits in the OSX echo system,

Homebrew is similar to `apt-get` on Ubuntu in that it is language-agnostic, for any type of software package (even GUI packages, through homebrew "casks"), with the main difference being that Ubuntu users can be expected to get *ALL* of their software through `apt-get`, while I believe it is unreasonable to expect the non-coder OSX user to use homebrew (non-coders would more naturally use the App Store).

**Comment by aymanhab** [comment]
Great, thanks @chrisdembia for the explanation. Will likely stick to the official OSX packaging for the GUI application when the time comes.

**Comment by chrisdembia** [comment]
Two comments for now:

1. OSRF also has a tap for simbody (https://github.com/osrf/homebrew-simulation/blob/master/simbody.rb); we should coordinate somehow. Perhaps simbody's script should go into Homebrew's main repo?
2. Homebrew has a tap for python. Should we require homebrew's python or use the system python?

**Comment by klshrinidhi** [comment]
@chrisdembia 
>OSRF also has a tap for simbody (https://github.com/osrf/homebrew-simulation/blob/master/simbody.rb); we should coordinate somehow. Perhaps simbody's script should go into Homebrew's main repo?

If Simbody's script goes to another repo, then users will have to use two commands, one for our repo and one for Simbody's repo. Since Simbody is integral to OpenSim, I think it is okay to have our own script to get better control and to reduce number of commands users have to type. Homebrew allows users to install from any script of their choosing so there will be not much conflict.

My idea was to get a PPA like thing going for OpenSim for now. I will try to get OpenSim into Homebrew. It will take time. After that, it will just be one command:
```shell
brew install opensim-core
```

>Homebrew has a tap for python. Should we require homebrew's python or use the system python?

Right now, I do not have Python stated as a dependency for OpenSim in Homebrew. If it becomes a problem, we will update later.

**Comment by chrisdembia** [comment]
From a fresh OSX install (El Capitan 10.11.2):

1. When installing homebrew, I was prompted to install Xcode, and I did so.
2. `brew tap klshrinidhi/tap` worked fine.
3. `brew install opensim-core` gave an error `Error: an unsatisfied requirement failed this build. I was told to run `brew install Caskroom/cask/java`.
4. I ran `brew install Caskroom/cask/java` and was asked to enter my password to set up caskrooms properly.
5. I reran `brew install opensim-core` and this succeeded. It took 10 minutes to build `opensim-core`.
6. I got a long list of "Possible conflicting files are:", mostly listing Simbody headers and libraries.
7. I got an error about failed `brew link`: 
![image](https://cloud.githubusercontent.com/assets/846001/13134459/636a230a-d5bb-11e5-9ac3-73c71e4ee29d.png)
8. There are no opensim-core executables in `/usr/local/bin`. There are no OpenSIm libraries in `/usr/local/lib`; only Simbody and BTK libs. Also, OpenSim's Config.cmake file isn't there.
9. The executables in the `/usr/local/Cellar/opensim-core/4.0/bin` directory do work, and have the proper RPATH.
Feedback:

1. I think we should rename our tap to be something other than `tap`. Perhaps `opensim`, or `ncsrr`? I guess I'm fine with `tap` too...
2. Where/how do you plan to document this new method for getting OpenSim? It seems like it falls in between the README, which has manual build-from-source instructions, and Confluence, which is for end users.
3. I did not test different build configurations... if I ask for OpenSim `--with-Debug`, will all its dependencies be built in debug as well?
4. What's the difference between `depends_on :java` and `depends_on "java"`?
5. I feel a little bit weird that the opensim-core tap says `version  "4.0"`, since the given commit hash is not actually v.4.0 . Could it be named something like `v4.0b`? Ditto for Simbody.
6. What about making OpenSim depend on Simbody HEAD? Otherwise, we'll need to keep updating the commit hash in the Simbody .rb file.
7. I think the descriptions should just say what the software package is: `"Download, compile and install OpenSim."` -> `Musculoskeletal modeling and simulation software`, etc.
8. The `class OpensimCore` should be called `OpenSimCore`, I think.
9. The compiling happened non-parallel. Is this a homebrew policy?
10. I don't know if this is necessary, but OSRF has travis do some checks on their tap files: https://github.com/osrf/homebrew-simulation/blob/master/.travis.yml
11. FYI: https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/formula.rb#L1045. I don't think we should use this though; I think it removes optimizations.
12. What about doxygen as a dependency? It might be good to leave it out; just wanted to mention it though.
13. We can't install OpenSim's applications into `/usr/local/bin`, b/c we conflict with the system's `id` executable. But we should be able to install symlinks to OpenSim's Libraries. But this didn't happen.

**Comment by HelgeG** [comment]
Thanks for creating this brew recipe. It installed without a hitch on OSX 10.11.5.

**Comment by claudia-lat** [comment]
Thanks for your efforts.  
Just a comment on my installation experience: when I ran the two command lines I found the error 'Error: Formulae found in multiple taps' because I had another dependency on simbody.  So I changed  the name of the formula and the ran `brew install opensim-core`.
