### ISSUE TITLE
Adding outputs

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#796]
Add outputs to classes

- [x] Muscle 
- [ ] Forces 
       - [ ] bushing {Matt}
       - [x] path Spring {Ayman}
- [x] Frames (position, transform) {Ayman}
- [ ] Markers {James & Chris}

**Comment by aymanhab** [comment]
Will start on Frames & PathSpring, Please let me know @chrisdembia if I can start using constructOutput as done in Muscle to create these, or if some changes are coming. Thanks.
Who's doing Controller? @jenhicks or @jimmyDunne ? Thanks.

**Comment by chrisdembia** [comment]
The output macros are ready to use! There are other changes coming but they don't affect the ability for people to work on this issue.

**Comment by aymanhab** [comment]
@chrisdembia Trying to add outputs to Frames, it looked very elegant but failed to compile because the macro assumes (as far as I can tell):
 - [ ] The return type can be initialized to SimTK::NaN 
 - [ ] The function/accessor returns by value, so I can't reuse a method that returns a const reference.

Are these assumptions true, or am I misusing the macro? Thanks.

**Comment by chrisdembia** [comment]
Those assumptions are true. The first one can probably be lifted. The second one is somewhat harder to lift, at least in time for the hackathon. We'll have to discuss that second one with Shrinidhi.

**Comment by chrisdembia** [comment]
Actually, can you tell me which branch you're using? I can try a hackish thing for the return by reference.

**Comment by chrisdembia** [comment]
Actually, don't worry. I can create my own branch.

**Comment by aymanhab** [comment]
I created a branch off master as of yesterday to work with so you should be fine @chrisdembia and no need to worry about changing the mechanism now, I was mainly making sure myself and others on this issue do understand the assumptions since the error message from VisualStudio was a bit unclear. 

I'll proceed with these assumptions in mind and see how it goes. Thanks.

**Comment by chrisdembia** [comment]
@aymanhab see https://github.com/opensim-org/opensim-core/tree/output-return-by-ref if you're interested.

**Comment by chrisdembia** [comment]
That branch should address both assumptions.

**Comment by aymanhab** [comment]
@chrisdembia I have commented out the initialization to NaN so I can proceed since SimTK::Transform can't be initialized to NaN (and probably other types as well, e.g String outputs? are these allowed?) Thanks.

**Comment by chrisdembia** [comment]
@aymanhab do you plan to create one PR or multiple small ones?

**Comment by aymanhab** [comment]
Multiple small ones.

**Comment by aymanhab** [comment]
Pending the change in #839, I did add outputs to Frame, PathSpring. 
Trying to access outputs for display in GUI failed due to #837
Controller depends on List Outputs per earlier discussion, are these ready @chrisdembia ?

**Comment by chrisdembia** [comment]
Yes; List Outputs are merged and an example of how to use them can be found here: https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Sandbox/futureIKListOutputs.cpp#L40.

**Comment by aymanhab** [comment]
GeometryPath: Length, Velocity
Joint loads 
Actuator power
Force Potential energy
Kinetic and Potential energy on model

**Comment by aymanhab** [comment]
Geometry path "speed" is the name of the Cache entry used for LengehteningSpeed. Any preference? @chrisdembia or @aseth1 ? I stuck with "speed".
Joint loads as far as I can tell require passing in Forces, so are not purely function of state. Is that true @msdemers ?

**Comment by chrisdembia** [comment]
> Geometry path "speed" is the name of the Cache entry used for LengehteningSpeed. Any preference? @chrisdembia or @aseth1 ? I stuck with "speed".

I commented on this on the relevant line. Unfortunately, I advocated "lengthening_speed" :/

**Comment by aymanhab** [comment]
Sure, thanks @chrisdembia

**Comment by msdemers** [comment]
I'm not sure what you mean by "passing in forces". Are you talking about the option for the JointReactionsAnalysis? That's just a workaround for using static optimization results, which are independent of a simulation.

If you have the state an realize to acceleration stage, you can get the reaction forces. You'll get the reaction forces due to the current dynamics, including the forces already in the model. I believe either the simbody or simbodyengine methods even check and take care of realizing to acceleration for you.

**Comment by aymanhab** [comment]
Thanks @msdemers yes I looked into JointReactions but wasn't clear on the intention. Thanks for the clear up. 
That said, the Simbody method computes reaction forces for all joints at the same time not those for specific joints. Does it make sense to add an output method that gets the full list and fish out the relevant part for every Joint vs. have one for the whole model instead?

**Comment by msdemers** [comment]
@aymanhab Sherm wrote newer, more computationally efficient methods to get individual joint reaction loads in specific frames. You no longer need to get them all at once for the whole model. Will look and get you the name.

**Comment by msdemers** [comment]
Here are the relevant simbody methods on mobilized body.  You can get the MobilizedBody/s from the joint directly

MobilizedBody::findMobilizerReactionOnBodyAtMInGround(const State& state)
MobilizedBody::findMobilizerReactionOnBodyAtOriginInGround(const State& state)
MobilizedBody::findMobilizerReactionOnParentAtFInGround(const State& state)
MobilizedBody::findMobilizerReactionOnParentAtOriginInGround(const State& state)

**Comment by msdemers** [comment]
Oh and also @aymanhab , you may not want to looks at JointReactionsAnalysis as an example of anything. Remember that was the first piece of software I wrote while learning c++... first.c++.ever. Definitely not trustworthy. :fearful:

**Comment by aymanhab** [comment]
Thanks @msdemers. I understand the disclaimer :smile_cat:

**Comment by jenhicks** [comment]
Need to update this list with priorities for 4.0

**Comment by jenhicks** [comment]
I'm going to close this issue and we can add new ones as we identify needs/priorities
