### ISSUE TITLE
PassiveFiberForceAlongTendon reported by MuscleAnalysis for Millard2012EquilibriumMuscle can be negative

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#835]
Is this a bug?

I observed this with OpenSim 3.2 using the MuscleAnalysis. Perhaps it's due to small numerical inconsistencies resulting from using an approximate state, but even so, it seems like we shouldn't allow passive force to be negative.

I've attached the PassiveFiberForceAlongTendon.sto file as well as the files necessary to reproduce the issue.
[negative_passive_fiber_force_along_tendon.zip](https://github.com/opensim-org/opensim-core/files/174619/negative_passive_fiber_force_along_tendon.zip)

**Comment by tkuchida** [comment]
This is not a bug: passive fiber force can be negative in a Millard2012EquilibriumMuscle with damping.

Fiber force is calculated [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L1253). The muscles in your model all have `fiber_damping = 0.01` so there are "conservative passive forces" (`fp1 = fiso * fpe`) and "non-conservative passive forces" (`fp2 = fiso * beta*dlceN`), the latter of which can be negative. These two terms are summed [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L1003) and reported as _the_ passive fiber force [here](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Actuators/Millard2012EquilibriumMuscle.cpp#L1053) because the Muscle interface doesn't have separate slots for conservative and non-conservative passive forces.

I answered a related question on the Forum [here](https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=91&t=6818&p=17690&start=0&view=), where the user obtained nonzero passive forces even though the fiber was below its optimal fiber length. Should the Millard2012EquilibriumMuscle report only "conservative passive forces" (fiso * fpe) as "passive fiber force"?

cc: @aseth1

**Comment by aseth1** [comment]
It seems correct to report the total passive force due to stiffness and damping. Having the ability to get the fiber force due to strain (or damping) would also be helpful for users and help them to understand why they are seeing negative passive forces in some cases due to damping.

Updating the doxygen for Muscle:
```.cpp
    /** get the current passive fiber force (N) passive_force_length relationship */
    double getPassiveFiberForce(const SimTK::State& s) const;
```
would also be beneficial since the "passive_force_length relationship " typically implies the force-strain curve of the parallel elastic element, so it is understandable why there would be some surprise that the value returned includes damping.

To conclude:
 1. leave `Muscle::getPassiveFiberForce` as is, with it returning the total passive fiber force
 2. update the doxygen comment for  `Muscle::getPassiveFiberForce` to indicate it includes both force due to PE strain and damping
 3. (optional) add `Muscle::getPassiveDampingForce` so that users can easily assess how much of the total passive force is due to damping versus strain.

**Comment by tkuchida** [comment]
It does not seem possible to do :two: as stated because the base class shouldn't need to know anything about the unique features of any derived classes. How about "get the force applied by all passive elements in the fiber (N)"?

**Comment by aseth1** [comment]
@tkuchida yes good point. I agree it should say "all" or "total" and not attempt to parse out what the contributors.

In keeping with your point, then :three: should only be defined on muscle models with damping (e.g. `Millard2012EquilibriumMuscle`). The only trade-off is if one wants to access these values in a generic way from any Muscle, otherwise you have to treat `Millard2012EquilibriumMuscle` differently. But I believe this issue can be overcome with Outputs, since Outputs could be wired up to a Reporter by name, and a list of Outputs can be provided at the Component level. If you are using a Muscle that provides a damping term it will appear as Output.

**Comment by chrisdembia** [comment]
Thanks for the explanation. I agree with what you have settled on.
