### ISSUE TITLE
Consistent "isDisabled" vs "enabled" vs "is_disabled" properties

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#845]
See Reporters, Controllers for examples.

**Comment by aseth1** [comment]
I would like component writers to only focus on the affirmative case and NEVER check that flag to change their component's behavior. The enabling/disabling capability should be a feature of Component itself and it dictates whether (enabled) or not (disabled) that Component is included in the list (tree) of components used to build the system. It would then allow Components to be around for the sake of serialization but when disabled they have 0 impact on the system because they are simply not a part of the system. Then there would be no ambiguity about whether the flag works or not, which is the biggest frustration for users and then have to manually remove a component from XML.

**Comment by chrisdembia** [comment]
+1, but I still think it should be `<enabled>` or `<is_enabled>` rather than something with a negative in it.

**Comment by aymanhab** [comment]
I ran into this issue again when visualizing ContactGeometry as it turns out the isDisabled flag is likely ignored for ContactForce. We should have a design/plan for the long term even if we implement a small part of it in 4.0 (e.g. are all ModelComponents disablable? If yes what does it mean to disable a Body/Component-with-children? How does it affect visualization? Some SimTK level objects support the flag (e.g. Force, Constraint) but not others. Should we add a pass through the top level model component tree before "Connecting" and remove all disabled Components, so downstream functions can assume enabled all the time?

**Comment by tkuchida** [comment]
> what does it mean to disable a Body/Component-with-children?

In the case of an actuator, it seems like "disable" would mean the actuator is still part of the model but just not applying any force. This may be the desired effect since ignoring the component entirely would have side effects (e.g., adjusting indices into the Model's ForceSet). If the flag removes the component entirely, perhaps something like `is_ignored` would be clearer?

**Comment by jenhicks** [comment]
First step: rename disabled flags. I think we decided on the following.
Forces: appliesForce
Constraints: isEnforced
Controllers: enabled

**Comment by jenhicks** [comment]
Also need to reverse the logic.
