### ISSUE TITLE
Update README cpp example to reflect latest API changes.

### ISSUE THREAD

**Issue by chrisdembia** [opensim-org/opensim-core#884]

**Comment by chrisdembia** [comment]
@tkuchida and @jimmyDunne did you find any issues with the README example being out of date? If so, @carmichaelong might be interested in updating it.

**Comment by tkuchida** [comment]
> did you find any issues with the README example being out of date?

The example still works. A couple small things could be improved for readability (e.g., use `SimTK::White` rather than `Vec3(1, 1, 1)`; change `joint2` to `elbow` so the ConsoleReporter code is self documenting). I've made a couple small tweaks… PR coming soon to a repo near you. Are you okay with adding a ConsoleReporter to the README example?

**Comment by chrisdembia** [comment]
Sweet. 

 Are you okay with adding a ConsoleReporter to the README example?

Yes. 


Make sure to update testREADME too.
