### ISSUE TITLE
Expose SimbodyMatterSubsystem or parts of it to Scripting 

### ISSUE THREAD

**Issue by aymanhab** [opensim-org/opensim-core#924]
The issue came up multiple times on the forum most recently here https://simtk.org/forums/viewtopic.php?f=91&t=6520
It will be possible to expose it (per @chrisdembia ) or parts of it or some other classes along with it that would be helpful to script writers in Matlab and Python. We need to agree on scope.

**Comment by aymanhab** [comment]
@chrisdembia I did experiment with that and got SimbodyMatterSubsystem to be exposed but some related questions came up:
1. Do we need to expose MultibodySystem or DefaultSystemSubsystem, GeneralForceSubsystem? The risk is users could try to modify these directly (since const correctness is not enforced).This's even worse than you may think since calls to updXXX have side effect of invalidating while getXXX don't have the same side effects, a foreign concept in scripting.
2. If MultibodySystem is exposed, it maybe possible to create components that contribute to System resources entirely from Scripting, but that will likely require exposing more of the SimTK internals.
3. Do you think it'd be confusing if users see all methods in Doxygen and only some methods are available thru scripting while others are not?

**Comment by chrisdembia** [comment]
That's great that you were able to expose it.

> 1. Do we need to expose MultibodySystem or DefaultSystemSubsystem, GeneralForceSubsystem? The risk is users could try to modify these directly (since const correctness is not enforced).This's even worse than you may think since calls to updXXX have side effect of invalidating while getXXX don't have the same side effects, a foreign concept in scripting.

I don't think we should expose these, for now. I think the major benefit would be to expose the methods that do system-wide calculations (jacobians, mass matrix, etc.).I think we already have this risk with all of OpenSim's const methods.

> 3. Do you think it'd be confusing if users see all methods in Doxygen and only some methods are available thru scripting while others are not?

Yes this would be confusing. Perhaps the Scripting page on Doxygen could clarify this point, and tell users to use tab completion, etc. (`dir(model.getMatterSubsystem())` in python) to see which methods are available. I'll also highlight that we already have this issue anyway (that is, Model is currently only partially wrapped, since SimbodyMatterSubsystem previously was not exposed); so it's not a new issue (we have to deal with this anyway). We can also potentially generate separate documentation for python wrapping, (and also generate javadocs for java wrapping), etc.
